package main

// `lore sync install-action` / `uninstall-action` — opt-in GitHub workflow
// that runs `lore sync ci-merge` for pull requests (see sync_ci.go for why).
//
// Opt-in on purpose: the workflow spends Actions time, which is billed on
// private repositories, so lore never installs it on its own (unlike the
// local git hooks). The file is generated from sync_action.yml.tmpl with the
// same constants the CLI uses (driver outcomes, data paths), so the workflow
// and the binary it downloads cannot drift apart.
//
// Keeping the pin current: a file installed without --lore-version is pinned
// "auto". Every lore command checks it (refreshSyncActionPin, run with the
// git wiring) and, when the running lore is a newer release, rewrites the
// file to that release and asks the developer to commit it. It never
// downgrades, never touches a "fixed" pin or a hand-edited file (detected by
// the checksum line), and never acts from a development build.

import (
	"bytes"
	"context"
	"crypto/sha256"
	_ "embed"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"text/template"

	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"

	"saas/pkg/aicoder/errcodes"
	"saas/pkg/aicoder/gitsetup"
	"saas/pkg/aicoder/style"
	"saas/pkg/constants"
)

//go:embed sync_action.yml.tmpl
var syncActionTemplate string

// syncActionMarker opens every generated workflow file. install-action only
// overwrites, and uninstall-action only deletes, a file that starts with it.
const syncActionMarker = "# lore-sync-merge: generated by `lore sync install-action`"

// syncActionDir is where workflows live, relative to the repository root
// (GitHub only reads workflows from there, wherever the lore project is).
var syncActionDir = path.Join(".github", "workflows")

// syncActionBaseName names the workflow of a lore project at the repository
// root; a project in a subfolder gets "<base>-<folder-slug>.yml", so two lore
// projects in one repository (a monorepo) never overwrite each other's file.
const syncActionBaseName = "lore-sync-merge"

// syncActionExt is the workflow file extension.
const syncActionExt = ".yml"

// syncActionFileRel is the repository-relative workflow path for the lore
// project whose path prefix (lorePathPrefix: "" or "svc/api/") is given.
func syncActionFileRel(prefix string) string {
	return path.Join(syncActionDir, syncActionBaseName+syncActionSlug(prefix)+syncActionExt)
}

// syncActionSlug is "" for the root project, else "-" plus the folder path
// with slashes as dashes ("svc/api/" → "-svc-api"). It also keeps the
// workflow's concurrency group distinct per project.
func syncActionSlug(prefix string) string {
	s := strings.Trim(strings.ReplaceAll(prefix, "/", "-"), "-")
	if s == "" {
		return ""
	}
	return "-" + s
}

// syncActionPin says whether lore may move the workflow's lore version.
type syncActionPin string

const (
	// syncActionPinAuto: installed without --lore-version; follows the
	// newest lore release a developer runs in the repository.
	syncActionPinAuto syncActionPin = "auto"
	// syncActionPinFixed: installed with --lore-version (including
	// "latest"); never changed automatically.
	syncActionPinFixed syncActionPin = "fixed"
)

// Header lines written under the marker. The checksum covers the whole file
// except its own line, with line endings normalised to LF (a Windows
// checkout with CRLF is not a hand edit).
const (
	syncActionPinPrefix = "# lore-sync-merge-pin: "
	syncActionSumPrefix = "# lore-sync-merge-sum: "
	// syncActionSumPending is written while rendering, then replaced by the
	// real checksum of the rendered file.
	syncActionSumPending = "pending"
)

// syncActionMarkerVersion reads "(lore v0.1.11)" / "(lore latest)" from the
// marker line.
var syncActionMarkerVersion = regexp.MustCompile(`\(lore (v\d+\.\d+\.\d+|` + loreVersionLatest + `)\)`)

// loreReleaseRepo is the GitHub repository lore releases are published from;
// the workflow downloads the lore binary from its releases.
const loreReleaseRepo = "thesatellite-ai/lore"

// loreVersionLatest asks the workflow for the newest release instead of a
// pinned one.
const loreVersionLatest = "latest"

// fallbackDefaultBranch is used when the clone never recorded the remote's
// default branch and no --branch was given.
const fallbackDefaultBranch = "main"

// syncActionRemote is the remote whose default branch is looked up.
const syncActionRemote = "origin"

// releaseVersionPattern matches a lore version that has a published release
// (what goreleaser stamps into release builds: "0.1.10" or "v0.1.10").
// Development builds ("0.1.0-dev", "v0.1.9-4-gabc-dirty") do not.
var releaseVersionPattern = regexp.MustCompile(`^v?\d+\.\d+\.\d+$`)

// branchNamePattern accepts the branch names install-action writes into the
// workflow; anything else is refused rather than escaped into YAML.
var branchNamePattern = regexp.MustCompile(`^[A-Za-z0-9._/-]+$`)

// syncActionParams fills sync_action.yml.tmpl.
type syncActionParams struct {
	// Marker is syncActionMarker (first line of the file).
	Marker string
	// PinLine records the syncActionPin ("# lore-sync-merge-pin: auto").
	PinLine string
	// SumLine holds the checksum; renderSyncAction fills it in.
	SumLine string
	// NameSuffix and Slug tell projects in subfolders apart: the workflow's
	// display name (" (svc/api)") and its concurrency group ("-svc-api").
	NameSuffix string
	Slug       string
	// LoreVersion is the release tag ("v0.1.10") or loreVersionLatest.
	LoreVersion string
	// ReleaseURL is the base URL of that release's assets.
	ReleaseURL string
	// Manual drops the automatic triggers (workflow_dispatch only).
	Manual bool
	// DataGlob is the paths filter for lore data, repository-relative.
	DataGlob string
	// BranchesYAML is the YAML flow sequence of branches whose pushes
	// trigger the job.
	BranchesYAML string
	// DefaultBranch is the workflow_dispatch input's default.
	DefaultBranch string
	// WorkDir is the lore project directory, repository-relative ("." at
	// the root); ci-merge runs there.
	WorkDir string
	// OutcomeMerged / OutcomeNeedsHuman are the ci-merge outcomes the job
	// branches on.
	OutcomeMerged     ciMergeOutcome
	OutcomeNeedsHuman ciMergeOutcome
}

// syncActionOptions are install-action's inputs.
type syncActionOptions struct {
	branches    []string
	manual      bool
	loreVersion string
	// pin defaults to auto; installSyncAction sets fixed when --lore-version
	// was given.
	pin    syncActionPin
	dryRun bool
	force  bool
}

// syncActionResult is what install-action / uninstall-action report.
type syncActionResult struct {
	// Path is the workflow file.
	Path string `json:"path"`
	// Status is one of the syncAction* status constants.
	Status syncActionStatus `json:"status"`
	// LoreVersion is the lore release the workflow downloads.
	LoreVersion string `json:"lore_version,omitempty"`
	// Pin says whether lore keeps LoreVersion current (auto) or not (fixed).
	Pin syncActionPin `json:"pin,omitempty"`
	// Branches are the branches whose pushes trigger it (none when manual).
	Branches []string `json:"branches,omitempty"`
	// Manual is true when the workflow only runs by hand.
	Manual bool `json:"manual"`
	// Content is the generated file (--dry-run only).
	Content string `json:"content,omitempty"`
}

// syncActionStatus is what install-action / uninstall-action did (the
// "status" field of their --json output).
type syncActionStatus string

// install-action / uninstall-action statuses.
const (
	syncActionCreated   syncActionStatus = "created"
	syncActionUpdated   syncActionStatus = "updated"
	syncActionUnchanged syncActionStatus = "unchanged"
	syncActionDryRun    syncActionStatus = "dry-run"
	syncActionRemoved   syncActionStatus = "removed"
	syncActionAbsent    syncActionStatus = "not-installed"
)

// syncActionStatuses is every status (tests check each is printed).
var syncActionStatuses = []syncActionStatus{syncActionCreated, syncActionUpdated, syncActionUnchanged, syncActionDryRun, syncActionRemoved, syncActionAbsent}

// jsonKindSyncAction is the JSON envelope kind of both commands.
const jsonKindSyncAction = "sync.action"

func newSyncInstallActionCommand() *cobra.Command {
	var o syncActionOptions
	var asJSON bool
	cmd := &cobra.Command{
		Use:   "install-action",
		Short: "Add a GitHub workflow that merges lore data in pull requests (opt-in)",
		Long: `Writes .github/workflows/lore-sync-merge.yml at the repository root.

GitHub's merge button never runs lore's merge driver, so two pull requests
that edited the same lore row conflict there even when lore would merge them.
The workflow runs ` + "`lore sync ci-merge`" + ` for open pull requests: it merges the base
branch in with lore and pushes, only when every conflict is in lore data and
lore settles all of them. Anything else is left for a person.

It runs when lore data changes on a pull request or on a --branch (default:
the remote's default branch). It uses Actions time (billed on private
repositories); --manual installs it to run only when started by hand.

Commit the file to enable it. Its lore version keeps itself current: when a
developer runs a newer lore release here, their next lore command rewrites
the file to that release (commit it). --lore-version pins a version that is
never changed. A subfolder project gets its own lore-sync-merge-<folder>.yml.`,
		Example: `  lore sync install-action
  lore sync install-action --branch main --branch staging
  lore sync install-action --manual
  lore sync install-action --dry-run`,
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			if cmd.Flags().Changed(constants.FlagLoreVersion) {
				o.pin = syncActionPinFixed
			}
			res, err := installSyncAction(cmd.Context(), ".", o)
			if err != nil {
				return err
			}
			if asJSON {
				printJSON(jsonKindSyncAction, res, 0)
				return nil
			}
			printSyncAction(res)
			return nil
		},
	}
	cmd.Flags().StringArrayVar(&o.branches, constants.FlagBranch, nil, "branch whose pushes trigger the workflow (repeatable; default: the remote's default branch)")
	cmd.Flags().BoolVar(&o.manual, constants.FlagManual, false, "run only when started by hand (no automatic triggers)")
	cmd.Flags().StringVar(&o.loreVersion, constants.FlagLoreVersion, "", "lore release the workflow downloads: vX.Y.Z or latest (default: this lore's version)")
	cmd.Flags().BoolVar(&o.dryRun, constants.FlagDryRun, false, "print the workflow; write nothing")
	cmd.Flags().BoolVar(&o.force, constants.FlagForce, false, "overwrite a file at that path that lore did not generate")
	cmd.Flags().BoolVar(&asJSON, constants.FlagJSON, false, "JSON output")
	return cmd
}

func newSyncUninstallActionCommand() *cobra.Command {
	var force, asJSON bool
	cmd := &cobra.Command{
		Use:     "uninstall-action",
		Short:   "Remove the workflow added by install-action",
		Long:    "Deletes .github/workflows/lore-sync-merge.yml if lore generated it. Commit the deletion to disable it.",
		Example: "  lore sync uninstall-action",
		Args:    cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			res, err := uninstallSyncAction(cmd.Context(), ".", force)
			if err != nil {
				return err
			}
			if asJSON {
				printJSON(jsonKindSyncAction, res, 0)
				return nil
			}
			printSyncAction(res)
			return nil
		},
	}
	cmd.Flags().BoolVar(&force, constants.FlagForce, false, "delete the file even if lore did not generate it")
	cmd.Flags().BoolVar(&asJSON, constants.FlagJSON, false, "JSON output")
	return cmd
}

// installSyncAction renders and writes the workflow for the project at dir.
func installSyncAction(ctx context.Context, dir string, o syncActionOptions) (syncActionResult, error) {
	repo, err := gitsetup.Open(ctx, dir)
	if err != nil {
		return syncActionResult{}, errcodes.New(errcodes.Unsupported, "install-action needs a git repository").WithCause(err)
	}
	params, err := syncActionParamsFor(ctx, repo.Toplevel, dir, o)
	if err != nil {
		return syncActionResult{}, err
	}
	content, err := renderSyncAction(params)
	if err != nil {
		return syncActionResult{}, errcodes.New(errcodes.Internal, "render workflow").WithCause(err)
	}
	prefix := lorePathPrefix(repo.Toplevel, dir)
	file := filepath.Join(repo.Toplevel, filepath.FromSlash(syncActionFileRel(prefix)))
	res := syncActionResult{Path: file, LoreVersion: params.LoreVersion, Pin: syncActionPinAuto, Manual: o.manual}
	if o.pin != "" {
		res.Pin = o.pin
	}
	if !o.manual {
		res.Branches = branchesOrDefault(ctx, dir, o.branches)
	}
	if o.dryRun {
		res.Status, res.Content = syncActionDryRun, content
		return res, nil
	}
	existing, err := os.ReadFile(file)
	switch {
	case errors.Is(err, fs.ErrNotExist):
		res.Status = syncActionCreated
	case err != nil:
		return res, errcodes.New(errcodes.Internal, "read "+file).WithCause(err)
	case string(existing) == content:
		res.Status = syncActionUnchanged
		return res, nil
	case !strings.HasPrefix(string(existing), syncActionMarker) && !o.force:
		return res, errcodes.New(errcodes.AlreadyInitialized, file+" exists and was not generated by lore").
			WithHint("move it away, or pass --force to overwrite it")
	default:
		res.Status = syncActionUpdated
	}
	if err := writeSyncActionFile(file, content); err != nil {
		return res, errcodes.New(errcodes.Internal, "write "+file).WithCause(err)
	}
	if err := removeLegacySyncAction(repo.Toplevel, prefix); err != nil {
		return res, errcodes.New(errcodes.Internal, "remove the old shared workflow file").WithCause(err)
	}
	return res, nil
}

// writeSyncActionFile writes content atomically (temp file + rename), so two
// lore processes refreshing at once never leave a half-written workflow.
func writeSyncActionFile(file, content string) error {
	if err := os.MkdirAll(filepath.Dir(file), syncDirMode); err != nil {
		return err
	}
	tmp, err := os.CreateTemp(filepath.Dir(file), "."+filepath.Base(file)+".tmp-*")
	if err != nil {
		return err
	}
	name := tmp.Name()
	if _, err := tmp.WriteString(content); err != nil {
		_ = tmp.Close()
		_ = os.Remove(name) // the write error is the one to report
		return err
	}
	if err := tmp.Close(); err != nil {
		_ = os.Remove(name)
		return err
	}
	if err := os.Chmod(name, syncFileMode); err != nil {
		_ = os.Remove(name)
		return err
	}
	return os.Rename(name, file)
}

// legacySyncActionFor returns the shared root-named workflow (the only name
// lore v0.1.11 wrote) when it belongs to the subfolder project at prefix, so
// installing or refreshing that project moves it to the project's own name.
// "" when there is none, or it belongs to another project.
func legacySyncActionFor(toplevel, prefix string) string {
	if prefix == "" {
		return "" // the root project's name never changed
	}
	file := filepath.Join(toplevel, filepath.FromSlash(syncActionFileRel("")))
	b, err := os.ReadFile(file)
	if err != nil || !strings.HasPrefix(string(b), syncActionMarker) {
		return ""
	}
	s, err := parseSyncAction(string(b))
	if err != nil || s.workDir != strings.TrimSuffix(prefix, "/") {
		return ""
	}
	return file
}

// removeLegacySyncAction deletes the subfolder project's old root-named file
// after its own file was written.
func removeLegacySyncAction(toplevel, prefix string) error {
	if legacy := legacySyncActionFor(toplevel, prefix); legacy != "" {
		return os.Remove(legacy)
	}
	return nil
}

// uninstallSyncAction deletes the generated workflow.
func uninstallSyncAction(ctx context.Context, dir string, force bool) (syncActionResult, error) {
	repo, err := gitsetup.Open(ctx, dir)
	if err != nil {
		return syncActionResult{}, errcodes.New(errcodes.Unsupported, "uninstall-action needs a git repository").WithCause(err)
	}
	prefix := lorePathPrefix(repo.Toplevel, dir)
	file := filepath.Join(repo.Toplevel, filepath.FromSlash(syncActionFileRel(prefix)))
	if _, err := os.Stat(file); errors.Is(err, fs.ErrNotExist) {
		if legacy := legacySyncActionFor(repo.Toplevel, prefix); legacy != "" {
			file = legacy
		}
	}
	res := syncActionResult{Path: file}
	existing, err := os.ReadFile(file)
	if errors.Is(err, fs.ErrNotExist) {
		res.Status = syncActionAbsent
		return res, nil
	}
	if err != nil {
		return res, errcodes.New(errcodes.Internal, "read "+file).WithCause(err)
	}
	if !strings.HasPrefix(string(existing), syncActionMarker) && !force {
		return res, errcodes.New(errcodes.InvalidInput, file+" was not generated by lore; refusing to delete it").
			WithHint("pass --force to delete it anyway")
	}
	if err := os.Remove(file); err != nil {
		return res, errcodes.New(errcodes.Internal, "remove "+file).WithCause(err)
	}
	res.Status = syncActionRemoved
	return res, nil
}

// syncActionParamsFor validates options and derives the template inputs.
func syncActionParamsFor(ctx context.Context, toplevel, dir string, o syncActionOptions) (syncActionParams, error) {
	ver, err := workflowLoreVersion(o.loreVersion, version)
	if err != nil {
		return syncActionParams{}, err
	}
	branches := branchesOrDefault(ctx, dir, o.branches)
	for _, b := range branches {
		if !branchNamePattern.MatchString(b) {
			return syncActionParams{}, errcodes.New(errcodes.InvalidInput, fmt.Sprintf("branch name %q has characters install-action does not write into a workflow", b))
		}
	}
	branchesYAML, err := json.Marshal(branches) // a JSON array is a valid YAML flow sequence
	if err != nil {
		return syncActionParams{}, errcodes.New(errcodes.Internal, "encode branches").WithCause(err)
	}
	prefix := lorePathPrefix(toplevel, dir)
	workDir := strings.TrimSuffix(prefix, "/")
	nameSuffix := ""
	if workDir == "" {
		workDir = repoRootRel
	} else {
		nameSuffix = " (" + workDir + ")"
	}
	pin := o.pin
	if pin == "" {
		pin = syncActionPinAuto
	}
	return syncActionParams{
		Marker:            syncActionMarker,
		PinLine:           syncActionPinPrefix + string(pin),
		NameSuffix:        nameSuffix,
		Slug:              syncActionSlug(prefix),
		LoreVersion:       ver,
		ReleaseURL:        releaseAssetURL(ver),
		Manual:            o.manual,
		DataGlob:          prefix + dataRel + "/**",
		BranchesYAML:      string(branchesYAML),
		DefaultBranch:     branches[0],
		WorkDir:           workDir,
		OutcomeMerged:     ciMergeMerged,
		OutcomeNeedsHuman: ciMergeNeedsHuman,
	}, nil
}

// branchesOrDefault returns the requested branches, or the remote's default
// branch (fallbackDefaultBranch when the clone never recorded one).
func branchesOrDefault(ctx context.Context, dir string, requested []string) []string {
	if len(requested) > 0 {
		return requested
	}
	if b, ok := gitsetup.DefaultBranch(ctx, dir, syncActionRemote); ok {
		return []string{b}
	}
	return []string{fallbackDefaultBranch}
}

// workflowLoreVersion picks the release the workflow downloads: the flag when
// given, else this binary's own version when it is a published release, else
// the latest release (a development build has no release to pin to).
func workflowLoreVersion(flag, own string) (string, error) {
	pick := func(v string) string { return "v" + strings.TrimPrefix(v, "v") }
	switch {
	case flag == loreVersionLatest:
		return loreVersionLatest, nil
	case flag != "":
		if !releaseVersionPattern.MatchString(flag) {
			return "", errcodes.New(errcodes.InvalidInput, fmt.Sprintf("--%s %q: want vX.Y.Z or %s", constants.FlagLoreVersion, flag, loreVersionLatest))
		}
		return pick(flag), nil
	case releaseVersionPattern.MatchString(own):
		return pick(own), nil
	default:
		return loreVersionLatest, nil
	}
}

// releaseAssetURL is the base URL of a release's downloadable assets.
func releaseAssetURL(ver string) string {
	base := "https://github.com/" + loreReleaseRepo + "/releases"
	if ver == loreVersionLatest {
		return base + "/latest/download"
	}
	return base + "/download/" + ver
}

// renderSyncAction fills the template and stamps the checksum line. It uses
// [[ ]] delimiters because the workflow itself is full of GitHub's ${{ }}
// expressions.
func renderSyncAction(p syncActionParams) (string, error) {
	tmpl, err := template.New("workflow").Delims("[[", "]]").Option("missingkey=error").Parse(syncActionTemplate)
	if err != nil {
		return "", err
	}
	p.SumLine = syncActionSumPrefix + syncActionSumPending
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, p); err != nil {
		return "", err
	}
	out := buf.String()
	return strings.Replace(out, p.SumLine, syncActionSumPrefix+syncActionChecksum(out), 1), nil
}

// syncActionChecksum hashes a workflow file without its checksum line, with
// line endings normalised to LF.
func syncActionChecksum(content string) string {
	var kept []string
	for _, l := range strings.Split(strings.ReplaceAll(content, "\r\n", "\n"), "\n") {
		if !strings.HasPrefix(l, syncActionSumPrefix) {
			kept = append(kept, l)
		}
	}
	sum := sha256.Sum256([]byte(strings.Join(kept, "\n")))
	return hex.EncodeToString(sum[:])
}

// syncActionSettings is what an installed workflow file says about itself:
// enough to render it again with another lore version.
type syncActionSettings struct {
	// version is the pinned release ("v0.1.11") or loreVersionLatest.
	version string
	// pin is auto or fixed (files written by v0.1.11 have no pin line and
	// were all installed with the default, so they read as auto).
	pin syncActionPin
	// manual: only workflow_dispatch triggers.
	manual bool
	// branches are the push branches, or [dispatch default] when manual.
	branches []string
	// workDir is the project folder the merge step runs in ("." = root).
	workDir string
	// sum is the recorded checksum ("" for files without one).
	sum string
}

// syncActionFileYAML is the slice of the workflow parseSyncAction reads.
type syncActionFileYAML struct {
	On struct {
		Push *struct {
			Branches []string `yaml:"branches"`
		} `yaml:"push"`
		Dispatch struct {
			Inputs struct {
				Base struct {
					Default string `yaml:"default"`
				} `yaml:"base"`
			} `yaml:"inputs"`
		} `yaml:"workflow_dispatch"`
	} `yaml:"on"`
	Jobs map[string]struct {
		Steps []struct {
			Run              string `yaml:"run"`
			WorkingDirectory string `yaml:"working-directory"`
		} `yaml:"steps"`
	} `yaml:"jobs"`
}

// parseSyncAction reads a generated workflow's settings back from its
// header lines and its YAML.
func parseSyncAction(content string) (syncActionSettings, error) {
	content = strings.ReplaceAll(content, "\r\n", "\n")
	first, _, _ := strings.Cut(content, "\n")
	m := syncActionMarkerVersion.FindStringSubmatch(first)
	if !strings.HasPrefix(first, syncActionMarker) || m == nil {
		return syncActionSettings{}, fmt.Errorf("not a lore-generated workflow (marker line %q)", first)
	}
	s := syncActionSettings{version: m[1], pin: syncActionPinAuto}
	for _, l := range strings.Split(content, "\n") {
		switch {
		case strings.HasPrefix(l, syncActionPinPrefix):
			s.pin = syncActionPin(strings.TrimPrefix(l, syncActionPinPrefix))
		case strings.HasPrefix(l, syncActionSumPrefix):
			s.sum = strings.TrimPrefix(l, syncActionSumPrefix)
		}
	}
	if s.pin != syncActionPinAuto && s.pin != syncActionPinFixed {
		return syncActionSettings{}, fmt.Errorf("unknown pin %q", s.pin)
	}
	var doc syncActionFileYAML
	if err := yaml.Unmarshal([]byte(content), &doc); err != nil {
		return syncActionSettings{}, fmt.Errorf("workflow YAML: %w", err)
	}
	if doc.On.Push == nil {
		s.manual = true
		if d := doc.On.Dispatch.Inputs.Base.Default; d != "" {
			s.branches = []string{d}
		}
	} else {
		s.branches = doc.On.Push.Branches
	}
	if len(s.branches) == 0 {
		return syncActionSettings{}, fmt.Errorf("workflow names no branch")
	}
	for _, job := range doc.Jobs {
		for _, st := range job.Steps {
			if strings.Contains(st.Run, "lore sync ci-merge") {
				s.workDir = st.WorkingDirectory
			}
		}
	}
	if s.workDir == "" {
		return syncActionSettings{}, fmt.Errorf("workflow has no ci-merge step")
	}
	return s, nil
}

// syncActionRefresh reports what refreshSyncActionPin did. All fields empty
// means there was nothing to do.
type syncActionRefresh struct {
	// Path is the workflow file that was rewritten (or would have been).
	Path string `json:"path,omitempty"`
	// From and To are the old and new pinned versions when it was rewritten.
	From string `json:"from,omitempty"`
	To   string `json:"to,omitempty"`
	// Note explains why an out-of-date file was left alone (hand-edited,
	// unreadable).
	Note string `json:"note,omitempty"`
}

// refreshSyncActionPin moves an auto-pinned workflow of the lore project at
// root to own, the running lore's version, when that is a newer release.
// See the file comment for every case it deliberately leaves alone.
func refreshSyncActionPin(ctx context.Context, root, own string) (syncActionRefresh, error) {
	target := ""
	if releaseVersionPattern.MatchString(own) {
		target = "v" + strings.TrimPrefix(own, "v")
	}
	if target == "" {
		return syncActionRefresh{}, nil // a development build has no release to pin to
	}
	repo, err := gitsetup.Open(ctx, root)
	if err != nil {
		return syncActionRefresh{}, err
	}
	prefix := lorePathPrefix(repo.Toplevel, root)
	file := filepath.Join(repo.Toplevel, filepath.FromSlash(syncActionFileRel(prefix)))
	b, err := os.ReadFile(file)
	if errors.Is(err, fs.ErrNotExist) {
		if legacy := legacySyncActionFor(repo.Toplevel, prefix); legacy != "" {
			file = legacy
			b, err = os.ReadFile(file)
		}
	}
	if errors.Is(err, fs.ErrNotExist) {
		return syncActionRefresh{}, nil // not installed: never created here
	}
	if err != nil {
		return syncActionRefresh{}, err
	}
	content := string(b)
	if !strings.HasPrefix(content, syncActionMarker) {
		return syncActionRefresh{}, nil // someone else's file
	}
	s, err := parseSyncAction(content)
	if err != nil {
		return syncActionRefresh{Path: file, Note: "cannot read its settings (" + err.Error() + "); not updating it"}, nil
	}
	if s.pin != syncActionPinAuto {
		return syncActionRefresh{}, nil
	}
	if s.version != loreVersionLatest && !releaseLess(s.version, target) {
		return syncActionRefresh{}, nil // same or newer: never downgrade
	}
	o := syncActionOptions{branches: s.branches, manual: s.manual, pin: syncActionPinAuto}
	if edited, err := syncActionEdited(ctx, repo.Toplevel, root, content, s, o); err != nil || edited {
		if err != nil {
			return syncActionRefresh{}, err
		}
		return syncActionRefresh{Path: file, Note: "edited by hand, so lore no longer updates it; re-run `lore sync install-action` to take " + target}, nil
	}
	o.loreVersion = target
	params, err := syncActionParamsFor(ctx, repo.Toplevel, root, o)
	if err != nil {
		return syncActionRefresh{}, err
	}
	next, err := renderSyncAction(params)
	if err != nil {
		return syncActionRefresh{}, err
	}
	dest := filepath.Join(repo.Toplevel, filepath.FromSlash(syncActionFileRel(prefix)))
	if err := writeSyncActionFile(dest, next); err != nil {
		return syncActionRefresh{}, err
	}
	if dest != file {
		if err := os.Remove(file); err != nil {
			return syncActionRefresh{}, err
		}
	}
	return syncActionRefresh{Path: dest, From: s.version, To: target}, nil
}

// syncActionEdited reports whether a generated file was changed by hand. A
// file with a checksum line is checked against it. Files from before the
// checksum (lore v0.1.11) are rendered again with their own settings and
// compared line by line, ignoring comments (the header changed since).
func syncActionEdited(ctx context.Context, toplevel, root, content string, s syncActionSettings, o syncActionOptions) (bool, error) {
	if s.sum != "" {
		return syncActionChecksum(content) != s.sum, nil
	}
	o.loreVersion = s.version
	params, err := syncActionParamsFor(ctx, toplevel, root, o)
	if err != nil {
		return false, err
	}
	again, err := renderSyncAction(params)
	if err != nil {
		return false, err
	}
	return yamlLines(again) != yamlLines(content), nil
}

// yamlLines drops comment lines and normalises line endings.
func yamlLines(content string) string {
	var kept []string
	for _, l := range strings.Split(strings.ReplaceAll(content, "\r\n", "\n"), "\n") {
		if !strings.HasPrefix(strings.TrimSpace(l), "#") {
			kept = append(kept, l)
		}
	}
	return strings.Join(kept, "\n")
}

// releaseLess reports whether release tag a ("v0.1.9") is older than b.
// Both must match releaseVersionPattern.
func releaseLess(a, b string) bool {
	pa, pb := releaseParts(a), releaseParts(b)
	for i := range pa {
		if pa[i] != pb[i] {
			return pa[i] < pb[i]
		}
	}
	return false
}

// releaseParts splits "v1.2.3" into its three numbers (zeros on bad input,
// which releaseVersionPattern has already excluded).
func releaseParts(v string) [3]int {
	var out [3]int
	for i, p := range strings.SplitN(strings.TrimPrefix(v, "v"), ".", len(out)) {
		n, err := strconv.Atoi(p)
		if err == nil {
			out[i] = n
		}
	}
	return out
}

// printSyncAction renders an install/uninstall result for a terminal.
func printSyncAction(res syncActionResult) {
	switch res.Status {
	case syncActionDryRun:
		fmt.Print(res.Content)
		return
	case syncActionAbsent:
		fmt.Printf("· no lore workflow at %s\n", res.Path)
		return
	case syncActionRemoved:
		fmt.Printf("%s removed %s — commit the deletion to disable it\n", style.Success("✓"), res.Path)
		return
	case syncActionUnchanged:
		fmt.Printf("· %s is already up to date\n", res.Path)
		return
	}
	fmt.Printf("%s %s %s\n", style.Success("✓"), res.Status, res.Path)
	if res.Pin == syncActionPinFixed {
		fmt.Printf("  downloads lore %s (pinned: never updated automatically)\n", res.LoreVersion)
	} else {
		fmt.Printf("  downloads lore %s; lore moves it to newer releases as developers upgrade (commit those updates)\n", res.LoreVersion)
	}
	if res.Manual {
		fmt.Println("  runs only when started by hand (Actions → lore sync merge → Run workflow)")
	} else {
		fmt.Printf("  runs when lore data changes on a pull request or on: %s\n", strings.Join(res.Branches, ", "))
	}
	fmt.Println("  commit the file to enable it; add a LORE_SYNC_TOKEN secret if required checks must re-run on its merges")
}
