# https://taskfile.dev

version: "3"

dotenv: [".env"]

includes:
  lace:
    taskfile: ./lace/Taskfile.yml
    dir: ./lace
  dbent:
    taskfile: ./dbent/Taskfile.yml
    dir: ./dbent
  saas:
    taskfile: ./saas/Taskfile.yml
    dir: ./saas

  # CUSTOM
  lore:
    taskfile: ./Taskfile.lore.yml
    dir: ./
  # END CUSTOM

tasks:
  build:
    desc: alias → lore:build
    cmds:
      - task: lore:build

  workvendor:
    desc: fix work vendor mismatch on server
    cmds:
      - |
        set -ex
        for d in $(sed -n '/^use *(/,/^)/p' go.work | tail -n +2 | sed '$d' | sed 's/^[[:space:]]*//; s/[[:space:]]*$//'); do
          echo ">> Removing go.sum for '$d'"
          (cd "$d" && rm -f go.sum)
        done
      - go work vendor

  upgrade:
    desc: update all go modules in go.work
    cmds:
      - |
        set -ex
        for d in $(sed -n '/^use *(/,/^)/p' go.work | tail -n +2 | sed '$d' | sed 's/^[[:space:]]*//; s/[[:space:]]*$//'); do
          echo ">> Updating '$d'"
          ls -ld "$d"
          (cd "$d" && go get -u ./... && go mod tidy)
        done
      - task workvendor

  lint:
    desc: gofmt + go vet on all modules
    cmds:
      - gofmt -w $(find . -name '*.go' -not -path './vendor/*' -not -path '*/gen/*' -not -path './.git/*')
      - go vet ./...
