package constants

// Cobra flag names. Centralizing these prevents typos in cmd.Flags().Changed
// (which silently returns false on misspelled names) and makes renames safe.
const (
	// Universal
	FlagDB         = "db"
	FlagProject    = "project"
	FlagRepo       = "repo"
	FlagReadOnly   = "read-only"
	FlagJSON       = "json"
	FlagColor      = "color"
	FlagAll        = "all"
	FlagAllRepos   = "all-repos"
	FlagMasterOnly = "master-only"
	FlagNoInherit  = "no-inherit"
	FlagLimit      = "limit"
	FlagDryRun     = "dry-run"
	FlagConfirm    = "confirm"
	FlagIDs        = "ids"
	FlagInclude    = "include"
	FlagExclude    = "exclude"
	FlagJSONOutput = "json-output"

	// Common entity fields
	FlagTitle       = "title"
	FlagName        = "name"
	FlagBody        = "body"
	FlagDescription = "description"
	FlagStatus      = "status"
	FlagPriority    = "priority"
	FlagSeverity    = "severity"
	FlagActivation  = "activation"
	FlagKind        = "kind"
	FlagCategory    = "category"
	FlagSource      = "source"
	FlagSourceRef   = "source-ref"
	FlagGlobs       = "globs"
	FlagDue         = "due"
	FlagTarget      = "target"
	FlagOut         = "out"
	FlagNoPointer   = "no-pointer"
	FlagTags        = "tags"
	FlagCode        = "code"

	// Task / mission / relations
	FlagTasklist      = "tasklist"
	FlagMission       = "mission"
	FlagPlan          = "plan"
	FlagAssignedTo    = "assigned-to"
	FlagCreatedBy     = "created-by"
	FlagValidatedBy   = "validated-by"
	FlagFrom          = "from"
	FlagTo            = "to"
	FlagSupersedes    = "supersedes"
	FlagClearMission  = "clear-mission"
	FlagClearPlan     = "clear-plan"
	FlagClearDue      = "clear-due"
	FlagClearAssignee = "clear-assignee"
	FlagClearTarget   = "clear-target"
	FlagOnTable       = "on-table"
	FlagOnID          = "on-id"

	// Memory-specific
	FlagAllowSecrets    = "allow-secrets"
	FlagIncludeArchived = "include-archived"
	FlagArchived        = "archived"

	// Bench
	FlagEval             = "eval"
	FlagEvalSet          = "eval-set"
	FlagArm              = "arm"
	FlagArms             = "arms"
	FlagModel            = "model"
	FlagAs               = "as"
	FlagGrade            = "grade"
	FlagGraderCmd        = "grader-cmd"
	FlagGraderJudge      = "grader-judge"
	FlagGraderKind       = "grader-kind"
	FlagGraderRubric     = "grader-rubric"
	FlagGraderSpec       = "grader-spec"
	FlagBudgetBytes      = "budget-bytes"
	FlagByModel          = "by-model"
	FlagExpectedBaseline = "expected-baseline"
	FlagExpectedWith     = "expected-with"
	FlagClaudeMd         = "claude-md"

	// Bootstrap / project
	FlagNonInteractive = "non-interactive"
	FlagDisplayName    = "display-name"
	FlagAgent          = "agent"
	FlagAuthor         = "author"
	FlagCommit         = "commit"
	FlagCommittedAt    = "committed-at"
	FlagBaseURL        = "base-url"
	FlagConfig         = "config"
	FlagPaths          = "paths"
	FlagPath           = "path"
	FlagFile           = "file"
	FlagColumn         = "column"
	FlagFilter         = "filter"
	FlagEntity         = "entity"
	FlagError          = "error"
	FlagExpiring       = "expiring"
	FlagGoal           = "goal"
	FlagIncludeContent = "include-content"
	FlagAlways         = "always"
	FlagAccepted       = "accepted"
	FlagCustom         = "custom"
	FlagDone           = "done"
	FlagHigh           = "high"
)
