// Package tuigen holds the enttui register glue for the aicoder schema.
//
// It is GENERATED by the enttui codegen CLI (which lives in the entx-main
// monorepo: github.com/khanakia/entx/enttui). There is no generator in
// this repo — the CLI reads dbent/schema + its enttui.* annotations and
// writes one register_<entity>.go here plus register_all.go.
//
// Regenerate after a dbent schema change:
//
//	go generate ./saas/pkg/aicoder/tuigen     # or: task aicoder:tui:gen
//
// The `lore tui` subcommand (saas/cmd/cli/tui.go) calls
// tuigen.RegisterAll(app, client) with the SAME *ent.Client the rest of
// the CLI uses (resolved from .lore/lore.db via resolveContext).
//
//go:generate go run github.com/khanakia/entx/enttui/cmd/enttui --schema ../../../../dbent/schema --out . --package tuigen --ent-pkg dbent/gen/ent --scope project_id
package tuigen
