// Code generated by enttui. DO NOT EDIT.

package tuigen

import (
	"context"
	"dbent/gen/ent"
	entRun "dbent/gen/ent/run"
	"encoding/json"
	"fmt"

	"github.com/khanakia/entx/enttui/runtime"
)

// registerRun wires *ent.Run into the enttui runtime.
//
// Scope filtering: for every scope key configured in enttui.Config.ScopeFields
// that exists on this schema, the Fetch closure below reads opts.Scope[key]
// and applies a predicate when set. Caller drives this via app.SetScope(key, value).
func registerRun(app *runtime.App, client *ent.Client) {
	runtime.Register(app, runtime.EntitySpec[*ent.Run]{
		Kind:           "run",
		Display:        "Runs",
		Group:          "data",
		Icon:           "•",
		LabelKey:       "id",
		BodyKey:        "",
		IDKey:          "id",
		PageSize:       200,
		MultiSort:      true,
		ShowEdgeCounts: true,
		AllowBulkCopy:  false,
		AllowExport:    false,
		Default: runtime.DefaultView{
			SortField: "created_at",
			SortDir:   runtime.Desc,
			Mode:      "",
		},

		Fetch: func(ctx context.Context, opts runtime.ListOpts) ([]*ent.Run, int, error) {
			q := client.Run.Query()
			// Scope predicate — keyed generically via ListOpts.Scope so the
			// runtime stays decoupled from any specific field name.
			if v := opts.Scope["project_id"]; v != "" {
				q = q.Where(entRun.ProjectID(v))
			}
			// Legacy substring filter — used by the list+preview browser's
			// global `/` prompt. Phase E (Filters slice) supersedes this
			// in the table view but both can coexist.
			if opts.Filter != "" {
				q = q.Where(entRun.Or(
					entRun.IDContainsFold(opts.Filter),
					entRun.ProjectIDContainsFold(opts.Filter),
					entRun.KindContainsFold(opts.Filter),
					entRun.StatusStrContainsFold(opts.Filter),
					entRun.ActorIDContainsFold(opts.Filter),
					entRun.NotesContainsFold(opts.Filter),
				))
			}
			// Phase E — structured per-column filters. AND-composed.
			// Unsupported operators for a given field type fall through
			// silently rather than erroring — keeps the UI forgiving.
			for _, f := range opts.Filters {
				switch f.Field {
				case "id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entRun.IDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entRun.IDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entRun.IDContainsFold(f.Value))
					}
				case "project_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entRun.ProjectIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entRun.ProjectIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entRun.ProjectIDContainsFold(f.Value))
					}
				case "kind":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entRun.KindEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entRun.KindNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entRun.KindContainsFold(f.Value))
					}
				case "status_str":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entRun.StatusStrEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entRun.StatusStrNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entRun.StatusStrContainsFold(f.Value))
					}
				case "actor_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entRun.ActorIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entRun.ActorIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entRun.ActorIDContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entRun.ActorIDIsNil())
					case runtime.OpNotNull:
						q = q.Where(entRun.ActorIDNotNil())
					}
				case "notes":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entRun.NotesEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entRun.NotesNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entRun.NotesContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entRun.NotesIsNil())
					case runtime.OpNotNull:
						q = q.Where(entRun.NotesNotNil())
					}
				}
			}
			// Phase D — multi-column sort stack. Each Sort entry walks the
			// generated dispatch; unknown fields are silently skipped.
			if len(opts.Sort) > 0 {
				for _, k := range opts.Sort {
					switch k.Field {
					case "id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entRun.FieldID))
						} else {
							q = q.Order(ent.Desc(entRun.FieldID))
						}
					case "created_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entRun.FieldCreatedAt))
						} else {
							q = q.Order(ent.Desc(entRun.FieldCreatedAt))
						}
					case "updated_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entRun.FieldUpdatedAt))
						} else {
							q = q.Order(ent.Desc(entRun.FieldUpdatedAt))
						}
					case "project_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entRun.FieldProjectID))
						} else {
							q = q.Order(ent.Desc(entRun.FieldProjectID))
						}
					case "kind":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entRun.FieldKind))
						} else {
							q = q.Order(ent.Desc(entRun.FieldKind))
						}
					case "status_str":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entRun.FieldStatusStr))
						} else {
							q = q.Order(ent.Desc(entRun.FieldStatusStr))
						}
					case "actor_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entRun.FieldActorID))
						} else {
							q = q.Order(ent.Desc(entRun.FieldActorID))
						}
					case "started_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entRun.FieldStartedAt))
						} else {
							q = q.Order(ent.Desc(entRun.FieldStartedAt))
						}
					case "completed_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entRun.FieldCompletedAt))
						} else {
							q = q.Order(ent.Desc(entRun.FieldCompletedAt))
						}
					case "notes":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entRun.FieldNotes))
						} else {
							q = q.Order(ent.Desc(entRun.FieldNotes))
						}
					}
				}
			}
			total, err := q.Clone().Count(ctx)
			if err != nil {
				return nil, 0, err
			}
			rows, err := q.Offset(opts.Offset).Limit(opts.Limit).All(ctx)
			return rows, total, err
		},

		// Ent-native JSON for the `J` clipboard shortcut. *ent.Run
		// implements MarshalJSON so eager-loaded edges (from With*())
		// land in the output under `edges` automatically.
		JSON: func(r *ent.Run) ([]byte, error) { return json.Marshal(r) },

		Columns: []runtime.Column[*ent.Run]{
			{
				Key:        "id",
				Label:      "Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Run) string {
					return r.ID
				},
			},
			{
				Key:        "created_at",
				Label:      "Created At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Run) string {
					if r.CreatedAt.IsZero() {
						return ""
					}
					return r.CreatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "updated_at",
				Label:      "Updated At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Run) string {
					if r.UpdatedAt.IsZero() {
						return ""
					}
					return r.UpdatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "project_id",
				Label:      "Project Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Run) string {
					return r.ProjectID
				},
			},
			{
				Key:        "kind",
				Label:      "Kind",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Run) string {
					return r.Kind
				},
			},
			{
				Key:        "status_str",
				Label:      "Status Str",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Run) string {
					return r.StatusStr
				},
			},
			{
				Key:        "actor_id",
				Label:      "Actor Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Run) string {
					if r.ActorID == nil {
						return ""
					}
					return *r.ActorID
				},
			},
			{
				Key:        "started_at",
				Label:      "Started At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Run) string {
					if r.StartedAt == nil || r.StartedAt.IsZero() {
						return ""
					}
					return r.StartedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "completed_at",
				Label:      "Completed At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Run) string {
					if r.CompletedAt == nil || r.CompletedAt.IsZero() {
						return ""
					}
					return r.CompletedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "notes",
				Label:      "Notes",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Run) string {
					if r.Notes == nil {
						return ""
					}
					return *r.Notes
				},
			},
		},

		Edges: []runtime.EdgeSpec[*ent.Run]{
			{
				Name: "steps", Display: "RunSteps", Kind: runtime.EdgeDrill, Trigger: "t",
				// Count is emitted for BOTH upward and drill edges. For
				// upward edges it returns 0 or 1 (parent exists / doesn't).
				// For drill edges, the child row count.
				Count: func(ctx context.Context, r *ent.Run) (int, error) {
					return client.Run.QuerySteps(r).Count(ctx)
				},
				ResolveDrill: func(ctx context.Context, r *ent.Run) (runtime.EntityRefList, error) {
					ids, err := client.Run.QuerySteps(r).IDs(ctx)
					if err != nil {
						return runtime.EntityRefList{}, err
					}
					sids := make([]string, len(ids))
					for i, v := range ids {
						sids[i] = fmt.Sprint(v)
					}
					return runtime.EntityRefList{Kind: "runstep", IDs: sids}, nil
				},
			},
		},
	})
}
