// Code generated by enttui. DO NOT EDIT.

package tuigen

import (
	"context"
	"dbent/gen/ent"
	entLearnCandidate "dbent/gen/ent/learncandidate"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/khanakia/entx/enttui/runtime"
)

// registerLearnCandidate wires *ent.LearnCandidate into the enttui runtime.
//
// Scope filtering: for every scope key configured in enttui.Config.ScopeFields
// that exists on this schema, the Fetch closure below reads opts.Scope[key]
// and applies a predicate when set. Caller drives this via app.SetScope(key, value).
func registerLearnCandidate(app *runtime.App, client *ent.Client) {
	runtime.Register(app, runtime.EntitySpec[*ent.LearnCandidate]{
		Kind:           "learncandidate",
		Display:        "LearnCandidates",
		Group:          "data",
		Icon:           "•",
		LabelKey:       "id",
		BodyKey:        "",
		IDKey:          "id",
		PageSize:       200,
		MultiSort:      true,
		ShowEdgeCounts: true,
		AllowBulkCopy:  false,
		AllowExport:    false,
		Default: runtime.DefaultView{
			SortField: "created_at",
			SortDir:   runtime.Desc,
			Mode:      "",
		},

		Fetch: func(ctx context.Context, opts runtime.ListOpts) ([]*ent.LearnCandidate, int, error) {
			q := client.LearnCandidate.Query()
			// Scope predicate — keyed generically via ListOpts.Scope so the
			// runtime stays decoupled from any specific field name.
			if v := opts.Scope["project_id"]; v != "" {
				q = q.Where(entLearnCandidate.ProjectID(v))
			}
			// Legacy substring filter — used by the list+preview browser's
			// global `/` prompt. Phase E (Filters slice) supersedes this
			// in the table view but both can coexist.
			if opts.Filter != "" {
				q = q.Where(entLearnCandidate.Or(
					entLearnCandidate.IDContainsFold(opts.Filter),
					entLearnCandidate.ProjectIDContainsFold(opts.Filter),
					entLearnCandidate.RepoIDContainsFold(opts.Filter),
					entLearnCandidate.ProposedKindContainsFold(opts.Filter),
					entLearnCandidate.ProposedBodyContainsFold(opts.Filter),
					entLearnCandidate.SourceRefContainsFold(opts.Filter),
					entLearnCandidate.ProposedByActorIDContainsFold(opts.Filter),
					entLearnCandidate.ReviewedByActorIDContainsFold(opts.Filter),
					entLearnCandidate.JobIDContainsFold(opts.Filter),
				))
			}
			// Phase E — structured per-column filters. AND-composed.
			// Unsupported operators for a given field type fall through
			// silently rather than erroring — keeps the UI forgiving.
			for _, f := range opts.Filters {
				switch f.Field {
				case "id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entLearnCandidate.IDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entLearnCandidate.IDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entLearnCandidate.IDContainsFold(f.Value))
					}
				case "project_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entLearnCandidate.ProjectIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entLearnCandidate.ProjectIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entLearnCandidate.ProjectIDContainsFold(f.Value))
					}
				case "repo_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entLearnCandidate.RepoIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entLearnCandidate.RepoIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entLearnCandidate.RepoIDContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entLearnCandidate.RepoIDIsNil())
					case runtime.OpNotNull:
						q = q.Where(entLearnCandidate.RepoIDNotNil())
					}
				case "proposed_kind":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entLearnCandidate.ProposedKindEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entLearnCandidate.ProposedKindNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entLearnCandidate.ProposedKindContainsFold(f.Value))
					}
				case "proposed_body":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entLearnCandidate.ProposedBodyEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entLearnCandidate.ProposedBodyNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entLearnCandidate.ProposedBodyContainsFold(f.Value))
					}
				case "source_kind":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entLearnCandidate.SourceKindEQ(entLearnCandidate.SourceKind(f.Value)))
					case runtime.OpNeq:
						q = q.Where(entLearnCandidate.SourceKindNEQ(entLearnCandidate.SourceKind(f.Value)))
					case runtime.OpIn, runtime.OpNotIn:
						// Multi-select: condition value is a "|"-joined
						// list of enum strings. Empty entries are dropped.
						parts := strings.Split(f.Value, "|")
						vals := make([]entLearnCandidate.SourceKind, 0, len(parts))
						for _, p := range parts {
							if p == "" {
								continue
							}
							vals = append(vals, entLearnCandidate.SourceKind(p))
						}
						if len(vals) > 0 {
							if f.Op == runtime.OpIn {
								q = q.Where(entLearnCandidate.SourceKindIn(vals...))
							} else {
								q = q.Where(entLearnCandidate.SourceKindNotIn(vals...))
							}
						}
					}
				case "source_ref":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entLearnCandidate.SourceRefEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entLearnCandidate.SourceRefNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entLearnCandidate.SourceRefContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entLearnCandidate.SourceRefIsNil())
					case runtime.OpNotNull:
						q = q.Where(entLearnCandidate.SourceRefNotNil())
					}
				case "proposed_by_actor_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entLearnCandidate.ProposedByActorIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entLearnCandidate.ProposedByActorIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entLearnCandidate.ProposedByActorIDContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entLearnCandidate.ProposedByActorIDIsNil())
					case runtime.OpNotNull:
						q = q.Where(entLearnCandidate.ProposedByActorIDNotNil())
					}
				case "status":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entLearnCandidate.StatusEQ(entLearnCandidate.Status(f.Value)))
					case runtime.OpNeq:
						q = q.Where(entLearnCandidate.StatusNEQ(entLearnCandidate.Status(f.Value)))
					case runtime.OpIn, runtime.OpNotIn:
						// Multi-select: condition value is a "|"-joined
						// list of enum strings. Empty entries are dropped.
						parts := strings.Split(f.Value, "|")
						vals := make([]entLearnCandidate.Status, 0, len(parts))
						for _, p := range parts {
							if p == "" {
								continue
							}
							vals = append(vals, entLearnCandidate.Status(p))
						}
						if len(vals) > 0 {
							if f.Op == runtime.OpIn {
								q = q.Where(entLearnCandidate.StatusIn(vals...))
							} else {
								q = q.Where(entLearnCandidate.StatusNotIn(vals...))
							}
						}
					}
				case "reviewed_by_actor_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entLearnCandidate.ReviewedByActorIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entLearnCandidate.ReviewedByActorIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entLearnCandidate.ReviewedByActorIDContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entLearnCandidate.ReviewedByActorIDIsNil())
					case runtime.OpNotNull:
						q = q.Where(entLearnCandidate.ReviewedByActorIDNotNil())
					}
				case "job_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entLearnCandidate.JobIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entLearnCandidate.JobIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entLearnCandidate.JobIDContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entLearnCandidate.JobIDIsNil())
					case runtime.OpNotNull:
						q = q.Where(entLearnCandidate.JobIDNotNil())
					}
				}
			}
			// Phase D — multi-column sort stack. Each Sort entry walks the
			// generated dispatch; unknown fields are silently skipped.
			if len(opts.Sort) > 0 {
				for _, k := range opts.Sort {
					switch k.Field {
					case "id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entLearnCandidate.FieldID))
						} else {
							q = q.Order(ent.Desc(entLearnCandidate.FieldID))
						}
					case "created_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entLearnCandidate.FieldCreatedAt))
						} else {
							q = q.Order(ent.Desc(entLearnCandidate.FieldCreatedAt))
						}
					case "updated_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entLearnCandidate.FieldUpdatedAt))
						} else {
							q = q.Order(ent.Desc(entLearnCandidate.FieldUpdatedAt))
						}
					case "project_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entLearnCandidate.FieldProjectID))
						} else {
							q = q.Order(ent.Desc(entLearnCandidate.FieldProjectID))
						}
					case "repo_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entLearnCandidate.FieldRepoID))
						} else {
							q = q.Order(ent.Desc(entLearnCandidate.FieldRepoID))
						}
					case "proposed_kind":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entLearnCandidate.FieldProposedKind))
						} else {
							q = q.Order(ent.Desc(entLearnCandidate.FieldProposedKind))
						}
					case "proposed_body":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entLearnCandidate.FieldProposedBody))
						} else {
							q = q.Order(ent.Desc(entLearnCandidate.FieldProposedBody))
						}
					case "source_kind":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entLearnCandidate.FieldSourceKind))
						} else {
							q = q.Order(ent.Desc(entLearnCandidate.FieldSourceKind))
						}
					case "source_ref":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entLearnCandidate.FieldSourceRef))
						} else {
							q = q.Order(ent.Desc(entLearnCandidate.FieldSourceRef))
						}
					case "proposed_by_actor_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entLearnCandidate.FieldProposedByActorID))
						} else {
							q = q.Order(ent.Desc(entLearnCandidate.FieldProposedByActorID))
						}
					case "status":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entLearnCandidate.FieldStatus))
						} else {
							q = q.Order(ent.Desc(entLearnCandidate.FieldStatus))
						}
					case "reviewed_by_actor_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entLearnCandidate.FieldReviewedByActorID))
						} else {
							q = q.Order(ent.Desc(entLearnCandidate.FieldReviewedByActorID))
						}
					case "reviewed_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entLearnCandidate.FieldReviewedAt))
						} else {
							q = q.Order(ent.Desc(entLearnCandidate.FieldReviewedAt))
						}
					case "job_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entLearnCandidate.FieldJobID))
						} else {
							q = q.Order(ent.Desc(entLearnCandidate.FieldJobID))
						}
					}
				}
			}
			total, err := q.Clone().Count(ctx)
			if err != nil {
				return nil, 0, err
			}
			rows, err := q.Offset(opts.Offset).Limit(opts.Limit).All(ctx)
			return rows, total, err
		},

		// Ent-native JSON for the `J` clipboard shortcut. *ent.LearnCandidate
		// implements MarshalJSON so eager-loaded edges (from With*())
		// land in the output under `edges` automatically.
		JSON: func(r *ent.LearnCandidate) ([]byte, error) { return json.Marshal(r) },

		Columns: []runtime.Column[*ent.LearnCandidate]{
			{
				Key:        "id",
				Label:      "Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.LearnCandidate) string {
					return r.ID
				},
			},
			{
				Key:        "created_at",
				Label:      "Created At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.LearnCandidate) string {
					if r.CreatedAt.IsZero() {
						return ""
					}
					return r.CreatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "updated_at",
				Label:      "Updated At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.LearnCandidate) string {
					if r.UpdatedAt.IsZero() {
						return ""
					}
					return r.UpdatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "project_id",
				Label:      "Project Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.LearnCandidate) string {
					return r.ProjectID
				},
			},
			{
				Key:        "repo_id",
				Label:      "Repo Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.LearnCandidate) string {
					if r.RepoID == nil {
						return ""
					}
					return *r.RepoID
				},
			},
			{
				Key:        "proposed_kind",
				Label:      "Proposed Kind",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.LearnCandidate) string {
					return r.ProposedKind
				},
			},
			{
				Key:        "proposed_body",
				Label:      "Proposed Body",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.LearnCandidate) string {
					return r.ProposedBody
				},
			},
			{
				Key:        "source_kind",
				Label:      "Source Kind",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				EnumValues: []string{
					"agent-proposal",
					"learn-from",
					"plugin",
				},
				Get: func(r *ent.LearnCandidate) string {
					return string(r.SourceKind)
				},
			},
			{
				Key:        "source_ref",
				Label:      "Source Ref",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.LearnCandidate) string {
					if r.SourceRef == nil {
						return ""
					}
					return *r.SourceRef
				},
			},
			{
				Key:        "trust_score",
				Label:      "Trust Score",
				Sortable:   false,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.LearnCandidate) string {
					return fmt.Sprintf("%v", r.TrustScore)
				},
			},
			{
				Key:        "proposed_by_actor_id",
				Label:      "Proposed By Actor Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.LearnCandidate) string {
					if r.ProposedByActorID == nil {
						return ""
					}
					return *r.ProposedByActorID
				},
			},
			{
				Key:        "status",
				Label:      "Status",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				EnumValues: []string{
					"pending",
					"accepted",
					"rejected",
					"expired",
				},
				Get: func(r *ent.LearnCandidate) string {
					return string(r.Status)
				},
			},
			{
				Key:        "reviewed_by_actor_id",
				Label:      "Reviewed By Actor Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.LearnCandidate) string {
					if r.ReviewedByActorID == nil {
						return ""
					}
					return *r.ReviewedByActorID
				},
			},
			{
				Key:        "reviewed_at",
				Label:      "Reviewed At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.LearnCandidate) string {
					if r.ReviewedAt == nil || r.ReviewedAt.IsZero() {
						return ""
					}
					return r.ReviewedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "job_id",
				Label:      "Job Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.LearnCandidate) string {
					if r.JobID == nil {
						return ""
					}
					return *r.JobID
				},
			},
		},
	})
}
