// Code generated by enttui. DO NOT EDIT.

package tuigen

import (
	"context"
	"dbent/gen/ent"
	entMemoryCodeRef "dbent/gen/ent/memorycoderef"
	"encoding/json"
	"strings"

	"github.com/khanakia/entx/enttui/runtime"
)

// registerMemoryCodeRef wires *ent.MemoryCodeRef into the enttui runtime.
//
// Scope filtering: for every scope key configured in enttui.Config.ScopeFields
// that exists on this schema, the Fetch closure below reads opts.Scope[key]
// and applies a predicate when set. Caller drives this via app.SetScope(key, value).
func registerMemoryCodeRef(app *runtime.App, client *ent.Client) {
	runtime.Register(app, runtime.EntitySpec[*ent.MemoryCodeRef]{
		Kind:           "memorycoderef",
		Display:        "MemoryCodeRefs",
		Group:          "data",
		Icon:           "•",
		LabelKey:       "id",
		BodyKey:        "",
		IDKey:          "id",
		PageSize:       200,
		MultiSort:      true,
		ShowEdgeCounts: true,
		AllowBulkCopy:  false,
		AllowExport:    false,
		Default: runtime.DefaultView{
			SortField: "created_at",
			SortDir:   runtime.Desc,
			Mode:      "",
		},

		Fetch: func(ctx context.Context, opts runtime.ListOpts) ([]*ent.MemoryCodeRef, int, error) {
			q := client.MemoryCodeRef.Query()
			// Legacy substring filter — used by the list+preview browser's
			// global `/` prompt. Phase E (Filters slice) supersedes this
			// in the table view but both can coexist.
			if opts.Filter != "" {
				q = q.Where(entMemoryCodeRef.Or(
					entMemoryCodeRef.IDContainsFold(opts.Filter),
					entMemoryCodeRef.MemoryIDContainsFold(opts.Filter),
					entMemoryCodeRef.CodeFileIDContainsFold(opts.Filter),
				))
			}
			// Phase E — structured per-column filters. AND-composed.
			// Unsupported operators for a given field type fall through
			// silently rather than erroring — keeps the UI forgiving.
			for _, f := range opts.Filters {
				switch f.Field {
				case "id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entMemoryCodeRef.IDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entMemoryCodeRef.IDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entMemoryCodeRef.IDContainsFold(f.Value))
					}
				case "memory_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entMemoryCodeRef.MemoryIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entMemoryCodeRef.MemoryIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entMemoryCodeRef.MemoryIDContainsFold(f.Value))
					}
				case "code_file_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entMemoryCodeRef.CodeFileIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entMemoryCodeRef.CodeFileIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entMemoryCodeRef.CodeFileIDContainsFold(f.Value))
					}
				case "relation":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entMemoryCodeRef.RelationEQ(entMemoryCodeRef.Relation(f.Value)))
					case runtime.OpNeq:
						q = q.Where(entMemoryCodeRef.RelationNEQ(entMemoryCodeRef.Relation(f.Value)))
					case runtime.OpIn, runtime.OpNotIn:
						// Multi-select: condition value is a "|"-joined
						// list of enum strings. Empty entries are dropped.
						parts := strings.Split(f.Value, "|")
						vals := make([]entMemoryCodeRef.Relation, 0, len(parts))
						for _, p := range parts {
							if p == "" {
								continue
							}
							vals = append(vals, entMemoryCodeRef.Relation(p))
						}
						if len(vals) > 0 {
							if f.Op == runtime.OpIn {
								q = q.Where(entMemoryCodeRef.RelationIn(vals...))
							} else {
								q = q.Where(entMemoryCodeRef.RelationNotIn(vals...))
							}
						}
					}
				}
			}
			// Phase D — multi-column sort stack. Each Sort entry walks the
			// generated dispatch; unknown fields are silently skipped.
			if len(opts.Sort) > 0 {
				for _, k := range opts.Sort {
					switch k.Field {
					case "id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entMemoryCodeRef.FieldID))
						} else {
							q = q.Order(ent.Desc(entMemoryCodeRef.FieldID))
						}
					case "created_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entMemoryCodeRef.FieldCreatedAt))
						} else {
							q = q.Order(ent.Desc(entMemoryCodeRef.FieldCreatedAt))
						}
					case "updated_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entMemoryCodeRef.FieldUpdatedAt))
						} else {
							q = q.Order(ent.Desc(entMemoryCodeRef.FieldUpdatedAt))
						}
					case "memory_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entMemoryCodeRef.FieldMemoryID))
						} else {
							q = q.Order(ent.Desc(entMemoryCodeRef.FieldMemoryID))
						}
					case "code_file_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entMemoryCodeRef.FieldCodeFileID))
						} else {
							q = q.Order(ent.Desc(entMemoryCodeRef.FieldCodeFileID))
						}
					case "relation":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entMemoryCodeRef.FieldRelation))
						} else {
							q = q.Order(ent.Desc(entMemoryCodeRef.FieldRelation))
						}
					}
				}
			}
			total, err := q.Clone().Count(ctx)
			if err != nil {
				return nil, 0, err
			}
			rows, err := q.Offset(opts.Offset).Limit(opts.Limit).All(ctx)
			return rows, total, err
		},

		// Ent-native JSON for the `J` clipboard shortcut. *ent.MemoryCodeRef
		// implements MarshalJSON so eager-loaded edges (from With*())
		// land in the output under `edges` automatically.
		JSON: func(r *ent.MemoryCodeRef) ([]byte, error) { return json.Marshal(r) },

		Columns: []runtime.Column[*ent.MemoryCodeRef]{
			{
				Key:        "id",
				Label:      "Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.MemoryCodeRef) string {
					return r.ID
				},
			},
			{
				Key:        "created_at",
				Label:      "Created At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.MemoryCodeRef) string {
					if r.CreatedAt.IsZero() {
						return ""
					}
					return r.CreatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "updated_at",
				Label:      "Updated At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.MemoryCodeRef) string {
					if r.UpdatedAt.IsZero() {
						return ""
					}
					return r.UpdatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "memory_id",
				Label:      "Memory Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.MemoryCodeRef) string {
					return r.MemoryID
				},
			},
			{
				Key:        "code_file_id",
				Label:      "Code File Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.MemoryCodeRef) string {
					return r.CodeFileID
				},
			},
			{
				Key:        "relation",
				Label:      "Relation",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				EnumValues: []string{
					"references",
					"applies_to",
					"derived_from",
					"caused_by",
				},
				Get: func(r *ent.MemoryCodeRef) string {
					return string(r.Relation)
				},
			},
		},
	})
}
