// Code generated by enttui. DO NOT EDIT.

package tuigen

import (
	"context"
	"dbent/gen/ent"
	entComment "dbent/gen/ent/comment"
	"encoding/json"
	"fmt"

	"github.com/khanakia/entx/enttui/runtime"
)

// registerComment wires *ent.Comment into the enttui runtime.
//
// Scope filtering: for every scope key configured in enttui.Config.ScopeFields
// that exists on this schema, the Fetch closure below reads opts.Scope[key]
// and applies a predicate when set. Caller drives this via app.SetScope(key, value).
func registerComment(app *runtime.App, client *ent.Client) {
	runtime.Register(app, runtime.EntitySpec[*ent.Comment]{
		Kind:           "comment",
		Display:        "Comments",
		Group:          "data",
		Icon:           "•",
		LabelKey:       "id",
		BodyKey:        "body",
		IDKey:          "id",
		PageSize:       200,
		MultiSort:      true,
		ShowEdgeCounts: true,
		AllowBulkCopy:  false,
		AllowExport:    false,
		Default: runtime.DefaultView{
			SortField: "created_at",
			SortDir:   runtime.Desc,
			Mode:      "",
		},

		Fetch: func(ctx context.Context, opts runtime.ListOpts) ([]*ent.Comment, int, error) {
			q := client.Comment.Query()
			// Legacy substring filter — used by the list+preview browser's
			// global `/` prompt. Phase E (Filters slice) supersedes this
			// in the table view but both can coexist.
			if opts.Filter != "" {
				q = q.Where(entComment.Or(
					entComment.IDContainsFold(opts.Filter),
					entComment.EntityTableContainsFold(opts.Filter),
					entComment.EntityIDContainsFold(opts.Filter),
					entComment.CreatedByActorIDContainsFold(opts.Filter),
				))
			}
			// Phase E — structured per-column filters. AND-composed.
			// Unsupported operators for a given field type fall through
			// silently rather than erroring — keeps the UI forgiving.
			for _, f := range opts.Filters {
				switch f.Field {
				case "id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entComment.IDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entComment.IDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entComment.IDContainsFold(f.Value))
					}
				case "entity_table":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entComment.EntityTableEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entComment.EntityTableNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entComment.EntityTableContainsFold(f.Value))
					}
				case "entity_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entComment.EntityIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entComment.EntityIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entComment.EntityIDContainsFold(f.Value))
					}
				case "created_by_actor_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entComment.CreatedByActorIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entComment.CreatedByActorIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entComment.CreatedByActorIDContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entComment.CreatedByActorIDIsNil())
					case runtime.OpNotNull:
						q = q.Where(entComment.CreatedByActorIDNotNil())
					}
				}
			}
			// Phase D — multi-column sort stack. Each Sort entry walks the
			// generated dispatch; unknown fields are silently skipped.
			if len(opts.Sort) > 0 {
				for _, k := range opts.Sort {
					switch k.Field {
					case "id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entComment.FieldID))
						} else {
							q = q.Order(ent.Desc(entComment.FieldID))
						}
					case "created_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entComment.FieldCreatedAt))
						} else {
							q = q.Order(ent.Desc(entComment.FieldCreatedAt))
						}
					case "updated_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entComment.FieldUpdatedAt))
						} else {
							q = q.Order(ent.Desc(entComment.FieldUpdatedAt))
						}
					case "entity_table":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entComment.FieldEntityTable))
						} else {
							q = q.Order(ent.Desc(entComment.FieldEntityTable))
						}
					case "entity_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entComment.FieldEntityID))
						} else {
							q = q.Order(ent.Desc(entComment.FieldEntityID))
						}
					case "created_by_actor_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entComment.FieldCreatedByActorID))
						} else {
							q = q.Order(ent.Desc(entComment.FieldCreatedByActorID))
						}
					}
				}
			}
			total, err := q.Clone().Count(ctx)
			if err != nil {
				return nil, 0, err
			}
			rows, err := q.Offset(opts.Offset).Limit(opts.Limit).All(ctx)
			return rows, total, err
		},

		// Ent-native JSON for the `J` clipboard shortcut. *ent.Comment
		// implements MarshalJSON so eager-loaded edges (from With*())
		// land in the output under `edges` automatically.
		JSON: func(r *ent.Comment) ([]byte, error) { return json.Marshal(r) },

		Columns: []runtime.Column[*ent.Comment]{
			{
				Key:        "id",
				Label:      "Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Comment) string {
					return r.ID
				},
			},
			{
				Key:        "created_at",
				Label:      "Created At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Comment) string {
					if r.CreatedAt.IsZero() {
						return ""
					}
					return r.CreatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "updated_at",
				Label:      "Updated At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Comment) string {
					if r.UpdatedAt.IsZero() {
						return ""
					}
					return r.UpdatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "entity_table",
				Label:      "Entity Table",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Comment) string {
					return r.EntityTable
				},
			},
			{
				Key:        "entity_id",
				Label:      "Entity Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Comment) string {
					return r.EntityID
				},
			},
			{
				Key:        "body",
				Label:      "Body",
				Sortable:   false,
				Filterable: false,
				Hidden:     true,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Comment) string {
					return r.Body
				},
			},
			{
				Key:        "created_by_actor_id",
				Label:      "Created By Actor Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Comment) string {
					if r.CreatedByActorID == nil {
						return ""
					}
					return *r.CreatedByActorID
				},
			},
		},

		// Form support — see enttui.Editable() / AllowCreate() / AllowDelete().
		FormFields: []runtime.FormField{
			{
				Key: "entity_table", Label: "Entity Table", Kind: "string", Required: true,
			},
			{
				Key: "entity_id", Label: "Entity Id", Kind: "string", Required: true,
			},
			{
				Key: "body", Label: "Body", Kind: "string", Required: true,
			},
			{
				Key: "created_by_actor_id", Label: "Created By Actor Id", Kind: "stringPtr", Required: false,
			},
		},

		// Update wires the typed setters for each Editable field. The
		// runtime collects form input as strings; we cast / parse here.
		Update: func(ctx context.Context, id string, vals map[string]string) error {
			pid, err := parseCommentID(id)
			if err != nil {
				return err
			}
			u := client.Comment.UpdateOneID(pid)
			if v, ok := vals["entity_table"]; ok {
				u.SetEntityTable(v)
			}
			if v, ok := vals["entity_id"]; ok {
				u.SetEntityID(v)
			}
			if v, ok := vals["body"]; ok {
				u.SetBody(v)
			}
			if v, ok := vals["created_by_actor_id"]; ok {
				if v == "" {
					u.ClearCreatedByActorID()
				} else {
					u.SetCreatedByActorID(v)
				}
			}
			_, err = u.Save(ctx)
			return err
		},

		Create: func(ctx context.Context, vals map[string]string) (string, error) {
			c := client.Comment.Create()
			if v, ok := vals["entity_table"]; ok && v != "" {
				c.SetEntityTable(v)
			}
			if v, ok := vals["entity_id"]; ok && v != "" {
				c.SetEntityID(v)
			}
			if v, ok := vals["body"]; ok && v != "" {
				c.SetBody(v)
			}
			if v, ok := vals["created_by_actor_id"]; ok && v != "" {
				c.SetCreatedByActorID(v)
			}
			saved, err := c.Save(ctx)
			if err != nil {
				return "", err
			}
			return fmt.Sprint(saved.ID), nil
		},

		Delete: func(ctx context.Context, id string) error {
			pid, err := parseCommentID(id)
			if err != nil {
				return err
			}
			return client.Comment.DeleteOneID(pid).Exec(ctx)
		},
	})
}

// parseID converts the runtime's string row id into Comment's actual
// ID Go type (string). enttui is type-erased (Row.ID is always
// string); this is the inbound conversion for UpdateOneID / DeleteOneID.
func parseCommentID(s string) (string, error) {
	return s, nil
}
