// Code generated by enttui. DO NOT EDIT.

package tuigen

import (
	"context"
	"dbent/gen/ent"
	entReminder "dbent/gen/ent/reminder"
	"encoding/json"
	"strings"

	"github.com/khanakia/entx/enttui/runtime"
)

// registerReminder wires *ent.Reminder into the enttui runtime.
//
// Scope filtering: for every scope key configured in enttui.Config.ScopeFields
// that exists on this schema, the Fetch closure below reads opts.Scope[key]
// and applies a predicate when set. Caller drives this via app.SetScope(key, value).
func registerReminder(app *runtime.App, client *ent.Client) {
	runtime.Register(app, runtime.EntitySpec[*ent.Reminder]{
		Kind:           "reminder",
		Display:        "Reminders",
		Group:          "data",
		Icon:           "•",
		LabelKey:       "id",
		BodyKey:        "",
		IDKey:          "id",
		PageSize:       200,
		MultiSort:      true,
		ShowEdgeCounts: true,
		AllowBulkCopy:  false,
		AllowExport:    false,
		Default: runtime.DefaultView{
			SortField: "created_at",
			SortDir:   runtime.Desc,
			Mode:      "",
		},

		Fetch: func(ctx context.Context, opts runtime.ListOpts) ([]*ent.Reminder, int, error) {
			q := client.Reminder.Query()
			// Scope predicate — keyed generically via ListOpts.Scope so the
			// runtime stays decoupled from any specific field name.
			if v := opts.Scope["project_id"]; v != "" {
				q = q.Where(entReminder.ProjectID(v))
			}
			// Legacy substring filter — used by the list+preview browser's
			// global `/` prompt. Phase E (Filters slice) supersedes this
			// in the table view but both can coexist.
			if opts.Filter != "" {
				q = q.Where(entReminder.Or(
					entReminder.IDContainsFold(opts.Filter),
					entReminder.ProjectIDContainsFold(opts.Filter),
					entReminder.TargetTableContainsFold(opts.Filter),
					entReminder.TargetIDContainsFold(opts.Filter),
					entReminder.MessageContainsFold(opts.Filter),
					entReminder.CreatedByActorIDContainsFold(opts.Filter),
				))
			}
			// Phase E — structured per-column filters. AND-composed.
			// Unsupported operators for a given field type fall through
			// silently rather than erroring — keeps the UI forgiving.
			for _, f := range opts.Filters {
				switch f.Field {
				case "id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entReminder.IDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entReminder.IDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entReminder.IDContainsFold(f.Value))
					}
				case "project_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entReminder.ProjectIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entReminder.ProjectIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entReminder.ProjectIDContainsFold(f.Value))
					}
				case "target_table":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entReminder.TargetTableEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entReminder.TargetTableNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entReminder.TargetTableContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entReminder.TargetTableIsNil())
					case runtime.OpNotNull:
						q = q.Where(entReminder.TargetTableNotNil())
					}
				case "target_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entReminder.TargetIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entReminder.TargetIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entReminder.TargetIDContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entReminder.TargetIDIsNil())
					case runtime.OpNotNull:
						q = q.Where(entReminder.TargetIDNotNil())
					}
				case "message":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entReminder.MessageEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entReminder.MessageNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entReminder.MessageContainsFold(f.Value))
					}
				case "recurrence":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entReminder.RecurrenceEQ(entReminder.Recurrence(f.Value)))
					case runtime.OpNeq:
						q = q.Where(entReminder.RecurrenceNEQ(entReminder.Recurrence(f.Value)))
					case runtime.OpIn, runtime.OpNotIn:
						// Multi-select: condition value is a "|"-joined
						// list of enum strings. Empty entries are dropped.
						parts := strings.Split(f.Value, "|")
						vals := make([]entReminder.Recurrence, 0, len(parts))
						for _, p := range parts {
							if p == "" {
								continue
							}
							vals = append(vals, entReminder.Recurrence(p))
						}
						if len(vals) > 0 {
							if f.Op == runtime.OpIn {
								q = q.Where(entReminder.RecurrenceIn(vals...))
							} else {
								q = q.Where(entReminder.RecurrenceNotIn(vals...))
							}
						}
					case runtime.OpIsNull:
						q = q.Where(entReminder.RecurrenceIsNil())
					case runtime.OpNotNull:
						q = q.Where(entReminder.RecurrenceNotNil())
					}
				case "created_by_actor_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entReminder.CreatedByActorIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entReminder.CreatedByActorIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entReminder.CreatedByActorIDContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entReminder.CreatedByActorIDIsNil())
					case runtime.OpNotNull:
						q = q.Where(entReminder.CreatedByActorIDNotNil())
					}
				}
			}
			// Phase D — multi-column sort stack. Each Sort entry walks the
			// generated dispatch; unknown fields are silently skipped.
			if len(opts.Sort) > 0 {
				for _, k := range opts.Sort {
					switch k.Field {
					case "id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entReminder.FieldID))
						} else {
							q = q.Order(ent.Desc(entReminder.FieldID))
						}
					case "created_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entReminder.FieldCreatedAt))
						} else {
							q = q.Order(ent.Desc(entReminder.FieldCreatedAt))
						}
					case "updated_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entReminder.FieldUpdatedAt))
						} else {
							q = q.Order(ent.Desc(entReminder.FieldUpdatedAt))
						}
					case "project_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entReminder.FieldProjectID))
						} else {
							q = q.Order(ent.Desc(entReminder.FieldProjectID))
						}
					case "target_table":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entReminder.FieldTargetTable))
						} else {
							q = q.Order(ent.Desc(entReminder.FieldTargetTable))
						}
					case "target_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entReminder.FieldTargetID))
						} else {
							q = q.Order(ent.Desc(entReminder.FieldTargetID))
						}
					case "due_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entReminder.FieldDueAt))
						} else {
							q = q.Order(ent.Desc(entReminder.FieldDueAt))
						}
					case "message":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entReminder.FieldMessage))
						} else {
							q = q.Order(ent.Desc(entReminder.FieldMessage))
						}
					case "recurrence":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entReminder.FieldRecurrence))
						} else {
							q = q.Order(ent.Desc(entReminder.FieldRecurrence))
						}
					case "done_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entReminder.FieldDoneAt))
						} else {
							q = q.Order(ent.Desc(entReminder.FieldDoneAt))
						}
					case "created_by_actor_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entReminder.FieldCreatedByActorID))
						} else {
							q = q.Order(ent.Desc(entReminder.FieldCreatedByActorID))
						}
					}
				}
			}
			total, err := q.Clone().Count(ctx)
			if err != nil {
				return nil, 0, err
			}
			rows, err := q.Offset(opts.Offset).Limit(opts.Limit).All(ctx)
			return rows, total, err
		},

		// Ent-native JSON for the `J` clipboard shortcut. *ent.Reminder
		// implements MarshalJSON so eager-loaded edges (from With*())
		// land in the output under `edges` automatically.
		JSON: func(r *ent.Reminder) ([]byte, error) { return json.Marshal(r) },

		Columns: []runtime.Column[*ent.Reminder]{
			{
				Key:        "id",
				Label:      "Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Reminder) string {
					return r.ID
				},
			},
			{
				Key:        "created_at",
				Label:      "Created At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Reminder) string {
					if r.CreatedAt.IsZero() {
						return ""
					}
					return r.CreatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "updated_at",
				Label:      "Updated At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Reminder) string {
					if r.UpdatedAt.IsZero() {
						return ""
					}
					return r.UpdatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "project_id",
				Label:      "Project Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Reminder) string {
					return r.ProjectID
				},
			},
			{
				Key:        "target_table",
				Label:      "Target Table",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Reminder) string {
					if r.TargetTable == nil {
						return ""
					}
					return *r.TargetTable
				},
			},
			{
				Key:        "target_id",
				Label:      "Target Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Reminder) string {
					if r.TargetID == nil {
						return ""
					}
					return *r.TargetID
				},
			},
			{
				Key:        "due_at",
				Label:      "Due At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Reminder) string {
					if r.DueAt.IsZero() {
						return ""
					}
					return r.DueAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "message",
				Label:      "Message",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Reminder) string {
					return r.Message
				},
			},
			{
				Key:        "recurrence",
				Label:      "Recurrence",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				EnumValues: []string{
					"7d",
					"30d",
					"1m",
					"3m",
					"6m",
					"1y",
				},
				Get: func(r *ent.Reminder) string {
					if r.Recurrence == nil {
						return ""
					}
					return string(*r.Recurrence)
				},
			},
			{
				Key:        "done_at",
				Label:      "Done At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Reminder) string {
					if r.DoneAt == nil || r.DoneAt.IsZero() {
						return ""
					}
					return r.DoneAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "created_by_actor_id",
				Label:      "Created By Actor Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Reminder) string {
					if r.CreatedByActorID == nil {
						return ""
					}
					return *r.CreatedByActorID
				},
			},
		},
	})
}
