// Code generated by enttui. DO NOT EDIT.

package tuigen

import (
	"context"
	"dbent/gen/ent"
	entSnapshot "dbent/gen/ent/snapshot"
	"encoding/json"
	"fmt"

	"github.com/khanakia/entx/enttui/runtime"
)

// registerSnapshot wires *ent.Snapshot into the enttui runtime.
//
// Scope filtering: for every scope key configured in enttui.Config.ScopeFields
// that exists on this schema, the Fetch closure below reads opts.Scope[key]
// and applies a predicate when set. Caller drives this via app.SetScope(key, value).
func registerSnapshot(app *runtime.App, client *ent.Client) {
	runtime.Register(app, runtime.EntitySpec[*ent.Snapshot]{
		Kind:           "snapshot",
		Display:        "Snapshots",
		Group:          "data",
		Icon:           "•",
		LabelKey:       "title",
		BodyKey:        "body",
		IDKey:          "id",
		PageSize:       200,
		MultiSort:      true,
		ShowEdgeCounts: true,
		AllowBulkCopy:  false,
		AllowExport:    false,
		Default: runtime.DefaultView{
			SortField: "created_at",
			SortDir:   runtime.Desc,
			Mode:      "",
		},

		Fetch: func(ctx context.Context, opts runtime.ListOpts) ([]*ent.Snapshot, int, error) {
			q := client.Snapshot.Query()
			// Scope predicate — keyed generically via ListOpts.Scope so the
			// runtime stays decoupled from any specific field name.
			if v := opts.Scope["project_id"]; v != "" {
				q = q.Where(entSnapshot.ProjectID(v))
			}
			// Legacy substring filter — used by the list+preview browser's
			// global `/` prompt. Phase E (Filters slice) supersedes this
			// in the table view but both can coexist.
			if opts.Filter != "" {
				q = q.Where(entSnapshot.Or(
					entSnapshot.IDContainsFold(opts.Filter),
					entSnapshot.SourceKindContainsFold(opts.Filter),
					entSnapshot.SourceRefContainsFold(opts.Filter),
					entSnapshot.ProjectIDContainsFold(opts.Filter),
					entSnapshot.RepoIDContainsFold(opts.Filter),
					entSnapshot.TitleContainsFold(opts.Filter),
					entSnapshot.CreatedByActorIDContainsFold(opts.Filter),
				))
			}
			// Phase E — structured per-column filters. AND-composed.
			// Unsupported operators for a given field type fall through
			// silently rather than erroring — keeps the UI forgiving.
			for _, f := range opts.Filters {
				switch f.Field {
				case "id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entSnapshot.IDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entSnapshot.IDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entSnapshot.IDContainsFold(f.Value))
					}
				case "source_kind":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entSnapshot.SourceKindEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entSnapshot.SourceKindNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entSnapshot.SourceKindContainsFold(f.Value))
					}
				case "source_ref":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entSnapshot.SourceRefEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entSnapshot.SourceRefNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entSnapshot.SourceRefContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entSnapshot.SourceRefIsNil())
					case runtime.OpNotNull:
						q = q.Where(entSnapshot.SourceRefNotNil())
					}
				case "project_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entSnapshot.ProjectIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entSnapshot.ProjectIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entSnapshot.ProjectIDContainsFold(f.Value))
					}
				case "repo_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entSnapshot.RepoIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entSnapshot.RepoIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entSnapshot.RepoIDContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entSnapshot.RepoIDIsNil())
					case runtime.OpNotNull:
						q = q.Where(entSnapshot.RepoIDNotNil())
					}
				case "title":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entSnapshot.TitleEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entSnapshot.TitleNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entSnapshot.TitleContainsFold(f.Value))
					}
				case "created_by_actor_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entSnapshot.CreatedByActorIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entSnapshot.CreatedByActorIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entSnapshot.CreatedByActorIDContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entSnapshot.CreatedByActorIDIsNil())
					case runtime.OpNotNull:
						q = q.Where(entSnapshot.CreatedByActorIDNotNil())
					}
				}
			}
			// Phase D — multi-column sort stack. Each Sort entry walks the
			// generated dispatch; unknown fields are silently skipped.
			if len(opts.Sort) > 0 {
				for _, k := range opts.Sort {
					switch k.Field {
					case "id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entSnapshot.FieldID))
						} else {
							q = q.Order(ent.Desc(entSnapshot.FieldID))
						}
					case "created_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entSnapshot.FieldCreatedAt))
						} else {
							q = q.Order(ent.Desc(entSnapshot.FieldCreatedAt))
						}
					case "updated_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entSnapshot.FieldUpdatedAt))
						} else {
							q = q.Order(ent.Desc(entSnapshot.FieldUpdatedAt))
						}
					case "last_accessed_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entSnapshot.FieldLastAccessedAt))
						} else {
							q = q.Order(ent.Desc(entSnapshot.FieldLastAccessedAt))
						}
					case "last_validated_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entSnapshot.FieldLastValidatedAt))
						} else {
							q = q.Order(ent.Desc(entSnapshot.FieldLastValidatedAt))
						}
					case "archived_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entSnapshot.FieldArchivedAt))
						} else {
							q = q.Order(ent.Desc(entSnapshot.FieldArchivedAt))
						}
					case "source_kind":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entSnapshot.FieldSourceKind))
						} else {
							q = q.Order(ent.Desc(entSnapshot.FieldSourceKind))
						}
					case "source_ref":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entSnapshot.FieldSourceRef))
						} else {
							q = q.Order(ent.Desc(entSnapshot.FieldSourceRef))
						}
					case "project_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entSnapshot.FieldProjectID))
						} else {
							q = q.Order(ent.Desc(entSnapshot.FieldProjectID))
						}
					case "repo_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entSnapshot.FieldRepoID))
						} else {
							q = q.Order(ent.Desc(entSnapshot.FieldRepoID))
						}
					case "title":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entSnapshot.FieldTitle))
						} else {
							q = q.Order(ent.Desc(entSnapshot.FieldTitle))
						}
					case "taken_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entSnapshot.FieldTakenAt))
						} else {
							q = q.Order(ent.Desc(entSnapshot.FieldTakenAt))
						}
					case "created_by_actor_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entSnapshot.FieldCreatedByActorID))
						} else {
							q = q.Order(ent.Desc(entSnapshot.FieldCreatedByActorID))
						}
					}
				}
			}
			total, err := q.Clone().Count(ctx)
			if err != nil {
				return nil, 0, err
			}
			rows, err := q.Offset(opts.Offset).Limit(opts.Limit).All(ctx)
			return rows, total, err
		},

		// Ent-native JSON for the `J` clipboard shortcut. *ent.Snapshot
		// implements MarshalJSON so eager-loaded edges (from With*())
		// land in the output under `edges` automatically.
		JSON: func(r *ent.Snapshot) ([]byte, error) { return json.Marshal(r) },

		Columns: []runtime.Column[*ent.Snapshot]{
			{
				Key:        "id",
				Label:      "Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Snapshot) string {
					return r.ID
				},
			},
			{
				Key:        "created_at",
				Label:      "Created At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Snapshot) string {
					if r.CreatedAt.IsZero() {
						return ""
					}
					return r.CreatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "updated_at",
				Label:      "Updated At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Snapshot) string {
					if r.UpdatedAt.IsZero() {
						return ""
					}
					return r.UpdatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "trust_score",
				Label:      "Trust Score",
				Sortable:   false,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Snapshot) string {
					return fmt.Sprintf("%v", r.TrustScore)
				},
			},
			{
				Key:        "confidence",
				Label:      "Confidence",
				Sortable:   false,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Snapshot) string {
					if r.Confidence == nil {
						return ""
					}
					return fmt.Sprintf("%v", *r.Confidence)
				},
			},
			{
				Key:        "last_accessed_at",
				Label:      "Last Accessed At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Snapshot) string {
					if r.LastAccessedAt == nil || r.LastAccessedAt.IsZero() {
						return ""
					}
					return r.LastAccessedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "last_validated_at",
				Label:      "Last Validated At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Snapshot) string {
					if r.LastValidatedAt == nil || r.LastValidatedAt.IsZero() {
						return ""
					}
					return r.LastValidatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "archived_at",
				Label:      "Archived At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Snapshot) string {
					if r.ArchivedAt == nil || r.ArchivedAt.IsZero() {
						return ""
					}
					return r.ArchivedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "source_kind",
				Label:      "Source Kind",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Snapshot) string {
					return r.SourceKind
				},
			},
			{
				Key:        "source_ref",
				Label:      "Source Ref",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Snapshot) string {
					if r.SourceRef == nil {
						return ""
					}
					return *r.SourceRef
				},
			},
			{
				Key:        "project_id",
				Label:      "Project Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Snapshot) string {
					return r.ProjectID
				},
			},
			{
				Key:        "repo_id",
				Label:      "Repo Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Snapshot) string {
					if r.RepoID == nil {
						return ""
					}
					return *r.RepoID
				},
			},
			{
				Key:        "title",
				Label:      "Title",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Snapshot) string {
					return r.Title
				},
			},
			{
				Key:        "body",
				Label:      "Body",
				Sortable:   false,
				Filterable: false,
				Hidden:     true,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Snapshot) string {
					return r.Body
				},
			},
			{
				Key:        "taken_at",
				Label:      "Taken At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Snapshot) string {
					if r.TakenAt.IsZero() {
						return ""
					}
					return r.TakenAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "created_by_actor_id",
				Label:      "Created By Actor Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Snapshot) string {
					if r.CreatedByActorID == nil {
						return ""
					}
					return *r.CreatedByActorID
				},
			},
		},
	})
}
