// Code generated by enttui. DO NOT EDIT.

package tuigen

import (
	"context"
	"dbent/gen/ent"
	entCodeSymbol "dbent/gen/ent/codesymbol"
	"encoding/json"
	"fmt"

	"github.com/khanakia/entx/enttui/runtime"
)

// registerCodeSymbol wires *ent.CodeSymbol into the enttui runtime.
//
// Scope filtering: for every scope key configured in enttui.Config.ScopeFields
// that exists on this schema, the Fetch closure below reads opts.Scope[key]
// and applies a predicate when set. Caller drives this via app.SetScope(key, value).
func registerCodeSymbol(app *runtime.App, client *ent.Client) {
	runtime.Register(app, runtime.EntitySpec[*ent.CodeSymbol]{
		Kind:           "codesymbol",
		Display:        "CodeSymbols",
		Group:          "data",
		Icon:           "•",
		LabelKey:       "name",
		BodyKey:        "",
		IDKey:          "id",
		PageSize:       200,
		MultiSort:      true,
		ShowEdgeCounts: true,
		AllowBulkCopy:  false,
		AllowExport:    false,
		Default: runtime.DefaultView{
			SortField: "created_at",
			SortDir:   runtime.Desc,
			Mode:      "",
		},

		Fetch: func(ctx context.Context, opts runtime.ListOpts) ([]*ent.CodeSymbol, int, error) {
			q := client.CodeSymbol.Query()
			// Scope predicate — keyed generically via ListOpts.Scope so the
			// runtime stays decoupled from any specific field name.
			if v := opts.Scope["project_id"]; v != "" {
				q = q.Where(entCodeSymbol.ProjectID(v))
			}
			// Legacy substring filter — used by the list+preview browser's
			// global `/` prompt. Phase E (Filters slice) supersedes this
			// in the table view but both can coexist.
			if opts.Filter != "" {
				q = q.Where(entCodeSymbol.Or(
					entCodeSymbol.IDContainsFold(opts.Filter),
					entCodeSymbol.ProjectIDContainsFold(opts.Filter),
					entCodeSymbol.CodeFileIDContainsFold(opts.Filter),
					entCodeSymbol.NameContainsFold(opts.Filter),
					entCodeSymbol.KindContainsFold(opts.Filter),
					entCodeSymbol.SignatureContainsFold(opts.Filter),
				))
			}
			// Phase E — structured per-column filters. AND-composed.
			// Unsupported operators for a given field type fall through
			// silently rather than erroring — keeps the UI forgiving.
			for _, f := range opts.Filters {
				switch f.Field {
				case "id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entCodeSymbol.IDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entCodeSymbol.IDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entCodeSymbol.IDContainsFold(f.Value))
					}
				case "project_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entCodeSymbol.ProjectIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entCodeSymbol.ProjectIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entCodeSymbol.ProjectIDContainsFold(f.Value))
					}
				case "code_file_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entCodeSymbol.CodeFileIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entCodeSymbol.CodeFileIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entCodeSymbol.CodeFileIDContainsFold(f.Value))
					}
				case "name":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entCodeSymbol.NameEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entCodeSymbol.NameNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entCodeSymbol.NameContainsFold(f.Value))
					}
				case "kind":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entCodeSymbol.KindEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entCodeSymbol.KindNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entCodeSymbol.KindContainsFold(f.Value))
					}
				case "signature":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entCodeSymbol.SignatureEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entCodeSymbol.SignatureNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entCodeSymbol.SignatureContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entCodeSymbol.SignatureIsNil())
					case runtime.OpNotNull:
						q = q.Where(entCodeSymbol.SignatureNotNil())
					}
				}
			}
			// Phase D — multi-column sort stack. Each Sort entry walks the
			// generated dispatch; unknown fields are silently skipped.
			if len(opts.Sort) > 0 {
				for _, k := range opts.Sort {
					switch k.Field {
					case "id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entCodeSymbol.FieldID))
						} else {
							q = q.Order(ent.Desc(entCodeSymbol.FieldID))
						}
					case "created_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entCodeSymbol.FieldCreatedAt))
						} else {
							q = q.Order(ent.Desc(entCodeSymbol.FieldCreatedAt))
						}
					case "updated_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entCodeSymbol.FieldUpdatedAt))
						} else {
							q = q.Order(ent.Desc(entCodeSymbol.FieldUpdatedAt))
						}
					case "project_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entCodeSymbol.FieldProjectID))
						} else {
							q = q.Order(ent.Desc(entCodeSymbol.FieldProjectID))
						}
					case "code_file_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entCodeSymbol.FieldCodeFileID))
						} else {
							q = q.Order(ent.Desc(entCodeSymbol.FieldCodeFileID))
						}
					case "name":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entCodeSymbol.FieldName))
						} else {
							q = q.Order(ent.Desc(entCodeSymbol.FieldName))
						}
					case "kind":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entCodeSymbol.FieldKind))
						} else {
							q = q.Order(ent.Desc(entCodeSymbol.FieldKind))
						}
					case "signature":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entCodeSymbol.FieldSignature))
						} else {
							q = q.Order(ent.Desc(entCodeSymbol.FieldSignature))
						}
					}
				}
			}
			total, err := q.Clone().Count(ctx)
			if err != nil {
				return nil, 0, err
			}
			rows, err := q.Offset(opts.Offset).Limit(opts.Limit).All(ctx)
			return rows, total, err
		},

		// Ent-native JSON for the `J` clipboard shortcut. *ent.CodeSymbol
		// implements MarshalJSON so eager-loaded edges (from With*())
		// land in the output under `edges` automatically.
		JSON: func(r *ent.CodeSymbol) ([]byte, error) { return json.Marshal(r) },

		Columns: []runtime.Column[*ent.CodeSymbol]{
			{
				Key:        "id",
				Label:      "Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.CodeSymbol) string {
					return r.ID
				},
			},
			{
				Key:        "created_at",
				Label:      "Created At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.CodeSymbol) string {
					if r.CreatedAt.IsZero() {
						return ""
					}
					return r.CreatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "updated_at",
				Label:      "Updated At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.CodeSymbol) string {
					if r.UpdatedAt.IsZero() {
						return ""
					}
					return r.UpdatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "project_id",
				Label:      "Project Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.CodeSymbol) string {
					return r.ProjectID
				},
			},
			{
				Key:        "code_file_id",
				Label:      "Code File Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.CodeSymbol) string {
					return r.CodeFileID
				},
			},
			{
				Key:        "name",
				Label:      "Name",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.CodeSymbol) string {
					return r.Name
				},
			},
			{
				Key:        "kind",
				Label:      "Kind",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.CodeSymbol) string {
					return r.Kind
				},
			},
			{
				Key:        "line_start",
				Label:      "Line Start",
				Sortable:   false,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.CodeSymbol) string {
					if r.LineStart == nil {
						return ""
					}
					return fmt.Sprintf("%v", *r.LineStart)
				},
			},
			{
				Key:        "line_end",
				Label:      "Line End",
				Sortable:   false,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.CodeSymbol) string {
					if r.LineEnd == nil {
						return ""
					}
					return fmt.Sprintf("%v", *r.LineEnd)
				},
			},
			{
				Key:        "signature",
				Label:      "Signature",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.CodeSymbol) string {
					if r.Signature == nil {
						return ""
					}
					return *r.Signature
				},
			},
		},
	})
}
