// Code generated by enttui. DO NOT EDIT.

package tuigen

import (
	"context"
	"dbent/gen/ent"
	entKnowledgeRef "dbent/gen/ent/knowledgeref"
	"encoding/json"
	"strings"

	"github.com/khanakia/entx/enttui/runtime"
)

// registerKnowledgeRef wires *ent.KnowledgeRef into the enttui runtime.
//
// Scope filtering: for every scope key configured in enttui.Config.ScopeFields
// that exists on this schema, the Fetch closure below reads opts.Scope[key]
// and applies a predicate when set. Caller drives this via app.SetScope(key, value).
func registerKnowledgeRef(app *runtime.App, client *ent.Client) {
	runtime.Register(app, runtime.EntitySpec[*ent.KnowledgeRef]{
		Kind:           "knowledgeref",
		Display:        "KnowledgeRefs",
		Group:          "data",
		Icon:           "•",
		LabelKey:       "id",
		BodyKey:        "",
		IDKey:          "id",
		PageSize:       200,
		MultiSort:      true,
		ShowEdgeCounts: true,
		AllowBulkCopy:  false,
		AllowExport:    false,
		Default: runtime.DefaultView{
			SortField: "created_at",
			SortDir:   runtime.Desc,
			Mode:      "",
		},

		Fetch: func(ctx context.Context, opts runtime.ListOpts) ([]*ent.KnowledgeRef, int, error) {
			q := client.KnowledgeRef.Query()
			// Legacy substring filter — used by the list+preview browser's
			// global `/` prompt. Phase E (Filters slice) supersedes this
			// in the table view but both can coexist.
			if opts.Filter != "" {
				q = q.Where(entKnowledgeRef.Or(
					entKnowledgeRef.IDContainsFold(opts.Filter),
					entKnowledgeRef.SrcTableContainsFold(opts.Filter),
					entKnowledgeRef.SrcIDContainsFold(opts.Filter),
					entKnowledgeRef.DstTableContainsFold(opts.Filter),
					entKnowledgeRef.DstIDContainsFold(opts.Filter),
					entKnowledgeRef.RelationContainsFold(opts.Filter),
				))
			}
			// Phase E — structured per-column filters. AND-composed.
			// Unsupported operators for a given field type fall through
			// silently rather than erroring — keeps the UI forgiving.
			for _, f := range opts.Filters {
				switch f.Field {
				case "id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entKnowledgeRef.IDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entKnowledgeRef.IDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entKnowledgeRef.IDContainsFold(f.Value))
					}
				case "src_table":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entKnowledgeRef.SrcTableEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entKnowledgeRef.SrcTableNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entKnowledgeRef.SrcTableContainsFold(f.Value))
					}
				case "src_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entKnowledgeRef.SrcIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entKnowledgeRef.SrcIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entKnowledgeRef.SrcIDContainsFold(f.Value))
					}
				case "dst_table":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entKnowledgeRef.DstTableEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entKnowledgeRef.DstTableNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entKnowledgeRef.DstTableContainsFold(f.Value))
					}
				case "dst_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entKnowledgeRef.DstIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entKnowledgeRef.DstIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entKnowledgeRef.DstIDContainsFold(f.Value))
					}
				case "relation":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entKnowledgeRef.RelationEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entKnowledgeRef.RelationNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entKnowledgeRef.RelationContainsFold(f.Value))
					}
				case "confidence":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entKnowledgeRef.ConfidenceEQ(entKnowledgeRef.Confidence(f.Value)))
					case runtime.OpNeq:
						q = q.Where(entKnowledgeRef.ConfidenceNEQ(entKnowledgeRef.Confidence(f.Value)))
					case runtime.OpIn, runtime.OpNotIn:
						// Multi-select: condition value is a "|"-joined
						// list of enum strings. Empty entries are dropped.
						parts := strings.Split(f.Value, "|")
						vals := make([]entKnowledgeRef.Confidence, 0, len(parts))
						for _, p := range parts {
							if p == "" {
								continue
							}
							vals = append(vals, entKnowledgeRef.Confidence(p))
						}
						if len(vals) > 0 {
							if f.Op == runtime.OpIn {
								q = q.Where(entKnowledgeRef.ConfidenceIn(vals...))
							} else {
								q = q.Where(entKnowledgeRef.ConfidenceNotIn(vals...))
							}
						}
					}
				}
			}
			// Phase D — multi-column sort stack. Each Sort entry walks the
			// generated dispatch; unknown fields are silently skipped.
			if len(opts.Sort) > 0 {
				for _, k := range opts.Sort {
					switch k.Field {
					case "id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entKnowledgeRef.FieldID))
						} else {
							q = q.Order(ent.Desc(entKnowledgeRef.FieldID))
						}
					case "created_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entKnowledgeRef.FieldCreatedAt))
						} else {
							q = q.Order(ent.Desc(entKnowledgeRef.FieldCreatedAt))
						}
					case "updated_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entKnowledgeRef.FieldUpdatedAt))
						} else {
							q = q.Order(ent.Desc(entKnowledgeRef.FieldUpdatedAt))
						}
					case "src_table":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entKnowledgeRef.FieldSrcTable))
						} else {
							q = q.Order(ent.Desc(entKnowledgeRef.FieldSrcTable))
						}
					case "src_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entKnowledgeRef.FieldSrcID))
						} else {
							q = q.Order(ent.Desc(entKnowledgeRef.FieldSrcID))
						}
					case "dst_table":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entKnowledgeRef.FieldDstTable))
						} else {
							q = q.Order(ent.Desc(entKnowledgeRef.FieldDstTable))
						}
					case "dst_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entKnowledgeRef.FieldDstID))
						} else {
							q = q.Order(ent.Desc(entKnowledgeRef.FieldDstID))
						}
					case "relation":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entKnowledgeRef.FieldRelation))
						} else {
							q = q.Order(ent.Desc(entKnowledgeRef.FieldRelation))
						}
					case "confidence":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entKnowledgeRef.FieldConfidence))
						} else {
							q = q.Order(ent.Desc(entKnowledgeRef.FieldConfidence))
						}
					}
				}
			}
			total, err := q.Clone().Count(ctx)
			if err != nil {
				return nil, 0, err
			}
			rows, err := q.Offset(opts.Offset).Limit(opts.Limit).All(ctx)
			return rows, total, err
		},

		// Ent-native JSON for the `J` clipboard shortcut. *ent.KnowledgeRef
		// implements MarshalJSON so eager-loaded edges (from With*())
		// land in the output under `edges` automatically.
		JSON: func(r *ent.KnowledgeRef) ([]byte, error) { return json.Marshal(r) },

		Columns: []runtime.Column[*ent.KnowledgeRef]{
			{
				Key:        "id",
				Label:      "Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.KnowledgeRef) string {
					return r.ID
				},
			},
			{
				Key:        "created_at",
				Label:      "Created At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.KnowledgeRef) string {
					if r.CreatedAt.IsZero() {
						return ""
					}
					return r.CreatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "updated_at",
				Label:      "Updated At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.KnowledgeRef) string {
					if r.UpdatedAt.IsZero() {
						return ""
					}
					return r.UpdatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "src_table",
				Label:      "Src Table",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.KnowledgeRef) string {
					return r.SrcTable
				},
			},
			{
				Key:        "src_id",
				Label:      "Src Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.KnowledgeRef) string {
					return r.SrcID
				},
			},
			{
				Key:        "dst_table",
				Label:      "Dst Table",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.KnowledgeRef) string {
					return r.DstTable
				},
			},
			{
				Key:        "dst_id",
				Label:      "Dst Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.KnowledgeRef) string {
					return r.DstID
				},
			},
			{
				Key:        "relation",
				Label:      "Relation",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.KnowledgeRef) string {
					return r.Relation
				},
			},
			{
				Key:        "confidence",
				Label:      "Confidence",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				EnumValues: []string{
					"extracted",
					"inferred",
					"ambiguous",
				},
				Get: func(r *ent.KnowledgeRef) string {
					return string(r.Confidence)
				},
			},
		},
	})
}
