// Code generated by enttui. DO NOT EDIT.

package tuigen

import (
	"context"
	"dbent/gen/ent"
	entHotfix "dbent/gen/ent/hotfix"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/khanakia/entx/enttui/runtime"
)

// registerHotfix wires *ent.Hotfix into the enttui runtime.
//
// Scope filtering: for every scope key configured in enttui.Config.ScopeFields
// that exists on this schema, the Fetch closure below reads opts.Scope[key]
// and applies a predicate when set. Caller drives this via app.SetScope(key, value).
func registerHotfix(app *runtime.App, client *ent.Client) {
	runtime.Register(app, runtime.EntitySpec[*ent.Hotfix]{
		Kind:           "hotfix",
		Display:        "Hotfixs",
		Group:          "data",
		Icon:           "•",
		LabelKey:       "title",
		BodyKey:        "body",
		IDKey:          "id",
		PageSize:       200,
		MultiSort:      true,
		ShowEdgeCounts: true,
		AllowBulkCopy:  false,
		AllowExport:    false,
		Default: runtime.DefaultView{
			SortField: "created_at",
			SortDir:   runtime.Desc,
			Mode:      "",
		},

		Fetch: func(ctx context.Context, opts runtime.ListOpts) ([]*ent.Hotfix, int, error) {
			q := client.Hotfix.Query()
			// Scope predicate — keyed generically via ListOpts.Scope so the
			// runtime stays decoupled from any specific field name.
			if v := opts.Scope["project_id"]; v != "" {
				q = q.Where(entHotfix.ProjectID(v))
			}
			// Legacy substring filter — used by the list+preview browser's
			// global `/` prompt. Phase E (Filters slice) supersedes this
			// in the table view but both can coexist.
			if opts.Filter != "" {
				q = q.Where(entHotfix.Or(
					entHotfix.IDContainsFold(opts.Filter),
					entHotfix.SourceKindContainsFold(opts.Filter),
					entHotfix.SourceRefContainsFold(opts.Filter),
					entHotfix.ProjectIDContainsFold(opts.Filter),
					entHotfix.RepoIDContainsFold(opts.Filter),
					entHotfix.TitleContainsFold(opts.Filter),
					entHotfix.BodyContainsFold(opts.Filter),
					entHotfix.SupersededByIDContainsFold(opts.Filter),
					entHotfix.CreatedByActorIDContainsFold(opts.Filter),
				))
			}
			// Phase E — structured per-column filters. AND-composed.
			// Unsupported operators for a given field type fall through
			// silently rather than erroring — keeps the UI forgiving.
			for _, f := range opts.Filters {
				switch f.Field {
				case "id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entHotfix.IDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entHotfix.IDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entHotfix.IDContainsFold(f.Value))
					}
				case "source_kind":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entHotfix.SourceKindEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entHotfix.SourceKindNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entHotfix.SourceKindContainsFold(f.Value))
					}
				case "source_ref":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entHotfix.SourceRefEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entHotfix.SourceRefNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entHotfix.SourceRefContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entHotfix.SourceRefIsNil())
					case runtime.OpNotNull:
						q = q.Where(entHotfix.SourceRefNotNil())
					}
				case "project_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entHotfix.ProjectIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entHotfix.ProjectIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entHotfix.ProjectIDContainsFold(f.Value))
					}
				case "repo_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entHotfix.RepoIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entHotfix.RepoIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entHotfix.RepoIDContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entHotfix.RepoIDIsNil())
					case runtime.OpNotNull:
						q = q.Where(entHotfix.RepoIDNotNil())
					}
				case "title":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entHotfix.TitleEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entHotfix.TitleNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entHotfix.TitleContainsFold(f.Value))
					}
				case "body":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entHotfix.BodyEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entHotfix.BodyNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entHotfix.BodyContainsFold(f.Value))
					}
				case "severity":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entHotfix.SeverityEQ(entHotfix.Severity(f.Value)))
					case runtime.OpNeq:
						q = q.Where(entHotfix.SeverityNEQ(entHotfix.Severity(f.Value)))
					case runtime.OpIn, runtime.OpNotIn:
						// Multi-select: condition value is a "|"-joined
						// list of enum strings. Empty entries are dropped.
						parts := strings.Split(f.Value, "|")
						vals := make([]entHotfix.Severity, 0, len(parts))
						for _, p := range parts {
							if p == "" {
								continue
							}
							vals = append(vals, entHotfix.Severity(p))
						}
						if len(vals) > 0 {
							if f.Op == runtime.OpIn {
								q = q.Where(entHotfix.SeverityIn(vals...))
							} else {
								q = q.Where(entHotfix.SeverityNotIn(vals...))
							}
						}
					}
				case "superseded_by_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entHotfix.SupersededByIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entHotfix.SupersededByIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entHotfix.SupersededByIDContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entHotfix.SupersededByIDIsNil())
					case runtime.OpNotNull:
						q = q.Where(entHotfix.SupersededByIDNotNil())
					}
				case "created_by_actor_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entHotfix.CreatedByActorIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entHotfix.CreatedByActorIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entHotfix.CreatedByActorIDContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entHotfix.CreatedByActorIDIsNil())
					case runtime.OpNotNull:
						q = q.Where(entHotfix.CreatedByActorIDNotNil())
					}
				}
			}
			// Phase D — multi-column sort stack. Each Sort entry walks the
			// generated dispatch; unknown fields are silently skipped.
			if len(opts.Sort) > 0 {
				for _, k := range opts.Sort {
					switch k.Field {
					case "id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entHotfix.FieldID))
						} else {
							q = q.Order(ent.Desc(entHotfix.FieldID))
						}
					case "created_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entHotfix.FieldCreatedAt))
						} else {
							q = q.Order(ent.Desc(entHotfix.FieldCreatedAt))
						}
					case "updated_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entHotfix.FieldUpdatedAt))
						} else {
							q = q.Order(ent.Desc(entHotfix.FieldUpdatedAt))
						}
					case "last_accessed_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entHotfix.FieldLastAccessedAt))
						} else {
							q = q.Order(ent.Desc(entHotfix.FieldLastAccessedAt))
						}
					case "last_validated_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entHotfix.FieldLastValidatedAt))
						} else {
							q = q.Order(ent.Desc(entHotfix.FieldLastValidatedAt))
						}
					case "archived_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entHotfix.FieldArchivedAt))
						} else {
							q = q.Order(ent.Desc(entHotfix.FieldArchivedAt))
						}
					case "source_kind":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entHotfix.FieldSourceKind))
						} else {
							q = q.Order(ent.Desc(entHotfix.FieldSourceKind))
						}
					case "source_ref":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entHotfix.FieldSourceRef))
						} else {
							q = q.Order(ent.Desc(entHotfix.FieldSourceRef))
						}
					case "project_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entHotfix.FieldProjectID))
						} else {
							q = q.Order(ent.Desc(entHotfix.FieldProjectID))
						}
					case "repo_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entHotfix.FieldRepoID))
						} else {
							q = q.Order(ent.Desc(entHotfix.FieldRepoID))
						}
					case "title":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entHotfix.FieldTitle))
						} else {
							q = q.Order(ent.Desc(entHotfix.FieldTitle))
						}
					case "severity":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entHotfix.FieldSeverity))
						} else {
							q = q.Order(ent.Desc(entHotfix.FieldSeverity))
						}
					case "superseded_by_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entHotfix.FieldSupersededByID))
						} else {
							q = q.Order(ent.Desc(entHotfix.FieldSupersededByID))
						}
					case "created_by_actor_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entHotfix.FieldCreatedByActorID))
						} else {
							q = q.Order(ent.Desc(entHotfix.FieldCreatedByActorID))
						}
					}
				}
			}
			total, err := q.Clone().Count(ctx)
			if err != nil {
				return nil, 0, err
			}
			rows, err := q.Offset(opts.Offset).Limit(opts.Limit).All(ctx)
			return rows, total, err
		},

		// Ent-native JSON for the `J` clipboard shortcut. *ent.Hotfix
		// implements MarshalJSON so eager-loaded edges (from With*())
		// land in the output under `edges` automatically.
		JSON: func(r *ent.Hotfix) ([]byte, error) { return json.Marshal(r) },

		Columns: []runtime.Column[*ent.Hotfix]{
			{
				Key:        "id",
				Label:      "Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Hotfix) string {
					return r.ID
				},
			},
			{
				Key:        "created_at",
				Label:      "Created At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Hotfix) string {
					if r.CreatedAt.IsZero() {
						return ""
					}
					return r.CreatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "updated_at",
				Label:      "Updated At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Hotfix) string {
					if r.UpdatedAt.IsZero() {
						return ""
					}
					return r.UpdatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "trust_score",
				Label:      "Trust Score",
				Sortable:   false,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Hotfix) string {
					return fmt.Sprintf("%v", r.TrustScore)
				},
			},
			{
				Key:        "confidence",
				Label:      "Confidence",
				Sortable:   false,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Hotfix) string {
					if r.Confidence == nil {
						return ""
					}
					return fmt.Sprintf("%v", *r.Confidence)
				},
			},
			{
				Key:        "last_accessed_at",
				Label:      "Last Accessed At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Hotfix) string {
					if r.LastAccessedAt == nil || r.LastAccessedAt.IsZero() {
						return ""
					}
					return r.LastAccessedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "last_validated_at",
				Label:      "Last Validated At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Hotfix) string {
					if r.LastValidatedAt == nil || r.LastValidatedAt.IsZero() {
						return ""
					}
					return r.LastValidatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "archived_at",
				Label:      "Archived At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Hotfix) string {
					if r.ArchivedAt == nil || r.ArchivedAt.IsZero() {
						return ""
					}
					return r.ArchivedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "source_kind",
				Label:      "Source Kind",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Hotfix) string {
					return r.SourceKind
				},
			},
			{
				Key:        "source_ref",
				Label:      "Source Ref",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Hotfix) string {
					if r.SourceRef == nil {
						return ""
					}
					return *r.SourceRef
				},
			},
			{
				Key:        "project_id",
				Label:      "Project Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Hotfix) string {
					return r.ProjectID
				},
			},
			{
				Key:        "repo_id",
				Label:      "Repo Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Hotfix) string {
					if r.RepoID == nil {
						return ""
					}
					return *r.RepoID
				},
			},
			{
				Key:        "title",
				Label:      "Title",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Hotfix) string {
					return r.Title
				},
			},
			{
				Key:        "body",
				Label:      "Body",
				Sortable:   false,
				Filterable: true,
				Hidden:     true,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Hotfix) string {
					return r.Body
				},
			},
			{
				Key:        "severity",
				Label:      "Severity",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				EnumValues: []string{
					"low",
					"medium",
					"high",
					"critical",
				},
				Get: func(r *ent.Hotfix) string {
					return string(r.Severity)
				},
			},
			{
				Key:        "superseded_by_id",
				Label:      "Superseded By Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Hotfix) string {
					if r.SupersededByID == nil {
						return ""
					}
					return *r.SupersededByID
				},
			},
			{
				Key:        "created_by_actor_id",
				Label:      "Created By Actor Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Hotfix) string {
					if r.CreatedByActorID == nil {
						return ""
					}
					return *r.CreatedByActorID
				},
			},
		},
	})
}
