// Code generated by enttui. DO NOT EDIT.

package tuigen

import (
	"context"
	"dbent/gen/ent"
	entTaskView "dbent/gen/ent/taskview"
	"encoding/json"

	"github.com/khanakia/entx/enttui/runtime"
)

// registerTaskView wires *ent.TaskView into the enttui runtime.
//
// Scope filtering: for every scope key configured in enttui.Config.ScopeFields
// that exists on this schema, the Fetch closure below reads opts.Scope[key]
// and applies a predicate when set. Caller drives this via app.SetScope(key, value).
func registerTaskView(app *runtime.App, client *ent.Client) {
	runtime.Register(app, runtime.EntitySpec[*ent.TaskView]{
		Kind:           "taskview",
		Display:        "TaskViews",
		Group:          "data",
		Icon:           "•",
		LabelKey:       "name",
		BodyKey:        "",
		IDKey:          "id",
		PageSize:       200,
		MultiSort:      true,
		ShowEdgeCounts: true,
		AllowBulkCopy:  false,
		AllowExport:    false,
		Default: runtime.DefaultView{
			SortField: "created_at",
			SortDir:   runtime.Desc,
			Mode:      "",
		},

		Fetch: func(ctx context.Context, opts runtime.ListOpts) ([]*ent.TaskView, int, error) {
			q := client.TaskView.Query()
			// Scope predicate — keyed generically via ListOpts.Scope so the
			// runtime stays decoupled from any specific field name.
			if v := opts.Scope["project_id"]; v != "" {
				q = q.Where(entTaskView.ProjectID(v))
			}
			// Legacy substring filter — used by the list+preview browser's
			// global `/` prompt. Phase E (Filters slice) supersedes this
			// in the table view but both can coexist.
			if opts.Filter != "" {
				q = q.Where(entTaskView.Or(
					entTaskView.IDContainsFold(opts.Filter),
					entTaskView.ProjectIDContainsFold(opts.Filter),
					entTaskView.NameContainsFold(opts.Filter),
					entTaskView.FilterJSONContainsFold(opts.Filter),
				))
			}
			// Phase E — structured per-column filters. AND-composed.
			// Unsupported operators for a given field type fall through
			// silently rather than erroring — keeps the UI forgiving.
			for _, f := range opts.Filters {
				switch f.Field {
				case "id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entTaskView.IDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entTaskView.IDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entTaskView.IDContainsFold(f.Value))
					}
				case "project_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entTaskView.ProjectIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entTaskView.ProjectIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entTaskView.ProjectIDContainsFold(f.Value))
					}
				case "name":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entTaskView.NameEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entTaskView.NameNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entTaskView.NameContainsFold(f.Value))
					}
				case "filter_json":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entTaskView.FilterJSONEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entTaskView.FilterJSONNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entTaskView.FilterJSONContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entTaskView.FilterJSONIsNil())
					case runtime.OpNotNull:
						q = q.Where(entTaskView.FilterJSONNotNil())
					}
				}
			}
			// Phase D — multi-column sort stack. Each Sort entry walks the
			// generated dispatch; unknown fields are silently skipped.
			if len(opts.Sort) > 0 {
				for _, k := range opts.Sort {
					switch k.Field {
					case "id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entTaskView.FieldID))
						} else {
							q = q.Order(ent.Desc(entTaskView.FieldID))
						}
					case "created_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entTaskView.FieldCreatedAt))
						} else {
							q = q.Order(ent.Desc(entTaskView.FieldCreatedAt))
						}
					case "updated_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entTaskView.FieldUpdatedAt))
						} else {
							q = q.Order(ent.Desc(entTaskView.FieldUpdatedAt))
						}
					case "project_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entTaskView.FieldProjectID))
						} else {
							q = q.Order(ent.Desc(entTaskView.FieldProjectID))
						}
					case "name":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entTaskView.FieldName))
						} else {
							q = q.Order(ent.Desc(entTaskView.FieldName))
						}
					case "filter_json":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entTaskView.FieldFilterJSON))
						} else {
							q = q.Order(ent.Desc(entTaskView.FieldFilterJSON))
						}
					}
				}
			}
			total, err := q.Clone().Count(ctx)
			if err != nil {
				return nil, 0, err
			}
			rows, err := q.Offset(opts.Offset).Limit(opts.Limit).All(ctx)
			return rows, total, err
		},

		// Ent-native JSON for the `J` clipboard shortcut. *ent.TaskView
		// implements MarshalJSON so eager-loaded edges (from With*())
		// land in the output under `edges` automatically.
		JSON: func(r *ent.TaskView) ([]byte, error) { return json.Marshal(r) },

		Columns: []runtime.Column[*ent.TaskView]{
			{
				Key:        "id",
				Label:      "Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.TaskView) string {
					return r.ID
				},
			},
			{
				Key:        "created_at",
				Label:      "Created At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.TaskView) string {
					if r.CreatedAt.IsZero() {
						return ""
					}
					return r.CreatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "updated_at",
				Label:      "Updated At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.TaskView) string {
					if r.UpdatedAt.IsZero() {
						return ""
					}
					return r.UpdatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "project_id",
				Label:      "Project Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.TaskView) string {
					return r.ProjectID
				},
			},
			{
				Key:        "name",
				Label:      "Name",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.TaskView) string {
					return r.Name
				},
			},
			{
				Key:        "filter_json",
				Label:      "Filter Json",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.TaskView) string {
					if r.FilterJSON == nil {
						return ""
					}
					return *r.FilterJSON
				},
			},
		},
	})
}
