// Code generated by enttui. DO NOT EDIT.

package tuigen

import (
	"context"
	"dbent/gen/ent"
	entProject "dbent/gen/ent/project"
	"encoding/json"
	"fmt"

	"github.com/khanakia/entx/enttui/runtime"
)

// registerProject wires *ent.Project into the enttui runtime.
//
// Scope filtering: for every scope key configured in enttui.Config.ScopeFields
// that exists on this schema, the Fetch closure below reads opts.Scope[key]
// and applies a predicate when set. Caller drives this via app.SetScope(key, value).
func registerProject(app *runtime.App, client *ent.Client) {
	runtime.Register(app, runtime.EntitySpec[*ent.Project]{
		Kind:           "project",
		Display:        "Projects",
		Group:          "data",
		Icon:           "•",
		LabelKey:       "name",
		BodyKey:        "",
		IDKey:          "id",
		PageSize:       200,
		MultiSort:      true,
		ShowEdgeCounts: true,
		AllowBulkCopy:  false,
		AllowExport:    false,
		DetailEdges:    []string{"repos", "memories"},
		Default: runtime.DefaultView{
			SortField: "created_at",
			SortDir:   runtime.Desc,
			Mode:      "",
		},

		Fetch: func(ctx context.Context, opts runtime.ListOpts) ([]*ent.Project, int, error) {
			q := client.Project.Query()
			// Legacy substring filter — used by the list+preview browser's
			// global `/` prompt. Phase E (Filters slice) supersedes this
			// in the table view but both can coexist.
			if opts.Filter != "" {
				q = q.Where(entProject.Or(
					entProject.IDContainsFold(opts.Filter),
					entProject.NameContainsFold(opts.Filter),
					entProject.OriginURLContainsFold(opts.Filter),
				))
			}
			// Phase E — structured per-column filters. AND-composed.
			// Unsupported operators for a given field type fall through
			// silently rather than erroring — keeps the UI forgiving.
			for _, f := range opts.Filters {
				switch f.Field {
				case "id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entProject.IDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entProject.IDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entProject.IDContainsFold(f.Value))
					}
				case "name":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entProject.NameEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entProject.NameNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entProject.NameContainsFold(f.Value))
					}
				case "origin_url":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entProject.OriginURLEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entProject.OriginURLNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entProject.OriginURLContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entProject.OriginURLIsNil())
					case runtime.OpNotNull:
						q = q.Where(entProject.OriginURLNotNil())
					}
				}
			}
			// Phase D — multi-column sort stack. Each Sort entry walks the
			// generated dispatch; unknown fields are silently skipped.
			if len(opts.Sort) > 0 {
				for _, k := range opts.Sort {
					switch k.Field {
					case "id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entProject.FieldID))
						} else {
							q = q.Order(ent.Desc(entProject.FieldID))
						}
					case "created_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entProject.FieldCreatedAt))
						} else {
							q = q.Order(ent.Desc(entProject.FieldCreatedAt))
						}
					case "updated_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entProject.FieldUpdatedAt))
						} else {
							q = q.Order(ent.Desc(entProject.FieldUpdatedAt))
						}
					case "name":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entProject.FieldName))
						} else {
							q = q.Order(ent.Desc(entProject.FieldName))
						}
					case "origin_url":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entProject.FieldOriginURL))
						} else {
							q = q.Order(ent.Desc(entProject.FieldOriginURL))
						}
					case "archived_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entProject.FieldArchivedAt))
						} else {
							q = q.Order(ent.Desc(entProject.FieldArchivedAt))
						}
					case "last_active_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entProject.FieldLastActiveAt))
						} else {
							q = q.Order(ent.Desc(entProject.FieldLastActiveAt))
						}
					}
				}
			}
			total, err := q.Clone().Count(ctx)
			if err != nil {
				return nil, 0, err
			}
			rows, err := q.Offset(opts.Offset).Limit(opts.Limit).All(ctx)
			return rows, total, err
		},

		// Ent-native JSON for the `J` clipboard shortcut. *ent.Project
		// implements MarshalJSON so eager-loaded edges (from With*())
		// land in the output under `edges` automatically.
		JSON: func(r *ent.Project) ([]byte, error) { return json.Marshal(r) },

		Columns: []runtime.Column[*ent.Project]{
			{
				Key:        "id",
				Label:      "Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Project) string {
					return r.ID
				},
			},
			{
				Key:        "created_at",
				Label:      "Created At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Project) string {
					if r.CreatedAt.IsZero() {
						return ""
					}
					return r.CreatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "updated_at",
				Label:      "Updated At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Project) string {
					if r.UpdatedAt.IsZero() {
						return ""
					}
					return r.UpdatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "name",
				Label:      "Name",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Project) string {
					return r.Name
				},
			},
			{
				Key:        "origin_url",
				Label:      "Origin Url",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Project) string {
					if r.OriginURL == nil {
						return ""
					}
					return *r.OriginURL
				},
			},
			{
				Key:        "archived_at",
				Label:      "Archived At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Project) string {
					if r.ArchivedAt == nil || r.ArchivedAt.IsZero() {
						return ""
					}
					return r.ArchivedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "last_active_at",
				Label:      "Last Active At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Project) string {
					if r.LastActiveAt.IsZero() {
						return ""
					}
					return r.LastActiveAt.Format("2006-01-02 15:04:05")
				},
			},
		},

		Edges: []runtime.EdgeSpec[*ent.Project]{
			{
				Name: "repos", Display: "Repos", Kind: runtime.EdgeDrill, Trigger: "e",
				// Count is emitted for BOTH upward and drill edges. For
				// upward edges it returns 0 or 1 (parent exists / doesn't).
				// For drill edges, the child row count.
				Count: func(ctx context.Context, r *ent.Project) (int, error) {
					return client.Project.QueryRepos(r).Count(ctx)
				},
				ResolveDrill: func(ctx context.Context, r *ent.Project) (runtime.EntityRefList, error) {
					ids, err := client.Project.QueryRepos(r).IDs(ctx)
					if err != nil {
						return runtime.EntityRefList{}, err
					}
					sids := make([]string, len(ids))
					for i, v := range ids {
						sids[i] = fmt.Sprint(v)
					}
					return runtime.EntityRefList{Kind: "repo", IDs: sids}, nil
				},
			},
			{
				Name: "memories", Display: "Memories", Kind: runtime.EdgeDrill, Trigger: "m",
				// Count is emitted for BOTH upward and drill edges. For
				// upward edges it returns 0 or 1 (parent exists / doesn't).
				// For drill edges, the child row count.
				Count: func(ctx context.Context, r *ent.Project) (int, error) {
					return client.Project.QueryMemories(r).Count(ctx)
				},
				ResolveDrill: func(ctx context.Context, r *ent.Project) (runtime.EntityRefList, error) {
					ids, err := client.Project.QueryMemories(r).IDs(ctx)
					if err != nil {
						return runtime.EntityRefList{}, err
					}
					sids := make([]string, len(ids))
					for i, v := range ids {
						sids[i] = fmt.Sprint(v)
					}
					return runtime.EntityRefList{Kind: "memory", IDs: sids}, nil
				},
			},
		},
	})
}
