// Code generated by enttui. DO NOT EDIT.

package tuigen

import (
	"dbent/gen/ent"

	"github.com/khanakia/entx/enttui/runtime"
)

// RegisterAll wires every browsable entity into the enttui runtime.
//
// Scope filtering — e.g. by project_id, tenant_id — is decoupled from
// registration. Set it on the App BEFORE Run via:
//
//	app.SetScope("project_id", projectID)
//
// Each generated register function knows which scope keys its entity
// understands and applies them as predicates inside its Fetch closure.
func RegisterAll(app *runtime.App, client *ent.Client) {
	registerActivityArchive(app, client)
	registerActor(app, client)
	registerArchitectureNote(app, client)
	registerAssembleCitation(app, client)
	registerAssembleRun(app, client)
	registerBehaviour(app, client)
	registerBenchEval(app, client)
	registerBenchResult(app, client)
	registerBenchRun(app, client)
	registerCodeFile(app, client)
	registerCodeSymbol(app, client)
	registerComment(app, client)
	registerCommitLink(app, client)
	registerCompressRun(app, client)
	registerCookbookRecipe(app, client)
	registerDBConfig(app, client)
	registerDecision(app, client)
	registerDraft(app, client)
	registerEntityTag(app, client)
	registerExternalSource(app, client)
	registerHandoff(app, client)
	registerHotfix(app, client)
	registerIdentityProfile(app, client)
	registerIncident(app, client)
	registerInterventionMetric(app, client)
	registerKnowledgeRef(app, client)
	registerKnowledgeRevision(app, client)
	registerLearnCandidate(app, client)
	registerLearnRun(app, client)
	registerMemory(app, client)
	registerMemoryCodeRef(app, client)
	registerMission(app, client)
	registerMountAlias(app, client)
	registerPattern(app, client)
	registerPlan(app, client)
	registerPlaybook(app, client)
	registerProject(app, client)
	registerProjectConfig(app, client)
	registerPrompt(app, client)
	registerReminder(app, client)
	registerRenderHistory(app, client)
	registerRepo(app, client)
	registerRule(app, client)
	registerRuleVerifierRef(app, client)
	registerRun(app, client)
	registerRunStep(app, client)
	registerSession(app, client)
	registerSnapshot(app, client)
	registerSuggestion(app, client)
	registerTag(app, client)
	registerTask(app, client)
	registerTaskList(app, client)
	registerTaskView(app, client)
	registerTastePref(app, client)
	registerTechDoc(app, client)
	registerTechDocPage(app, client)
	registerTrustedPlugin(app, client)
	registerUser(app, client)
	registerWorkflow(app, client)
	registerWorkspace(app, client)
}
