// Code generated by enttui. DO NOT EDIT.

package tuigen

import (
	"context"
	"dbent/gen/ent"
	entRule "dbent/gen/ent/rule"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/khanakia/entx/enttui/runtime"
)

// registerRule wires *ent.Rule into the enttui runtime.
//
// Scope filtering: for every scope key configured in enttui.Config.ScopeFields
// that exists on this schema, the Fetch closure below reads opts.Scope[key]
// and applies a predicate when set. Caller drives this via app.SetScope(key, value).
func registerRule(app *runtime.App, client *ent.Client) {
	runtime.Register(app, runtime.EntitySpec[*ent.Rule]{
		Kind:           "rule",
		Display:        "Rules",
		Group:          "data",
		Icon:           "•",
		LabelKey:       "id",
		BodyKey:        "body",
		IDKey:          "id",
		PageSize:       200,
		MultiSort:      true,
		ShowEdgeCounts: true,
		AllowBulkCopy:  false,
		AllowExport:    false,
		Default: runtime.DefaultView{
			SortField: "created_at",
			SortDir:   runtime.Desc,
			Mode:      "",
		},

		Fetch: func(ctx context.Context, opts runtime.ListOpts) ([]*ent.Rule, int, error) {
			q := client.Rule.Query()
			// Scope predicate — keyed generically via ListOpts.Scope so the
			// runtime stays decoupled from any specific field name.
			if v := opts.Scope["project_id"]; v != "" {
				q = q.Where(entRule.ProjectID(v))
			}
			// Legacy substring filter — used by the list+preview browser's
			// global `/` prompt. Phase E (Filters slice) supersedes this
			// in the table view but both can coexist.
			if opts.Filter != "" {
				q = q.Where(entRule.Or(
					entRule.IDContainsFold(opts.Filter),
					entRule.SourceKindContainsFold(opts.Filter),
					entRule.SourceRefContainsFold(opts.Filter),
					entRule.ProjectIDContainsFold(opts.Filter),
					entRule.RepoIDContainsFold(opts.Filter),
					entRule.GlobsContainsFold(opts.Filter),
					entRule.AppliesToDescriptionContainsFold(opts.Filter),
					entRule.SupersededByIDContainsFold(opts.Filter),
					entRule.CreatedByActorIDContainsFold(opts.Filter),
				))
			}
			// Phase E — structured per-column filters. AND-composed.
			// Unsupported operators for a given field type fall through
			// silently rather than erroring — keeps the UI forgiving.
			for _, f := range opts.Filters {
				switch f.Field {
				case "id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entRule.IDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entRule.IDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entRule.IDContainsFold(f.Value))
					}
				case "source_kind":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entRule.SourceKindEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entRule.SourceKindNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entRule.SourceKindContainsFold(f.Value))
					}
				case "source_ref":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entRule.SourceRefEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entRule.SourceRefNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entRule.SourceRefContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entRule.SourceRefIsNil())
					case runtime.OpNotNull:
						q = q.Where(entRule.SourceRefNotNil())
					}
				case "project_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entRule.ProjectIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entRule.ProjectIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entRule.ProjectIDContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entRule.ProjectIDIsNil())
					case runtime.OpNotNull:
						q = q.Where(entRule.ProjectIDNotNil())
					}
				case "repo_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entRule.RepoIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entRule.RepoIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entRule.RepoIDContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entRule.RepoIDIsNil())
					case runtime.OpNotNull:
						q = q.Where(entRule.RepoIDNotNil())
					}
				case "activation":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entRule.ActivationEQ(entRule.Activation(f.Value)))
					case runtime.OpNeq:
						q = q.Where(entRule.ActivationNEQ(entRule.Activation(f.Value)))
					case runtime.OpIn, runtime.OpNotIn:
						// Multi-select: condition value is a "|"-joined
						// list of enum strings. Empty entries are dropped.
						parts := strings.Split(f.Value, "|")
						vals := make([]entRule.Activation, 0, len(parts))
						for _, p := range parts {
							if p == "" {
								continue
							}
							vals = append(vals, entRule.Activation(p))
						}
						if len(vals) > 0 {
							if f.Op == runtime.OpIn {
								q = q.Where(entRule.ActivationIn(vals...))
							} else {
								q = q.Where(entRule.ActivationNotIn(vals...))
							}
						}
					}
				case "globs":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entRule.GlobsEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entRule.GlobsNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entRule.GlobsContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entRule.GlobsIsNil())
					case runtime.OpNotNull:
						q = q.Where(entRule.GlobsNotNil())
					}
				case "applies_to_description":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entRule.AppliesToDescriptionEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entRule.AppliesToDescriptionNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entRule.AppliesToDescriptionContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entRule.AppliesToDescriptionIsNil())
					case runtime.OpNotNull:
						q = q.Where(entRule.AppliesToDescriptionNotNil())
					}
				case "severity":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entRule.SeverityEQ(entRule.Severity(f.Value)))
					case runtime.OpNeq:
						q = q.Where(entRule.SeverityNEQ(entRule.Severity(f.Value)))
					case runtime.OpIn, runtime.OpNotIn:
						// Multi-select: condition value is a "|"-joined
						// list of enum strings. Empty entries are dropped.
						parts := strings.Split(f.Value, "|")
						vals := make([]entRule.Severity, 0, len(parts))
						for _, p := range parts {
							if p == "" {
								continue
							}
							vals = append(vals, entRule.Severity(p))
						}
						if len(vals) > 0 {
							if f.Op == runtime.OpIn {
								q = q.Where(entRule.SeverityIn(vals...))
							} else {
								q = q.Where(entRule.SeverityNotIn(vals...))
							}
						}
					}
				case "superseded_by_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entRule.SupersededByIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entRule.SupersededByIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entRule.SupersededByIDContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entRule.SupersededByIDIsNil())
					case runtime.OpNotNull:
						q = q.Where(entRule.SupersededByIDNotNil())
					}
				case "created_by_actor_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entRule.CreatedByActorIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entRule.CreatedByActorIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entRule.CreatedByActorIDContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entRule.CreatedByActorIDIsNil())
					case runtime.OpNotNull:
						q = q.Where(entRule.CreatedByActorIDNotNil())
					}
				}
			}
			// Phase D — multi-column sort stack. Each Sort entry walks the
			// generated dispatch; unknown fields are silently skipped.
			if len(opts.Sort) > 0 {
				for _, k := range opts.Sort {
					switch k.Field {
					case "id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entRule.FieldID))
						} else {
							q = q.Order(ent.Desc(entRule.FieldID))
						}
					case "created_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entRule.FieldCreatedAt))
						} else {
							q = q.Order(ent.Desc(entRule.FieldCreatedAt))
						}
					case "updated_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entRule.FieldUpdatedAt))
						} else {
							q = q.Order(ent.Desc(entRule.FieldUpdatedAt))
						}
					case "last_accessed_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entRule.FieldLastAccessedAt))
						} else {
							q = q.Order(ent.Desc(entRule.FieldLastAccessedAt))
						}
					case "last_validated_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entRule.FieldLastValidatedAt))
						} else {
							q = q.Order(ent.Desc(entRule.FieldLastValidatedAt))
						}
					case "archived_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entRule.FieldArchivedAt))
						} else {
							q = q.Order(ent.Desc(entRule.FieldArchivedAt))
						}
					case "source_kind":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entRule.FieldSourceKind))
						} else {
							q = q.Order(ent.Desc(entRule.FieldSourceKind))
						}
					case "source_ref":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entRule.FieldSourceRef))
						} else {
							q = q.Order(ent.Desc(entRule.FieldSourceRef))
						}
					case "project_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entRule.FieldProjectID))
						} else {
							q = q.Order(ent.Desc(entRule.FieldProjectID))
						}
					case "repo_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entRule.FieldRepoID))
						} else {
							q = q.Order(ent.Desc(entRule.FieldRepoID))
						}
					case "activation":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entRule.FieldActivation))
						} else {
							q = q.Order(ent.Desc(entRule.FieldActivation))
						}
					case "globs":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entRule.FieldGlobs))
						} else {
							q = q.Order(ent.Desc(entRule.FieldGlobs))
						}
					case "applies_to_description":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entRule.FieldAppliesToDescription))
						} else {
							q = q.Order(ent.Desc(entRule.FieldAppliesToDescription))
						}
					case "severity":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entRule.FieldSeverity))
						} else {
							q = q.Order(ent.Desc(entRule.FieldSeverity))
						}
					case "superseded_by_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entRule.FieldSupersededByID))
						} else {
							q = q.Order(ent.Desc(entRule.FieldSupersededByID))
						}
					case "created_by_actor_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entRule.FieldCreatedByActorID))
						} else {
							q = q.Order(ent.Desc(entRule.FieldCreatedByActorID))
						}
					}
				}
			}
			total, err := q.Clone().Count(ctx)
			if err != nil {
				return nil, 0, err
			}
			rows, err := q.Offset(opts.Offset).Limit(opts.Limit).All(ctx)
			return rows, total, err
		},

		// Ent-native JSON for the `J` clipboard shortcut. *ent.Rule
		// implements MarshalJSON so eager-loaded edges (from With*())
		// land in the output under `edges` automatically.
		JSON: func(r *ent.Rule) ([]byte, error) { return json.Marshal(r) },

		Columns: []runtime.Column[*ent.Rule]{
			{
				Key:        "id",
				Label:      "Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Rule) string {
					return r.ID
				},
			},
			{
				Key:        "created_at",
				Label:      "Created At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Rule) string {
					if r.CreatedAt.IsZero() {
						return ""
					}
					return r.CreatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "updated_at",
				Label:      "Updated At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Rule) string {
					if r.UpdatedAt.IsZero() {
						return ""
					}
					return r.UpdatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "trust_score",
				Label:      "Trust Score",
				Sortable:   false,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Rule) string {
					return fmt.Sprintf("%v", r.TrustScore)
				},
			},
			{
				Key:        "confidence",
				Label:      "Confidence",
				Sortable:   false,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Rule) string {
					if r.Confidence == nil {
						return ""
					}
					return fmt.Sprintf("%v", *r.Confidence)
				},
			},
			{
				Key:        "last_accessed_at",
				Label:      "Last Accessed At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Rule) string {
					if r.LastAccessedAt == nil || r.LastAccessedAt.IsZero() {
						return ""
					}
					return r.LastAccessedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "last_validated_at",
				Label:      "Last Validated At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Rule) string {
					if r.LastValidatedAt == nil || r.LastValidatedAt.IsZero() {
						return ""
					}
					return r.LastValidatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "archived_at",
				Label:      "Archived At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Rule) string {
					if r.ArchivedAt == nil || r.ArchivedAt.IsZero() {
						return ""
					}
					return r.ArchivedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "source_kind",
				Label:      "Source Kind",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Rule) string {
					return r.SourceKind
				},
			},
			{
				Key:        "source_ref",
				Label:      "Source Ref",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Rule) string {
					if r.SourceRef == nil {
						return ""
					}
					return *r.SourceRef
				},
			},
			{
				Key:        "project_id",
				Label:      "Project Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Rule) string {
					if r.ProjectID == nil {
						return ""
					}
					return *r.ProjectID
				},
			},
			{
				Key:        "repo_id",
				Label:      "Repo Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Rule) string {
					if r.RepoID == nil {
						return ""
					}
					return *r.RepoID
				},
			},
			{
				Key:        "body",
				Label:      "Body",
				Sortable:   false,
				Filterable: false,
				Hidden:     true,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Rule) string {
					return r.Body
				},
			},
			{
				Key:        "activation",
				Label:      "Activation",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				EnumValues: []string{
					"always",
					"glob",
					"semantic",
					"manual",
				},
				Get: func(r *ent.Rule) string {
					return string(r.Activation)
				},
			},
			{
				Key:        "globs",
				Label:      "Globs",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Rule) string {
					if r.Globs == nil {
						return ""
					}
					return *r.Globs
				},
			},
			{
				Key:        "applies_to_description",
				Label:      "Applies To Description",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Rule) string {
					if r.AppliesToDescription == nil {
						return ""
					}
					return *r.AppliesToDescription
				},
			},
			{
				Key:        "severity",
				Label:      "Severity",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				EnumValues: []string{
					"must",
					"should",
					"may",
				},
				Get: func(r *ent.Rule) string {
					return string(r.Severity)
				},
			},
			{
				Key:        "superseded_by_id",
				Label:      "Superseded By Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Rule) string {
					if r.SupersededByID == nil {
						return ""
					}
					return *r.SupersededByID
				},
			},
			{
				Key:        "created_by_actor_id",
				Label:      "Created By Actor Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Rule) string {
					if r.CreatedByActorID == nil {
						return ""
					}
					return *r.CreatedByActorID
				},
			},
		},
	})
}
