// Code generated by enttui. DO NOT EDIT.

package tuigen

import (
	"context"
	"dbent/gen/ent"
	entAssembleCitation "dbent/gen/ent/assemblecitation"
	"encoding/json"
	"fmt"

	"github.com/khanakia/entx/enttui/runtime"
)

// registerAssembleCitation wires *ent.AssembleCitation into the enttui runtime.
//
// Scope filtering: for every scope key configured in enttui.Config.ScopeFields
// that exists on this schema, the Fetch closure below reads opts.Scope[key]
// and applies a predicate when set. Caller drives this via app.SetScope(key, value).
func registerAssembleCitation(app *runtime.App, client *ent.Client) {
	runtime.Register(app, runtime.EntitySpec[*ent.AssembleCitation]{
		Kind:           "assemblecitation",
		Display:        "AssembleCitations",
		Group:          "data",
		Icon:           "•",
		LabelKey:       "id",
		BodyKey:        "",
		IDKey:          "id",
		PageSize:       200,
		MultiSort:      true,
		ShowEdgeCounts: true,
		AllowBulkCopy:  false,
		AllowExport:    false,
		Default: runtime.DefaultView{
			SortField: "created_at",
			SortDir:   runtime.Desc,
			Mode:      "",
		},

		Fetch: func(ctx context.Context, opts runtime.ListOpts) ([]*ent.AssembleCitation, int, error) {
			q := client.AssembleCitation.Query()
			// Scope predicate — keyed generically via ListOpts.Scope so the
			// runtime stays decoupled from any specific field name.
			if v := opts.Scope["project_id"]; v != "" {
				q = q.Where(entAssembleCitation.ProjectID(v))
			}
			// Legacy substring filter — used by the list+preview browser's
			// global `/` prompt. Phase E (Filters slice) supersedes this
			// in the table view but both can coexist.
			if opts.Filter != "" {
				q = q.Where(entAssembleCitation.Or(
					entAssembleCitation.IDContainsFold(opts.Filter),
					entAssembleCitation.ProjectIDContainsFold(opts.Filter),
					entAssembleCitation.AssembleRunIDContainsFold(opts.Filter),
					entAssembleCitation.EntityTableContainsFold(opts.Filter),
					entAssembleCitation.EntityIDContainsFold(opts.Filter),
				))
			}
			// Phase E — structured per-column filters. AND-composed.
			// Unsupported operators for a given field type fall through
			// silently rather than erroring — keeps the UI forgiving.
			for _, f := range opts.Filters {
				switch f.Field {
				case "id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entAssembleCitation.IDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entAssembleCitation.IDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entAssembleCitation.IDContainsFold(f.Value))
					}
				case "project_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entAssembleCitation.ProjectIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entAssembleCitation.ProjectIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entAssembleCitation.ProjectIDContainsFold(f.Value))
					}
				case "assemble_run_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entAssembleCitation.AssembleRunIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entAssembleCitation.AssembleRunIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entAssembleCitation.AssembleRunIDContainsFold(f.Value))
					}
				case "entity_table":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entAssembleCitation.EntityTableEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entAssembleCitation.EntityTableNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entAssembleCitation.EntityTableContainsFold(f.Value))
					}
				case "entity_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entAssembleCitation.EntityIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entAssembleCitation.EntityIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entAssembleCitation.EntityIDContainsFold(f.Value))
					}
				}
			}
			// Phase D — multi-column sort stack. Each Sort entry walks the
			// generated dispatch; unknown fields are silently skipped.
			if len(opts.Sort) > 0 {
				for _, k := range opts.Sort {
					switch k.Field {
					case "id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entAssembleCitation.FieldID))
						} else {
							q = q.Order(ent.Desc(entAssembleCitation.FieldID))
						}
					case "created_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entAssembleCitation.FieldCreatedAt))
						} else {
							q = q.Order(ent.Desc(entAssembleCitation.FieldCreatedAt))
						}
					case "updated_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entAssembleCitation.FieldUpdatedAt))
						} else {
							q = q.Order(ent.Desc(entAssembleCitation.FieldUpdatedAt))
						}
					case "project_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entAssembleCitation.FieldProjectID))
						} else {
							q = q.Order(ent.Desc(entAssembleCitation.FieldProjectID))
						}
					case "assemble_run_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entAssembleCitation.FieldAssembleRunID))
						} else {
							q = q.Order(ent.Desc(entAssembleCitation.FieldAssembleRunID))
						}
					case "entity_table":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entAssembleCitation.FieldEntityTable))
						} else {
							q = q.Order(ent.Desc(entAssembleCitation.FieldEntityTable))
						}
					case "entity_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entAssembleCitation.FieldEntityID))
						} else {
							q = q.Order(ent.Desc(entAssembleCitation.FieldEntityID))
						}
					}
				}
			}
			total, err := q.Clone().Count(ctx)
			if err != nil {
				return nil, 0, err
			}
			rows, err := q.Offset(opts.Offset).Limit(opts.Limit).All(ctx)
			return rows, total, err
		},

		// Ent-native JSON for the `J` clipboard shortcut. *ent.AssembleCitation
		// implements MarshalJSON so eager-loaded edges (from With*())
		// land in the output under `edges` automatically.
		JSON: func(r *ent.AssembleCitation) ([]byte, error) { return json.Marshal(r) },

		Columns: []runtime.Column[*ent.AssembleCitation]{
			{
				Key:        "id",
				Label:      "Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.AssembleCitation) string {
					return r.ID
				},
			},
			{
				Key:        "created_at",
				Label:      "Created At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.AssembleCitation) string {
					if r.CreatedAt.IsZero() {
						return ""
					}
					return r.CreatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "updated_at",
				Label:      "Updated At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.AssembleCitation) string {
					if r.UpdatedAt.IsZero() {
						return ""
					}
					return r.UpdatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "project_id",
				Label:      "Project Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.AssembleCitation) string {
					return r.ProjectID
				},
			},
			{
				Key:        "assemble_run_id",
				Label:      "Assemble Run Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.AssembleCitation) string {
					return r.AssembleRunID
				},
			},
			{
				Key:        "entity_table",
				Label:      "Entity Table",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.AssembleCitation) string {
					return r.EntityTable
				},
			},
			{
				Key:        "entity_id",
				Label:      "Entity Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.AssembleCitation) string {
					return r.EntityID
				},
			},
			{
				Key:        "score",
				Label:      "Score",
				Sortable:   false,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.AssembleCitation) string {
					if r.Score == nil {
						return ""
					}
					return fmt.Sprintf("%v", *r.Score)
				},
			},
		},

		Edges: []runtime.EdgeSpec[*ent.AssembleCitation]{
			{
				Name: "assemble_run", Display: "→ AssembleRuns", Kind: runtime.EdgeUpward, Trigger: "a",
				// Count is emitted for BOTH upward and drill edges. For
				// upward edges it returns 0 or 1 (parent exists / doesn't).
				// For drill edges, the child row count.
				Count: func(ctx context.Context, r *ent.AssembleCitation) (int, error) {
					return client.AssembleCitation.QueryAssembleRun(r).Count(ctx)
				},
				ResolveUpward: func(ctx context.Context, r *ent.AssembleCitation) (runtime.EntityRef, error) {
					tgt, err := client.AssembleCitation.QueryAssembleRun(r).Only(ctx)
					if err != nil {
						return runtime.EntityRef{}, err
					}
					return runtime.EntityRef{Kind: "assemblerun", ID: fmt.Sprint(tgt.ID)}, nil
				},
			},
		},
	})
}
