// Code generated by enttui. DO NOT EDIT.

package tuigen

import (
	"context"
	"dbent/gen/ent"
	entPlaybook "dbent/gen/ent/playbook"
	"encoding/json"
	"fmt"

	"github.com/khanakia/entx/enttui/runtime"
)

// registerPlaybook wires *ent.Playbook into the enttui runtime.
//
// Scope filtering: for every scope key configured in enttui.Config.ScopeFields
// that exists on this schema, the Fetch closure below reads opts.Scope[key]
// and applies a predicate when set. Caller drives this via app.SetScope(key, value).
func registerPlaybook(app *runtime.App, client *ent.Client) {
	runtime.Register(app, runtime.EntitySpec[*ent.Playbook]{
		Kind:           "playbook",
		Display:        "Playbooks",
		Group:          "data",
		Icon:           "•",
		LabelKey:       "name",
		BodyKey:        "body",
		IDKey:          "id",
		PageSize:       200,
		MultiSort:      true,
		ShowEdgeCounts: true,
		AllowBulkCopy:  false,
		AllowExport:    false,
		Default: runtime.DefaultView{
			SortField: "created_at",
			SortDir:   runtime.Desc,
			Mode:      "",
		},

		Fetch: func(ctx context.Context, opts runtime.ListOpts) ([]*ent.Playbook, int, error) {
			q := client.Playbook.Query()
			// Scope predicate — keyed generically via ListOpts.Scope so the
			// runtime stays decoupled from any specific field name.
			if v := opts.Scope["project_id"]; v != "" {
				q = q.Where(entPlaybook.ProjectID(v))
			}
			// Legacy substring filter — used by the list+preview browser's
			// global `/` prompt. Phase E (Filters slice) supersedes this
			// in the table view but both can coexist.
			if opts.Filter != "" {
				q = q.Where(entPlaybook.Or(
					entPlaybook.IDContainsFold(opts.Filter),
					entPlaybook.SourceKindContainsFold(opts.Filter),
					entPlaybook.SourceRefContainsFold(opts.Filter),
					entPlaybook.ProjectIDContainsFold(opts.Filter),
					entPlaybook.NameContainsFold(opts.Filter),
					entPlaybook.ComposesContainsFold(opts.Filter),
					entPlaybook.CreatedByActorIDContainsFold(opts.Filter),
				))
			}
			// Phase E — structured per-column filters. AND-composed.
			// Unsupported operators for a given field type fall through
			// silently rather than erroring — keeps the UI forgiving.
			for _, f := range opts.Filters {
				switch f.Field {
				case "id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entPlaybook.IDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entPlaybook.IDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entPlaybook.IDContainsFold(f.Value))
					}
				case "source_kind":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entPlaybook.SourceKindEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entPlaybook.SourceKindNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entPlaybook.SourceKindContainsFold(f.Value))
					}
				case "source_ref":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entPlaybook.SourceRefEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entPlaybook.SourceRefNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entPlaybook.SourceRefContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entPlaybook.SourceRefIsNil())
					case runtime.OpNotNull:
						q = q.Where(entPlaybook.SourceRefNotNil())
					}
				case "project_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entPlaybook.ProjectIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entPlaybook.ProjectIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entPlaybook.ProjectIDContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entPlaybook.ProjectIDIsNil())
					case runtime.OpNotNull:
						q = q.Where(entPlaybook.ProjectIDNotNil())
					}
				case "name":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entPlaybook.NameEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entPlaybook.NameNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entPlaybook.NameContainsFold(f.Value))
					}
				case "composes":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entPlaybook.ComposesEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entPlaybook.ComposesNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entPlaybook.ComposesContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entPlaybook.ComposesIsNil())
					case runtime.OpNotNull:
						q = q.Where(entPlaybook.ComposesNotNil())
					}
				case "created_by_actor_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entPlaybook.CreatedByActorIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entPlaybook.CreatedByActorIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entPlaybook.CreatedByActorIDContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entPlaybook.CreatedByActorIDIsNil())
					case runtime.OpNotNull:
						q = q.Where(entPlaybook.CreatedByActorIDNotNil())
					}
				}
			}
			// Phase D — multi-column sort stack. Each Sort entry walks the
			// generated dispatch; unknown fields are silently skipped.
			if len(opts.Sort) > 0 {
				for _, k := range opts.Sort {
					switch k.Field {
					case "id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entPlaybook.FieldID))
						} else {
							q = q.Order(ent.Desc(entPlaybook.FieldID))
						}
					case "created_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entPlaybook.FieldCreatedAt))
						} else {
							q = q.Order(ent.Desc(entPlaybook.FieldCreatedAt))
						}
					case "updated_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entPlaybook.FieldUpdatedAt))
						} else {
							q = q.Order(ent.Desc(entPlaybook.FieldUpdatedAt))
						}
					case "last_accessed_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entPlaybook.FieldLastAccessedAt))
						} else {
							q = q.Order(ent.Desc(entPlaybook.FieldLastAccessedAt))
						}
					case "last_validated_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entPlaybook.FieldLastValidatedAt))
						} else {
							q = q.Order(ent.Desc(entPlaybook.FieldLastValidatedAt))
						}
					case "archived_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entPlaybook.FieldArchivedAt))
						} else {
							q = q.Order(ent.Desc(entPlaybook.FieldArchivedAt))
						}
					case "source_kind":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entPlaybook.FieldSourceKind))
						} else {
							q = q.Order(ent.Desc(entPlaybook.FieldSourceKind))
						}
					case "source_ref":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entPlaybook.FieldSourceRef))
						} else {
							q = q.Order(ent.Desc(entPlaybook.FieldSourceRef))
						}
					case "project_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entPlaybook.FieldProjectID))
						} else {
							q = q.Order(ent.Desc(entPlaybook.FieldProjectID))
						}
					case "name":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entPlaybook.FieldName))
						} else {
							q = q.Order(ent.Desc(entPlaybook.FieldName))
						}
					case "composes":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entPlaybook.FieldComposes))
						} else {
							q = q.Order(ent.Desc(entPlaybook.FieldComposes))
						}
					case "created_by_actor_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entPlaybook.FieldCreatedByActorID))
						} else {
							q = q.Order(ent.Desc(entPlaybook.FieldCreatedByActorID))
						}
					}
				}
			}
			total, err := q.Clone().Count(ctx)
			if err != nil {
				return nil, 0, err
			}
			rows, err := q.Offset(opts.Offset).Limit(opts.Limit).All(ctx)
			return rows, total, err
		},

		// Ent-native JSON for the `J` clipboard shortcut. *ent.Playbook
		// implements MarshalJSON so eager-loaded edges (from With*())
		// land in the output under `edges` automatically.
		JSON: func(r *ent.Playbook) ([]byte, error) { return json.Marshal(r) },

		Columns: []runtime.Column[*ent.Playbook]{
			{
				Key:        "id",
				Label:      "Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Playbook) string {
					return r.ID
				},
			},
			{
				Key:        "created_at",
				Label:      "Created At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Playbook) string {
					if r.CreatedAt.IsZero() {
						return ""
					}
					return r.CreatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "updated_at",
				Label:      "Updated At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Playbook) string {
					if r.UpdatedAt.IsZero() {
						return ""
					}
					return r.UpdatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "trust_score",
				Label:      "Trust Score",
				Sortable:   false,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Playbook) string {
					return fmt.Sprintf("%v", r.TrustScore)
				},
			},
			{
				Key:        "confidence",
				Label:      "Confidence",
				Sortable:   false,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Playbook) string {
					if r.Confidence == nil {
						return ""
					}
					return fmt.Sprintf("%v", *r.Confidence)
				},
			},
			{
				Key:        "last_accessed_at",
				Label:      "Last Accessed At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Playbook) string {
					if r.LastAccessedAt == nil || r.LastAccessedAt.IsZero() {
						return ""
					}
					return r.LastAccessedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "last_validated_at",
				Label:      "Last Validated At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Playbook) string {
					if r.LastValidatedAt == nil || r.LastValidatedAt.IsZero() {
						return ""
					}
					return r.LastValidatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "archived_at",
				Label:      "Archived At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Playbook) string {
					if r.ArchivedAt == nil || r.ArchivedAt.IsZero() {
						return ""
					}
					return r.ArchivedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "source_kind",
				Label:      "Source Kind",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Playbook) string {
					return r.SourceKind
				},
			},
			{
				Key:        "source_ref",
				Label:      "Source Ref",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Playbook) string {
					if r.SourceRef == nil {
						return ""
					}
					return *r.SourceRef
				},
			},
			{
				Key:        "project_id",
				Label:      "Project Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Playbook) string {
					if r.ProjectID == nil {
						return ""
					}
					return *r.ProjectID
				},
			},
			{
				Key:        "name",
				Label:      "Name",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Playbook) string {
					return r.Name
				},
			},
			{
				Key:        "description",
				Label:      "Description",
				Sortable:   false,
				Filterable: false,
				Hidden:     true,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Playbook) string {
					return r.Description
				},
			},
			{
				Key:        "body",
				Label:      "Body",
				Sortable:   false,
				Filterable: false,
				Hidden:     true,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Playbook) string {
					return r.Body
				},
			},
			{
				Key:        "composes",
				Label:      "Composes",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Playbook) string {
					if r.Composes == nil {
						return ""
					}
					return *r.Composes
				},
			},
			{
				Key:        "created_by_actor_id",
				Label:      "Created By Actor Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Playbook) string {
					if r.CreatedByActorID == nil {
						return ""
					}
					return *r.CreatedByActorID
				},
			},
		},
	})
}
