// Code generated by enttui. DO NOT EDIT.

package tuigen

import (
	"context"
	"dbent/gen/ent"
	entTrustedPlugin "dbent/gen/ent/trustedplugin"
	"encoding/json"

	"github.com/khanakia/entx/enttui/runtime"
)

// registerTrustedPlugin wires *ent.TrustedPlugin into the enttui runtime.
//
// Scope filtering: for every scope key configured in enttui.Config.ScopeFields
// that exists on this schema, the Fetch closure below reads opts.Scope[key]
// and applies a predicate when set. Caller drives this via app.SetScope(key, value).
func registerTrustedPlugin(app *runtime.App, client *ent.Client) {
	runtime.Register(app, runtime.EntitySpec[*ent.TrustedPlugin]{
		Kind:           "trustedplugin",
		Display:        "TrustedPlugins",
		Group:          "data",
		Icon:           "•",
		LabelKey:       "name",
		BodyKey:        "",
		IDKey:          "id",
		PageSize:       200,
		MultiSort:      true,
		ShowEdgeCounts: true,
		AllowBulkCopy:  false,
		AllowExport:    false,
		Default: runtime.DefaultView{
			SortField: "created_at",
			SortDir:   runtime.Desc,
			Mode:      "",
		},

		Fetch: func(ctx context.Context, opts runtime.ListOpts) ([]*ent.TrustedPlugin, int, error) {
			q := client.TrustedPlugin.Query()
			// Legacy substring filter — used by the list+preview browser's
			// global `/` prompt. Phase E (Filters slice) supersedes this
			// in the table view but both can coexist.
			if opts.Filter != "" {
				q = q.Where(entTrustedPlugin.Or(
					entTrustedPlugin.IDContainsFold(opts.Filter),
					entTrustedPlugin.NameContainsFold(opts.Filter),
					entTrustedPlugin.Sha256ContainsFold(opts.Filter),
					entTrustedPlugin.TrustedByActorIDContainsFold(opts.Filter),
				))
			}
			// Phase E — structured per-column filters. AND-composed.
			// Unsupported operators for a given field type fall through
			// silently rather than erroring — keeps the UI forgiving.
			for _, f := range opts.Filters {
				switch f.Field {
				case "id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entTrustedPlugin.IDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entTrustedPlugin.IDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entTrustedPlugin.IDContainsFold(f.Value))
					}
				case "name":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entTrustedPlugin.NameEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entTrustedPlugin.NameNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entTrustedPlugin.NameContainsFold(f.Value))
					}
				case "sha256":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entTrustedPlugin.Sha256EQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entTrustedPlugin.Sha256NEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entTrustedPlugin.Sha256ContainsFold(f.Value))
					}
				case "trusted_by_actor_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entTrustedPlugin.TrustedByActorIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entTrustedPlugin.TrustedByActorIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entTrustedPlugin.TrustedByActorIDContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entTrustedPlugin.TrustedByActorIDIsNil())
					case runtime.OpNotNull:
						q = q.Where(entTrustedPlugin.TrustedByActorIDNotNil())
					}
				}
			}
			// Phase D — multi-column sort stack. Each Sort entry walks the
			// generated dispatch; unknown fields are silently skipped.
			if len(opts.Sort) > 0 {
				for _, k := range opts.Sort {
					switch k.Field {
					case "id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entTrustedPlugin.FieldID))
						} else {
							q = q.Order(ent.Desc(entTrustedPlugin.FieldID))
						}
					case "created_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entTrustedPlugin.FieldCreatedAt))
						} else {
							q = q.Order(ent.Desc(entTrustedPlugin.FieldCreatedAt))
						}
					case "updated_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entTrustedPlugin.FieldUpdatedAt))
						} else {
							q = q.Order(ent.Desc(entTrustedPlugin.FieldUpdatedAt))
						}
					case "name":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entTrustedPlugin.FieldName))
						} else {
							q = q.Order(ent.Desc(entTrustedPlugin.FieldName))
						}
					case "sha256":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entTrustedPlugin.FieldSha256))
						} else {
							q = q.Order(ent.Desc(entTrustedPlugin.FieldSha256))
						}
					case "trusted_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entTrustedPlugin.FieldTrustedAt))
						} else {
							q = q.Order(ent.Desc(entTrustedPlugin.FieldTrustedAt))
						}
					case "trusted_by_actor_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entTrustedPlugin.FieldTrustedByActorID))
						} else {
							q = q.Order(ent.Desc(entTrustedPlugin.FieldTrustedByActorID))
						}
					}
				}
			}
			total, err := q.Clone().Count(ctx)
			if err != nil {
				return nil, 0, err
			}
			rows, err := q.Offset(opts.Offset).Limit(opts.Limit).All(ctx)
			return rows, total, err
		},

		// Ent-native JSON for the `J` clipboard shortcut. *ent.TrustedPlugin
		// implements MarshalJSON so eager-loaded edges (from With*())
		// land in the output under `edges` automatically.
		JSON: func(r *ent.TrustedPlugin) ([]byte, error) { return json.Marshal(r) },

		Columns: []runtime.Column[*ent.TrustedPlugin]{
			{
				Key:        "id",
				Label:      "Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.TrustedPlugin) string {
					return r.ID
				},
			},
			{
				Key:        "created_at",
				Label:      "Created At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.TrustedPlugin) string {
					if r.CreatedAt.IsZero() {
						return ""
					}
					return r.CreatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "updated_at",
				Label:      "Updated At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.TrustedPlugin) string {
					if r.UpdatedAt.IsZero() {
						return ""
					}
					return r.UpdatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "name",
				Label:      "Name",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.TrustedPlugin) string {
					return r.Name
				},
			},
			{
				Key:        "sha256",
				Label:      "Sha256",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.TrustedPlugin) string {
					return r.Sha256
				},
			},
			{
				Key:        "trusted_at",
				Label:      "Trusted At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.TrustedPlugin) string {
					if r.TrustedAt.IsZero() {
						return ""
					}
					return r.TrustedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "trusted_by_actor_id",
				Label:      "Trusted By Actor Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.TrustedPlugin) string {
					if r.TrustedByActorID == nil {
						return ""
					}
					return *r.TrustedByActorID
				},
			},
		},
	})
}
