// Code generated by enttui. DO NOT EDIT.

package tuigen

import (
	"context"
	"dbent/gen/ent"
	entMission "dbent/gen/ent/mission"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/khanakia/entx/enttui/runtime"
)

// registerMission wires *ent.Mission into the enttui runtime.
//
// Scope filtering: for every scope key configured in enttui.Config.ScopeFields
// that exists on this schema, the Fetch closure below reads opts.Scope[key]
// and applies a predicate when set. Caller drives this via app.SetScope(key, value).
func registerMission(app *runtime.App, client *ent.Client) {
	runtime.Register(app, runtime.EntitySpec[*ent.Mission]{
		Kind:           "mission",
		Display:        "Missions",
		Group:          "data",
		Icon:           "•",
		LabelKey:       "title",
		BodyKey:        "body",
		IDKey:          "id",
		PageSize:       200,
		MultiSort:      true,
		ShowEdgeCounts: true,
		AllowBulkCopy:  false,
		AllowExport:    false,
		Default: runtime.DefaultView{
			SortField: "created_at",
			SortDir:   runtime.Desc,
			Mode:      "",
		},

		Fetch: func(ctx context.Context, opts runtime.ListOpts) ([]*ent.Mission, int, error) {
			q := client.Mission.Query()
			// Scope predicate — keyed generically via ListOpts.Scope so the
			// runtime stays decoupled from any specific field name.
			if v := opts.Scope["project_id"]; v != "" {
				q = q.Where(entMission.ProjectID(v))
			}
			// Legacy substring filter — used by the list+preview browser's
			// global `/` prompt. Phase E (Filters slice) supersedes this
			// in the table view but both can coexist.
			if opts.Filter != "" {
				q = q.Where(entMission.Or(
					entMission.IDContainsFold(opts.Filter),
					entMission.ProjectIDContainsFold(opts.Filter),
					entMission.TitleContainsFold(opts.Filter),
					entMission.CreatedByActorIDContainsFold(opts.Filter),
				))
			}
			// Phase E — structured per-column filters. AND-composed.
			// Unsupported operators for a given field type fall through
			// silently rather than erroring — keeps the UI forgiving.
			for _, f := range opts.Filters {
				switch f.Field {
				case "id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entMission.IDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entMission.IDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entMission.IDContainsFold(f.Value))
					}
				case "project_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entMission.ProjectIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entMission.ProjectIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entMission.ProjectIDContainsFold(f.Value))
					}
				case "title":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entMission.TitleEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entMission.TitleNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entMission.TitleContainsFold(f.Value))
					}
				case "status":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entMission.StatusEQ(entMission.Status(f.Value)))
					case runtime.OpNeq:
						q = q.Where(entMission.StatusNEQ(entMission.Status(f.Value)))
					case runtime.OpIn, runtime.OpNotIn:
						// Multi-select: condition value is a "|"-joined
						// list of enum strings. Empty entries are dropped.
						parts := strings.Split(f.Value, "|")
						vals := make([]entMission.Status, 0, len(parts))
						for _, p := range parts {
							if p == "" {
								continue
							}
							vals = append(vals, entMission.Status(p))
						}
						if len(vals) > 0 {
							if f.Op == runtime.OpIn {
								q = q.Where(entMission.StatusIn(vals...))
							} else {
								q = q.Where(entMission.StatusNotIn(vals...))
							}
						}
					}
				case "created_by_actor_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entMission.CreatedByActorIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entMission.CreatedByActorIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entMission.CreatedByActorIDContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entMission.CreatedByActorIDIsNil())
					case runtime.OpNotNull:
						q = q.Where(entMission.CreatedByActorIDNotNil())
					}
				}
			}
			// Phase D — multi-column sort stack. Each Sort entry walks the
			// generated dispatch; unknown fields are silently skipped.
			if len(opts.Sort) > 0 {
				for _, k := range opts.Sort {
					switch k.Field {
					case "id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entMission.FieldID))
						} else {
							q = q.Order(ent.Desc(entMission.FieldID))
						}
					case "created_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entMission.FieldCreatedAt))
						} else {
							q = q.Order(ent.Desc(entMission.FieldCreatedAt))
						}
					case "updated_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entMission.FieldUpdatedAt))
						} else {
							q = q.Order(ent.Desc(entMission.FieldUpdatedAt))
						}
					case "project_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entMission.FieldProjectID))
						} else {
							q = q.Order(ent.Desc(entMission.FieldProjectID))
						}
					case "title":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entMission.FieldTitle))
						} else {
							q = q.Order(ent.Desc(entMission.FieldTitle))
						}
					case "status":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entMission.FieldStatus))
						} else {
							q = q.Order(ent.Desc(entMission.FieldStatus))
						}
					case "target_date":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entMission.FieldTargetDate))
						} else {
							q = q.Order(ent.Desc(entMission.FieldTargetDate))
						}
					case "completed_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entMission.FieldCompletedAt))
						} else {
							q = q.Order(ent.Desc(entMission.FieldCompletedAt))
						}
					case "created_by_actor_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entMission.FieldCreatedByActorID))
						} else {
							q = q.Order(ent.Desc(entMission.FieldCreatedByActorID))
						}
					}
				}
			}
			total, err := q.Clone().Count(ctx)
			if err != nil {
				return nil, 0, err
			}
			rows, err := q.Offset(opts.Offset).Limit(opts.Limit).All(ctx)
			return rows, total, err
		},

		// Ent-native JSON for the `J` clipboard shortcut. *ent.Mission
		// implements MarshalJSON so eager-loaded edges (from With*())
		// land in the output under `edges` automatically.
		JSON: func(r *ent.Mission) ([]byte, error) { return json.Marshal(r) },

		Columns: []runtime.Column[*ent.Mission]{
			{
				Key:        "id",
				Label:      "Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Mission) string {
					return r.ID
				},
			},
			{
				Key:        "created_at",
				Label:      "Created At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Mission) string {
					if r.CreatedAt.IsZero() {
						return ""
					}
					return r.CreatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "updated_at",
				Label:      "Updated At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Mission) string {
					if r.UpdatedAt.IsZero() {
						return ""
					}
					return r.UpdatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "project_id",
				Label:      "Project Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Mission) string {
					return r.ProjectID
				},
			},
			{
				Key:        "title",
				Label:      "Title",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Mission) string {
					return r.Title
				},
			},
			{
				Key:        "body",
				Label:      "Body",
				Sortable:   false,
				Filterable: false,
				Hidden:     true,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Mission) string {
					if r.Body == nil {
						return ""
					}
					return *r.Body
				},
			},
			{
				Key:        "status",
				Label:      "Status",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				EnumValues: []string{
					"active",
					"paused",
					"done",
					"cancelled",
				},
				Get: func(r *ent.Mission) string {
					return string(r.Status)
				},
			},
			{
				Key:        "target_date",
				Label:      "Target Date",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Mission) string {
					if r.TargetDate == nil || r.TargetDate.IsZero() {
						return ""
					}
					return r.TargetDate.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "completed_at",
				Label:      "Completed At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Mission) string {
					if r.CompletedAt == nil || r.CompletedAt.IsZero() {
						return ""
					}
					return r.CompletedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "created_by_actor_id",
				Label:      "Created By Actor Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Mission) string {
					if r.CreatedByActorID == nil {
						return ""
					}
					return *r.CreatedByActorID
				},
			},
		},

		Edges: []runtime.EdgeSpec[*ent.Mission]{
			{
				Name: "tasks", Display: "Tasks", Kind: runtime.EdgeDrill, Trigger: "t",
				// Count is emitted for BOTH upward and drill edges. For
				// upward edges it returns 0 or 1 (parent exists / doesn't).
				// For drill edges, the child row count.
				Count: func(ctx context.Context, r *ent.Mission) (int, error) {
					return client.Mission.QueryTasks(r).Count(ctx)
				},
				ResolveDrill: func(ctx context.Context, r *ent.Mission) (runtime.EntityRefList, error) {
					ids, err := client.Mission.QueryTasks(r).IDs(ctx)
					if err != nil {
						return runtime.EntityRefList{}, err
					}
					sids := make([]string, len(ids))
					for i, v := range ids {
						sids[i] = fmt.Sprint(v)
					}
					return runtime.EntityRefList{Kind: "task", IDs: sids}, nil
				},
			},
		},
	})
}
