// Code generated by enttui. DO NOT EDIT.

package tuigen

import (
	"context"
	"dbent/gen/ent"
	entPlan "dbent/gen/ent/plan"
	"encoding/json"
	"fmt"

	"github.com/khanakia/entx/enttui/runtime"
)

// registerPlan wires *ent.Plan into the enttui runtime.
//
// Scope filtering: for every scope key configured in enttui.Config.ScopeFields
// that exists on this schema, the Fetch closure below reads opts.Scope[key]
// and applies a predicate when set. Caller drives this via app.SetScope(key, value).
func registerPlan(app *runtime.App, client *ent.Client) {
	runtime.Register(app, runtime.EntitySpec[*ent.Plan]{
		Kind:           "plan",
		Display:        "Plans",
		Group:          "data",
		Icon:           "•",
		LabelKey:       "title",
		BodyKey:        "body",
		IDKey:          "id",
		PageSize:       200,
		MultiSort:      true,
		ShowEdgeCounts: true,
		AllowBulkCopy:  false,
		AllowExport:    false,
		Default: runtime.DefaultView{
			SortField: "created_at",
			SortDir:   runtime.Desc,
			Mode:      "",
		},

		Fetch: func(ctx context.Context, opts runtime.ListOpts) ([]*ent.Plan, int, error) {
			q := client.Plan.Query()
			// Scope predicate — keyed generically via ListOpts.Scope so the
			// runtime stays decoupled from any specific field name.
			if v := opts.Scope["project_id"]; v != "" {
				q = q.Where(entPlan.ProjectID(v))
			}
			// Legacy substring filter — used by the list+preview browser's
			// global `/` prompt. Phase E (Filters slice) supersedes this
			// in the table view but both can coexist.
			if opts.Filter != "" {
				q = q.Where(entPlan.Or(
					entPlan.IDContainsFold(opts.Filter),
					entPlan.ProjectIDContainsFold(opts.Filter),
					entPlan.TitleContainsFold(opts.Filter),
					entPlan.StatusStrContainsFold(opts.Filter),
					entPlan.CreatedByActorIDContainsFold(opts.Filter),
				))
			}
			// Phase E — structured per-column filters. AND-composed.
			// Unsupported operators for a given field type fall through
			// silently rather than erroring — keeps the UI forgiving.
			for _, f := range opts.Filters {
				switch f.Field {
				case "id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entPlan.IDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entPlan.IDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entPlan.IDContainsFold(f.Value))
					}
				case "project_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entPlan.ProjectIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entPlan.ProjectIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entPlan.ProjectIDContainsFold(f.Value))
					}
				case "title":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entPlan.TitleEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entPlan.TitleNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entPlan.TitleContainsFold(f.Value))
					}
				case "status_str":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entPlan.StatusStrEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entPlan.StatusStrNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entPlan.StatusStrContainsFold(f.Value))
					}
				case "created_by_actor_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entPlan.CreatedByActorIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entPlan.CreatedByActorIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entPlan.CreatedByActorIDContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entPlan.CreatedByActorIDIsNil())
					case runtime.OpNotNull:
						q = q.Where(entPlan.CreatedByActorIDNotNil())
					}
				}
			}
			// Phase D — multi-column sort stack. Each Sort entry walks the
			// generated dispatch; unknown fields are silently skipped.
			if len(opts.Sort) > 0 {
				for _, k := range opts.Sort {
					switch k.Field {
					case "id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entPlan.FieldID))
						} else {
							q = q.Order(ent.Desc(entPlan.FieldID))
						}
					case "created_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entPlan.FieldCreatedAt))
						} else {
							q = q.Order(ent.Desc(entPlan.FieldCreatedAt))
						}
					case "updated_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entPlan.FieldUpdatedAt))
						} else {
							q = q.Order(ent.Desc(entPlan.FieldUpdatedAt))
						}
					case "project_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entPlan.FieldProjectID))
						} else {
							q = q.Order(ent.Desc(entPlan.FieldProjectID))
						}
					case "title":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entPlan.FieldTitle))
						} else {
							q = q.Order(ent.Desc(entPlan.FieldTitle))
						}
					case "status_str":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entPlan.FieldStatusStr))
						} else {
							q = q.Order(ent.Desc(entPlan.FieldStatusStr))
						}
					case "created_by_actor_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entPlan.FieldCreatedByActorID))
						} else {
							q = q.Order(ent.Desc(entPlan.FieldCreatedByActorID))
						}
					}
				}
			}
			total, err := q.Clone().Count(ctx)
			if err != nil {
				return nil, 0, err
			}
			rows, err := q.Offset(opts.Offset).Limit(opts.Limit).All(ctx)
			return rows, total, err
		},

		// Ent-native JSON for the `J` clipboard shortcut. *ent.Plan
		// implements MarshalJSON so eager-loaded edges (from With*())
		// land in the output under `edges` automatically.
		JSON: func(r *ent.Plan) ([]byte, error) { return json.Marshal(r) },

		Columns: []runtime.Column[*ent.Plan]{
			{
				Key:        "id",
				Label:      "Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Plan) string {
					return r.ID
				},
			},
			{
				Key:        "created_at",
				Label:      "Created At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Plan) string {
					if r.CreatedAt.IsZero() {
						return ""
					}
					return r.CreatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "updated_at",
				Label:      "Updated At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Plan) string {
					if r.UpdatedAt.IsZero() {
						return ""
					}
					return r.UpdatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "project_id",
				Label:      "Project Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Plan) string {
					return r.ProjectID
				},
			},
			{
				Key:        "title",
				Label:      "Title",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Plan) string {
					return r.Title
				},
			},
			{
				Key:        "body",
				Label:      "Body",
				Sortable:   false,
				Filterable: false,
				Hidden:     true,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Plan) string {
					return r.Body
				},
			},
			{
				Key:        "status_str",
				Label:      "Status Str",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Plan) string {
					return r.StatusStr
				},
			},
			{
				Key:        "created_by_actor_id",
				Label:      "Created By Actor Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Plan) string {
					if r.CreatedByActorID == nil {
						return ""
					}
					return *r.CreatedByActorID
				},
			},
		},

		Edges: []runtime.EdgeSpec[*ent.Plan]{
			{
				Name: "tasks", Display: "Tasks", Kind: runtime.EdgeDrill, Trigger: "t",
				// Count is emitted for BOTH upward and drill edges. For
				// upward edges it returns 0 or 1 (parent exists / doesn't).
				// For drill edges, the child row count.
				Count: func(ctx context.Context, r *ent.Plan) (int, error) {
					return client.Plan.QueryTasks(r).Count(ctx)
				},
				ResolveDrill: func(ctx context.Context, r *ent.Plan) (runtime.EntityRefList, error) {
					ids, err := client.Plan.QueryTasks(r).IDs(ctx)
					if err != nil {
						return runtime.EntityRefList{}, err
					}
					sids := make([]string, len(ids))
					for i, v := range ids {
						sids[i] = fmt.Sprint(v)
					}
					return runtime.EntityRefList{Kind: "task", IDs: sids}, nil
				},
			},
		},
	})
}
