// Code generated by enttui. DO NOT EDIT.

package tuigen

import (
	"context"
	"dbent/gen/ent"
	entIdentityProfile "dbent/gen/ent/identityprofile"
	"encoding/json"

	"github.com/khanakia/entx/enttui/runtime"
)

// registerIdentityProfile wires *ent.IdentityProfile into the enttui runtime.
//
// Scope filtering: for every scope key configured in enttui.Config.ScopeFields
// that exists on this schema, the Fetch closure below reads opts.Scope[key]
// and applies a predicate when set. Caller drives this via app.SetScope(key, value).
func registerIdentityProfile(app *runtime.App, client *ent.Client) {
	runtime.Register(app, runtime.EntitySpec[*ent.IdentityProfile]{
		Kind:           "identityprofile",
		Display:        "IdentityProfiles",
		Group:          "data",
		Icon:           "•",
		LabelKey:       "display_name",
		BodyKey:        "",
		IDKey:          "id",
		PageSize:       200,
		MultiSort:      true,
		ShowEdgeCounts: true,
		AllowBulkCopy:  false,
		AllowExport:    false,
		Default: runtime.DefaultView{
			SortField: "created_at",
			SortDir:   runtime.Desc,
			Mode:      "",
		},

		Fetch: func(ctx context.Context, opts runtime.ListOpts) ([]*ent.IdentityProfile, int, error) {
			q := client.IdentityProfile.Query()
			// Legacy substring filter — used by the list+preview browser's
			// global `/` prompt. Phase E (Filters slice) supersedes this
			// in the table view but both can coexist.
			if opts.Filter != "" {
				q = q.Where(entIdentityProfile.Or(
					entIdentityProfile.IDContainsFold(opts.Filter),
					entIdentityProfile.StableKeyContainsFold(opts.Filter),
					entIdentityProfile.DisplayNameContainsFold(opts.Filter),
					entIdentityProfile.KindContainsFold(opts.Filter),
					entIdentityProfile.NotesContainsFold(opts.Filter),
				))
			}
			// Phase E — structured per-column filters. AND-composed.
			// Unsupported operators for a given field type fall through
			// silently rather than erroring — keeps the UI forgiving.
			for _, f := range opts.Filters {
				switch f.Field {
				case "id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entIdentityProfile.IDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entIdentityProfile.IDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entIdentityProfile.IDContainsFold(f.Value))
					}
				case "stable_key":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entIdentityProfile.StableKeyEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entIdentityProfile.StableKeyNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entIdentityProfile.StableKeyContainsFold(f.Value))
					}
				case "display_name":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entIdentityProfile.DisplayNameEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entIdentityProfile.DisplayNameNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entIdentityProfile.DisplayNameContainsFold(f.Value))
					}
				case "kind":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entIdentityProfile.KindEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entIdentityProfile.KindNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entIdentityProfile.KindContainsFold(f.Value))
					}
				case "notes":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entIdentityProfile.NotesEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entIdentityProfile.NotesNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entIdentityProfile.NotesContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entIdentityProfile.NotesIsNil())
					case runtime.OpNotNull:
						q = q.Where(entIdentityProfile.NotesNotNil())
					}
				}
			}
			// Phase D — multi-column sort stack. Each Sort entry walks the
			// generated dispatch; unknown fields are silently skipped.
			if len(opts.Sort) > 0 {
				for _, k := range opts.Sort {
					switch k.Field {
					case "id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entIdentityProfile.FieldID))
						} else {
							q = q.Order(ent.Desc(entIdentityProfile.FieldID))
						}
					case "created_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entIdentityProfile.FieldCreatedAt))
						} else {
							q = q.Order(ent.Desc(entIdentityProfile.FieldCreatedAt))
						}
					case "updated_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entIdentityProfile.FieldUpdatedAt))
						} else {
							q = q.Order(ent.Desc(entIdentityProfile.FieldUpdatedAt))
						}
					case "stable_key":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entIdentityProfile.FieldStableKey))
						} else {
							q = q.Order(ent.Desc(entIdentityProfile.FieldStableKey))
						}
					case "display_name":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entIdentityProfile.FieldDisplayName))
						} else {
							q = q.Order(ent.Desc(entIdentityProfile.FieldDisplayName))
						}
					case "kind":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entIdentityProfile.FieldKind))
						} else {
							q = q.Order(ent.Desc(entIdentityProfile.FieldKind))
						}
					case "notes":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entIdentityProfile.FieldNotes))
						} else {
							q = q.Order(ent.Desc(entIdentityProfile.FieldNotes))
						}
					}
				}
			}
			total, err := q.Clone().Count(ctx)
			if err != nil {
				return nil, 0, err
			}
			rows, err := q.Offset(opts.Offset).Limit(opts.Limit).All(ctx)
			return rows, total, err
		},

		// Ent-native JSON for the `J` clipboard shortcut. *ent.IdentityProfile
		// implements MarshalJSON so eager-loaded edges (from With*())
		// land in the output under `edges` automatically.
		JSON: func(r *ent.IdentityProfile) ([]byte, error) { return json.Marshal(r) },

		Columns: []runtime.Column[*ent.IdentityProfile]{
			{
				Key:        "id",
				Label:      "Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.IdentityProfile) string {
					return r.ID
				},
			},
			{
				Key:        "created_at",
				Label:      "Created At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.IdentityProfile) string {
					if r.CreatedAt.IsZero() {
						return ""
					}
					return r.CreatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "updated_at",
				Label:      "Updated At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.IdentityProfile) string {
					if r.UpdatedAt.IsZero() {
						return ""
					}
					return r.UpdatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "stable_key",
				Label:      "Stable Key",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.IdentityProfile) string {
					return r.StableKey
				},
			},
			{
				Key:        "display_name",
				Label:      "Display Name",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.IdentityProfile) string {
					return r.DisplayName
				},
			},
			{
				Key:        "kind",
				Label:      "Kind",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.IdentityProfile) string {
					return r.Kind
				},
			},
			{
				Key:        "notes",
				Label:      "Notes",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.IdentityProfile) string {
					if r.Notes == nil {
						return ""
					}
					return *r.Notes
				},
			},
		},
	})
}
