// Code generated by enttui. DO NOT EDIT.

package tuigen

import (
	"context"
	"dbent/gen/ent"
	entExternalSource "dbent/gen/ent/externalsource"
	"encoding/json"
	"fmt"

	"github.com/khanakia/entx/enttui/runtime"
)

// registerExternalSource wires *ent.ExternalSource into the enttui runtime.
//
// Scope filtering: for every scope key configured in enttui.Config.ScopeFields
// that exists on this schema, the Fetch closure below reads opts.Scope[key]
// and applies a predicate when set. Caller drives this via app.SetScope(key, value).
func registerExternalSource(app *runtime.App, client *ent.Client) {
	runtime.Register(app, runtime.EntitySpec[*ent.ExternalSource]{
		Kind:           "externalsource",
		Display:        "ExternalSources",
		Group:          "data",
		Icon:           "•",
		LabelKey:       "name",
		BodyKey:        "",
		IDKey:          "id",
		PageSize:       200,
		MultiSort:      true,
		ShowEdgeCounts: true,
		AllowBulkCopy:  false,
		AllowExport:    false,
		Default: runtime.DefaultView{
			SortField: "created_at",
			SortDir:   runtime.Desc,
			Mode:      "",
		},

		Fetch: func(ctx context.Context, opts runtime.ListOpts) ([]*ent.ExternalSource, int, error) {
			q := client.ExternalSource.Query()
			// Scope predicate — keyed generically via ListOpts.Scope so the
			// runtime stays decoupled from any specific field name.
			if v := opts.Scope["project_id"]; v != "" {
				q = q.Where(entExternalSource.ProjectID(v))
			}
			// Legacy substring filter — used by the list+preview browser's
			// global `/` prompt. Phase E (Filters slice) supersedes this
			// in the table view but both can coexist.
			if opts.Filter != "" {
				q = q.Where(entExternalSource.Or(
					entExternalSource.IDContainsFold(opts.Filter),
					entExternalSource.ProjectIDContainsFold(opts.Filter),
					entExternalSource.KindContainsFold(opts.Filter),
					entExternalSource.NameContainsFold(opts.Filter),
					entExternalSource.ConfigJSONContainsFold(opts.Filter),
				))
			}
			// Phase E — structured per-column filters. AND-composed.
			// Unsupported operators for a given field type fall through
			// silently rather than erroring — keeps the UI forgiving.
			for _, f := range opts.Filters {
				switch f.Field {
				case "id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entExternalSource.IDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entExternalSource.IDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entExternalSource.IDContainsFold(f.Value))
					}
				case "project_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entExternalSource.ProjectIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entExternalSource.ProjectIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entExternalSource.ProjectIDContainsFold(f.Value))
					}
				case "kind":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entExternalSource.KindEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entExternalSource.KindNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entExternalSource.KindContainsFold(f.Value))
					}
				case "name":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entExternalSource.NameEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entExternalSource.NameNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entExternalSource.NameContainsFold(f.Value))
					}
				case "config_json":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entExternalSource.ConfigJSONEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entExternalSource.ConfigJSONNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entExternalSource.ConfigJSONContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entExternalSource.ConfigJSONIsNil())
					case runtime.OpNotNull:
						q = q.Where(entExternalSource.ConfigJSONNotNil())
					}
				}
			}
			// Phase D — multi-column sort stack. Each Sort entry walks the
			// generated dispatch; unknown fields are silently skipped.
			if len(opts.Sort) > 0 {
				for _, k := range opts.Sort {
					switch k.Field {
					case "id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entExternalSource.FieldID))
						} else {
							q = q.Order(ent.Desc(entExternalSource.FieldID))
						}
					case "created_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entExternalSource.FieldCreatedAt))
						} else {
							q = q.Order(ent.Desc(entExternalSource.FieldCreatedAt))
						}
					case "updated_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entExternalSource.FieldUpdatedAt))
						} else {
							q = q.Order(ent.Desc(entExternalSource.FieldUpdatedAt))
						}
					case "project_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entExternalSource.FieldProjectID))
						} else {
							q = q.Order(ent.Desc(entExternalSource.FieldProjectID))
						}
					case "kind":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entExternalSource.FieldKind))
						} else {
							q = q.Order(ent.Desc(entExternalSource.FieldKind))
						}
					case "name":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entExternalSource.FieldName))
						} else {
							q = q.Order(ent.Desc(entExternalSource.FieldName))
						}
					case "config_json":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entExternalSource.FieldConfigJSON))
						} else {
							q = q.Order(ent.Desc(entExternalSource.FieldConfigJSON))
						}
					}
				}
			}
			total, err := q.Clone().Count(ctx)
			if err != nil {
				return nil, 0, err
			}
			rows, err := q.Offset(opts.Offset).Limit(opts.Limit).All(ctx)
			return rows, total, err
		},

		// Ent-native JSON for the `J` clipboard shortcut. *ent.ExternalSource
		// implements MarshalJSON so eager-loaded edges (from With*())
		// land in the output under `edges` automatically.
		JSON: func(r *ent.ExternalSource) ([]byte, error) { return json.Marshal(r) },

		Columns: []runtime.Column[*ent.ExternalSource]{
			{
				Key:        "id",
				Label:      "Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.ExternalSource) string {
					return r.ID
				},
			},
			{
				Key:        "created_at",
				Label:      "Created At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.ExternalSource) string {
					if r.CreatedAt.IsZero() {
						return ""
					}
					return r.CreatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "updated_at",
				Label:      "Updated At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.ExternalSource) string {
					if r.UpdatedAt.IsZero() {
						return ""
					}
					return r.UpdatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "project_id",
				Label:      "Project Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.ExternalSource) string {
					return r.ProjectID
				},
			},
			{
				Key:        "kind",
				Label:      "Kind",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.ExternalSource) string {
					return r.Kind
				},
			},
			{
				Key:        "name",
				Label:      "Name",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.ExternalSource) string {
					return r.Name
				},
			},
			{
				Key:        "config_json",
				Label:      "Config Json",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.ExternalSource) string {
					if r.ConfigJSON == nil {
						return ""
					}
					return *r.ConfigJSON
				},
			},
			{
				Key:        "enabled",
				Label:      "Enabled",
				Sortable:   false,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.ExternalSource) string {
					return fmt.Sprintf("%v", r.Enabled)
				},
			},
		},
	})
}
