// Code generated by enttui. DO NOT EDIT.

package tuigen

import (
	"context"
	"dbent/gen/ent"
	entInterventionMetric "dbent/gen/ent/interventionmetric"
	"encoding/json"
	"strings"

	"github.com/khanakia/entx/enttui/runtime"
)

// registerInterventionMetric wires *ent.InterventionMetric into the enttui runtime.
//
// Scope filtering: for every scope key configured in enttui.Config.ScopeFields
// that exists on this schema, the Fetch closure below reads opts.Scope[key]
// and applies a predicate when set. Caller drives this via app.SetScope(key, value).
func registerInterventionMetric(app *runtime.App, client *ent.Client) {
	runtime.Register(app, runtime.EntitySpec[*ent.InterventionMetric]{
		Kind:           "interventionmetric",
		Display:        "InterventionMetrics",
		Group:          "data",
		Icon:           "•",
		LabelKey:       "id",
		BodyKey:        "",
		IDKey:          "id",
		PageSize:       200,
		MultiSort:      true,
		ShowEdgeCounts: true,
		AllowBulkCopy:  false,
		AllowExport:    false,
		Default: runtime.DefaultView{
			SortField: "created_at",
			SortDir:   runtime.Desc,
			Mode:      "",
		},

		Fetch: func(ctx context.Context, opts runtime.ListOpts) ([]*ent.InterventionMetric, int, error) {
			q := client.InterventionMetric.Query()
			// Scope predicate — keyed generically via ListOpts.Scope so the
			// runtime stays decoupled from any specific field name.
			if v := opts.Scope["project_id"]; v != "" {
				q = q.Where(entInterventionMetric.ProjectID(v))
			}
			// Legacy substring filter — used by the list+preview browser's
			// global `/` prompt. Phase E (Filters slice) supersedes this
			// in the table view but both can coexist.
			if opts.Filter != "" {
				q = q.Where(entInterventionMetric.Or(
					entInterventionMetric.IDContainsFold(opts.Filter),
					entInterventionMetric.ProjectIDContainsFold(opts.Filter),
					entInterventionMetric.TargetTableContainsFold(opts.Filter),
					entInterventionMetric.TargetIDContainsFold(opts.Filter),
					entInterventionMetric.NotesContainsFold(opts.Filter),
					entInterventionMetric.ActorIDContainsFold(opts.Filter),
				))
			}
			// Phase E — structured per-column filters. AND-composed.
			// Unsupported operators for a given field type fall through
			// silently rather than erroring — keeps the UI forgiving.
			for _, f := range opts.Filters {
				switch f.Field {
				case "id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entInterventionMetric.IDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entInterventionMetric.IDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entInterventionMetric.IDContainsFold(f.Value))
					}
				case "project_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entInterventionMetric.ProjectIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entInterventionMetric.ProjectIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entInterventionMetric.ProjectIDContainsFold(f.Value))
					}
				case "kind":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entInterventionMetric.KindEQ(entInterventionMetric.Kind(f.Value)))
					case runtime.OpNeq:
						q = q.Where(entInterventionMetric.KindNEQ(entInterventionMetric.Kind(f.Value)))
					case runtime.OpIn, runtime.OpNotIn:
						// Multi-select: condition value is a "|"-joined
						// list of enum strings. Empty entries are dropped.
						parts := strings.Split(f.Value, "|")
						vals := make([]entInterventionMetric.Kind, 0, len(parts))
						for _, p := range parts {
							if p == "" {
								continue
							}
							vals = append(vals, entInterventionMetric.Kind(p))
						}
						if len(vals) > 0 {
							if f.Op == runtime.OpIn {
								q = q.Where(entInterventionMetric.KindIn(vals...))
							} else {
								q = q.Where(entInterventionMetric.KindNotIn(vals...))
							}
						}
					}
				case "target_table":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entInterventionMetric.TargetTableEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entInterventionMetric.TargetTableNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entInterventionMetric.TargetTableContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entInterventionMetric.TargetTableIsNil())
					case runtime.OpNotNull:
						q = q.Where(entInterventionMetric.TargetTableNotNil())
					}
				case "target_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entInterventionMetric.TargetIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entInterventionMetric.TargetIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entInterventionMetric.TargetIDContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entInterventionMetric.TargetIDIsNil())
					case runtime.OpNotNull:
						q = q.Where(entInterventionMetric.TargetIDNotNil())
					}
				case "notes":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entInterventionMetric.NotesEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entInterventionMetric.NotesNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entInterventionMetric.NotesContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entInterventionMetric.NotesIsNil())
					case runtime.OpNotNull:
						q = q.Where(entInterventionMetric.NotesNotNil())
					}
				case "actor_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entInterventionMetric.ActorIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entInterventionMetric.ActorIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entInterventionMetric.ActorIDContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entInterventionMetric.ActorIDIsNil())
					case runtime.OpNotNull:
						q = q.Where(entInterventionMetric.ActorIDNotNil())
					}
				}
			}
			// Phase D — multi-column sort stack. Each Sort entry walks the
			// generated dispatch; unknown fields are silently skipped.
			if len(opts.Sort) > 0 {
				for _, k := range opts.Sort {
					switch k.Field {
					case "id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entInterventionMetric.FieldID))
						} else {
							q = q.Order(ent.Desc(entInterventionMetric.FieldID))
						}
					case "created_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entInterventionMetric.FieldCreatedAt))
						} else {
							q = q.Order(ent.Desc(entInterventionMetric.FieldCreatedAt))
						}
					case "updated_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entInterventionMetric.FieldUpdatedAt))
						} else {
							q = q.Order(ent.Desc(entInterventionMetric.FieldUpdatedAt))
						}
					case "project_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entInterventionMetric.FieldProjectID))
						} else {
							q = q.Order(ent.Desc(entInterventionMetric.FieldProjectID))
						}
					case "kind":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entInterventionMetric.FieldKind))
						} else {
							q = q.Order(ent.Desc(entInterventionMetric.FieldKind))
						}
					case "target_table":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entInterventionMetric.FieldTargetTable))
						} else {
							q = q.Order(ent.Desc(entInterventionMetric.FieldTargetTable))
						}
					case "target_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entInterventionMetric.FieldTargetID))
						} else {
							q = q.Order(ent.Desc(entInterventionMetric.FieldTargetID))
						}
					case "notes":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entInterventionMetric.FieldNotes))
						} else {
							q = q.Order(ent.Desc(entInterventionMetric.FieldNotes))
						}
					case "actor_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entInterventionMetric.FieldActorID))
						} else {
							q = q.Order(ent.Desc(entInterventionMetric.FieldActorID))
						}
					}
				}
			}
			total, err := q.Clone().Count(ctx)
			if err != nil {
				return nil, 0, err
			}
			rows, err := q.Offset(opts.Offset).Limit(opts.Limit).All(ctx)
			return rows, total, err
		},

		// Ent-native JSON for the `J` clipboard shortcut. *ent.InterventionMetric
		// implements MarshalJSON so eager-loaded edges (from With*())
		// land in the output under `edges` automatically.
		JSON: func(r *ent.InterventionMetric) ([]byte, error) { return json.Marshal(r) },

		Columns: []runtime.Column[*ent.InterventionMetric]{
			{
				Key:        "id",
				Label:      "Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.InterventionMetric) string {
					return r.ID
				},
			},
			{
				Key:        "created_at",
				Label:      "Created At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.InterventionMetric) string {
					if r.CreatedAt.IsZero() {
						return ""
					}
					return r.CreatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "updated_at",
				Label:      "Updated At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.InterventionMetric) string {
					if r.UpdatedAt.IsZero() {
						return ""
					}
					return r.UpdatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "project_id",
				Label:      "Project Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.InterventionMetric) string {
					return r.ProjectID
				},
			},
			{
				Key:        "kind",
				Label:      "Kind",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				EnumValues: []string{
					"correction",
					"manual_edit",
					"retry",
					"rollback",
					"undo",
				},
				Get: func(r *ent.InterventionMetric) string {
					return string(r.Kind)
				},
			},
			{
				Key:        "target_table",
				Label:      "Target Table",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.InterventionMetric) string {
					if r.TargetTable == nil {
						return ""
					}
					return *r.TargetTable
				},
			},
			{
				Key:        "target_id",
				Label:      "Target Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.InterventionMetric) string {
					if r.TargetID == nil {
						return ""
					}
					return *r.TargetID
				},
			},
			{
				Key:        "notes",
				Label:      "Notes",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.InterventionMetric) string {
					if r.Notes == nil {
						return ""
					}
					return *r.Notes
				},
			},
			{
				Key:        "actor_id",
				Label:      "Actor Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.InterventionMetric) string {
					if r.ActorID == nil {
						return ""
					}
					return *r.ActorID
				},
			},
		},
	})
}
