// Code generated by enttui. DO NOT EDIT.

package tuigen

import (
	"context"
	"dbent/gen/ent"
	entMountAlias "dbent/gen/ent/mountalias"
	"encoding/json"

	"github.com/khanakia/entx/enttui/runtime"
)

// registerMountAlias wires *ent.MountAlias into the enttui runtime.
//
// Scope filtering: for every scope key configured in enttui.Config.ScopeFields
// that exists on this schema, the Fetch closure below reads opts.Scope[key]
// and applies a predicate when set. Caller drives this via app.SetScope(key, value).
func registerMountAlias(app *runtime.App, client *ent.Client) {
	runtime.Register(app, runtime.EntitySpec[*ent.MountAlias]{
		Kind:           "mountalias",
		Display:        "MountAlias",
		Group:          "data",
		Icon:           "•",
		LabelKey:       "id",
		BodyKey:        "",
		IDKey:          "id",
		PageSize:       200,
		MultiSort:      true,
		ShowEdgeCounts: true,
		AllowBulkCopy:  false,
		AllowExport:    false,
		Default: runtime.DefaultView{
			SortField: "created_at",
			SortDir:   runtime.Desc,
			Mode:      "",
		},

		Fetch: func(ctx context.Context, opts runtime.ListOpts) ([]*ent.MountAlias, int, error) {
			q := client.MountAlias.Query()
			// Legacy substring filter — used by the list+preview browser's
			// global `/` prompt. Phase E (Filters slice) supersedes this
			// in the table view but both can coexist.
			if opts.Filter != "" {
				q = q.Where(entMountAlias.Or(
					entMountAlias.IDContainsFold(opts.Filter),
					entMountAlias.RepoIDContainsFold(opts.Filter),
					entMountAlias.OldNameContainsFold(opts.Filter),
				))
			}
			// Phase E — structured per-column filters. AND-composed.
			// Unsupported operators for a given field type fall through
			// silently rather than erroring — keeps the UI forgiving.
			for _, f := range opts.Filters {
				switch f.Field {
				case "id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entMountAlias.IDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entMountAlias.IDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entMountAlias.IDContainsFold(f.Value))
					}
				case "repo_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entMountAlias.RepoIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entMountAlias.RepoIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entMountAlias.RepoIDContainsFold(f.Value))
					}
				case "old_name":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entMountAlias.OldNameEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entMountAlias.OldNameNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entMountAlias.OldNameContainsFold(f.Value))
					}
				}
			}
			// Phase D — multi-column sort stack. Each Sort entry walks the
			// generated dispatch; unknown fields are silently skipped.
			if len(opts.Sort) > 0 {
				for _, k := range opts.Sort {
					switch k.Field {
					case "id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entMountAlias.FieldID))
						} else {
							q = q.Order(ent.Desc(entMountAlias.FieldID))
						}
					case "created_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entMountAlias.FieldCreatedAt))
						} else {
							q = q.Order(ent.Desc(entMountAlias.FieldCreatedAt))
						}
					case "updated_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entMountAlias.FieldUpdatedAt))
						} else {
							q = q.Order(ent.Desc(entMountAlias.FieldUpdatedAt))
						}
					case "repo_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entMountAlias.FieldRepoID))
						} else {
							q = q.Order(ent.Desc(entMountAlias.FieldRepoID))
						}
					case "old_name":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entMountAlias.FieldOldName))
						} else {
							q = q.Order(ent.Desc(entMountAlias.FieldOldName))
						}
					case "renamed_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entMountAlias.FieldRenamedAt))
						} else {
							q = q.Order(ent.Desc(entMountAlias.FieldRenamedAt))
						}
					case "expires_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entMountAlias.FieldExpiresAt))
						} else {
							q = q.Order(ent.Desc(entMountAlias.FieldExpiresAt))
						}
					}
				}
			}
			total, err := q.Clone().Count(ctx)
			if err != nil {
				return nil, 0, err
			}
			rows, err := q.Offset(opts.Offset).Limit(opts.Limit).All(ctx)
			return rows, total, err
		},

		// Ent-native JSON for the `J` clipboard shortcut. *ent.MountAlias
		// implements MarshalJSON so eager-loaded edges (from With*())
		// land in the output under `edges` automatically.
		JSON: func(r *ent.MountAlias) ([]byte, error) { return json.Marshal(r) },

		Columns: []runtime.Column[*ent.MountAlias]{
			{
				Key:        "id",
				Label:      "Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.MountAlias) string {
					return r.ID
				},
			},
			{
				Key:        "created_at",
				Label:      "Created At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.MountAlias) string {
					if r.CreatedAt.IsZero() {
						return ""
					}
					return r.CreatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "updated_at",
				Label:      "Updated At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.MountAlias) string {
					if r.UpdatedAt.IsZero() {
						return ""
					}
					return r.UpdatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "repo_id",
				Label:      "Repo Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.MountAlias) string {
					return r.RepoID
				},
			},
			{
				Key:        "old_name",
				Label:      "Old Name",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.MountAlias) string {
					return r.OldName
				},
			},
			{
				Key:        "renamed_at",
				Label:      "Renamed At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.MountAlias) string {
					if r.RenamedAt.IsZero() {
						return ""
					}
					return r.RenamedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "expires_at",
				Label:      "Expires At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.MountAlias) string {
					if r.ExpiresAt.IsZero() {
						return ""
					}
					return r.ExpiresAt.Format("2006-01-02 15:04:05")
				},
			},
		},
	})
}
