// Code generated by enttui. DO NOT EDIT.

package tuigen

import (
	"context"
	"dbent/gen/ent"
	entActor "dbent/gen/ent/actor"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/khanakia/entx/enttui/runtime"
)

// registerActor wires *ent.Actor into the enttui runtime.
//
// Scope filtering: for every scope key configured in enttui.Config.ScopeFields
// that exists on this schema, the Fetch closure below reads opts.Scope[key]
// and applies a predicate when set. Caller drives this via app.SetScope(key, value).
func registerActor(app *runtime.App, client *ent.Client) {
	runtime.Register(app, runtime.EntitySpec[*ent.Actor]{
		Kind:           "actor",
		Display:        "Actors",
		Group:          "data",
		Icon:           "•",
		LabelKey:       "display_name",
		BodyKey:        "",
		IDKey:          "id",
		PageSize:       200,
		MultiSort:      true,
		ShowEdgeCounts: true,
		AllowBulkCopy:  false,
		AllowExport:    false,
		Default: runtime.DefaultView{
			SortField: "created_at",
			SortDir:   runtime.Desc,
			Mode:      "",
		},

		Fetch: func(ctx context.Context, opts runtime.ListOpts) ([]*ent.Actor, int, error) {
			q := client.Actor.Query()
			// Legacy substring filter — used by the list+preview browser's
			// global `/` prompt. Phase E (Filters slice) supersedes this
			// in the table view but both can coexist.
			if opts.Filter != "" {
				q = q.Where(entActor.Or(
					entActor.IDContainsFold(opts.Filter),
					entActor.DisplayNameContainsFold(opts.Filter),
					entActor.StableKeyContainsFold(opts.Filter),
				))
			}
			// Phase E — structured per-column filters. AND-composed.
			// Unsupported operators for a given field type fall through
			// silently rather than erroring — keeps the UI forgiving.
			for _, f := range opts.Filters {
				switch f.Field {
				case "id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entActor.IDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entActor.IDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entActor.IDContainsFold(f.Value))
					}
				case "kind":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entActor.KindEQ(entActor.Kind(f.Value)))
					case runtime.OpNeq:
						q = q.Where(entActor.KindNEQ(entActor.Kind(f.Value)))
					case runtime.OpIn, runtime.OpNotIn:
						// Multi-select: condition value is a "|"-joined
						// list of enum strings. Empty entries are dropped.
						parts := strings.Split(f.Value, "|")
						vals := make([]entActor.Kind, 0, len(parts))
						for _, p := range parts {
							if p == "" {
								continue
							}
							vals = append(vals, entActor.Kind(p))
						}
						if len(vals) > 0 {
							if f.Op == runtime.OpIn {
								q = q.Where(entActor.KindIn(vals...))
							} else {
								q = q.Where(entActor.KindNotIn(vals...))
							}
						}
					}
				case "display_name":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entActor.DisplayNameEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entActor.DisplayNameNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entActor.DisplayNameContainsFold(f.Value))
					}
				case "stable_key":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entActor.StableKeyEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entActor.StableKeyNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entActor.StableKeyContainsFold(f.Value))
					}
				}
			}
			// Phase D — multi-column sort stack. Each Sort entry walks the
			// generated dispatch; unknown fields are silently skipped.
			if len(opts.Sort) > 0 {
				for _, k := range opts.Sort {
					switch k.Field {
					case "id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entActor.FieldID))
						} else {
							q = q.Order(ent.Desc(entActor.FieldID))
						}
					case "created_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entActor.FieldCreatedAt))
						} else {
							q = q.Order(ent.Desc(entActor.FieldCreatedAt))
						}
					case "updated_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entActor.FieldUpdatedAt))
						} else {
							q = q.Order(ent.Desc(entActor.FieldUpdatedAt))
						}
					case "kind":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entActor.FieldKind))
						} else {
							q = q.Order(ent.Desc(entActor.FieldKind))
						}
					case "display_name":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entActor.FieldDisplayName))
						} else {
							q = q.Order(ent.Desc(entActor.FieldDisplayName))
						}
					case "stable_key":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entActor.FieldStableKey))
						} else {
							q = q.Order(ent.Desc(entActor.FieldStableKey))
						}
					case "last_seen_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entActor.FieldLastSeenAt))
						} else {
							q = q.Order(ent.Desc(entActor.FieldLastSeenAt))
						}
					}
				}
			}
			total, err := q.Clone().Count(ctx)
			if err != nil {
				return nil, 0, err
			}
			rows, err := q.Offset(opts.Offset).Limit(opts.Limit).All(ctx)
			return rows, total, err
		},

		// Ent-native JSON for the `J` clipboard shortcut. *ent.Actor
		// implements MarshalJSON so eager-loaded edges (from With*())
		// land in the output under `edges` automatically.
		JSON: func(r *ent.Actor) ([]byte, error) { return json.Marshal(r) },

		Columns: []runtime.Column[*ent.Actor]{
			{
				Key:        "id",
				Label:      "Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Actor) string {
					return r.ID
				},
			},
			{
				Key:        "created_at",
				Label:      "Created At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Actor) string {
					if r.CreatedAt.IsZero() {
						return ""
					}
					return r.CreatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "updated_at",
				Label:      "Updated At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Actor) string {
					if r.UpdatedAt.IsZero() {
						return ""
					}
					return r.UpdatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "kind",
				Label:      "Kind",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				EnumValues: []string{
					"human",
					"agent",
					"hook",
					"plugin",
					"cron",
					"system",
				},
				Get: func(r *ent.Actor) string {
					return string(r.Kind)
				},
			},
			{
				Key:        "display_name",
				Label:      "Display Name",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Actor) string {
					return r.DisplayName
				},
			},
			{
				Key:        "stable_key",
				Label:      "Stable Key",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Actor) string {
					return r.StableKey
				},
			},
			{
				Key:        "last_seen_at",
				Label:      "Last Seen At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Actor) string {
					if r.LastSeenAt.IsZero() {
						return ""
					}
					return r.LastSeenAt.Format("2006-01-02 15:04:05")
				},
			},
		},

		Edges: []runtime.EdgeSpec[*ent.Actor]{
			{
				Name: "created_memories", Display: "Memories", Kind: runtime.EdgeDrill, Trigger: "c",
				// Count is emitted for BOTH upward and drill edges. For
				// upward edges it returns 0 or 1 (parent exists / doesn't).
				// For drill edges, the child row count.
				Count: func(ctx context.Context, r *ent.Actor) (int, error) {
					return client.Actor.QueryCreatedMemories(r).Count(ctx)
				},
				ResolveDrill: func(ctx context.Context, r *ent.Actor) (runtime.EntityRefList, error) {
					ids, err := client.Actor.QueryCreatedMemories(r).IDs(ctx)
					if err != nil {
						return runtime.EntityRefList{}, err
					}
					sids := make([]string, len(ids))
					for i, v := range ids {
						sids[i] = fmt.Sprint(v)
					}
					return runtime.EntityRefList{Kind: "memory", IDs: sids}, nil
				},
			},
			{
				Name: "validated_memories", Display: "Memories", Kind: runtime.EdgeDrill, Trigger: "a",
				// Count is emitted for BOTH upward and drill edges. For
				// upward edges it returns 0 or 1 (parent exists / doesn't).
				// For drill edges, the child row count.
				Count: func(ctx context.Context, r *ent.Actor) (int, error) {
					return client.Actor.QueryValidatedMemories(r).Count(ctx)
				},
				ResolveDrill: func(ctx context.Context, r *ent.Actor) (runtime.EntityRefList, error) {
					ids, err := client.Actor.QueryValidatedMemories(r).IDs(ctx)
					if err != nil {
						return runtime.EntityRefList{}, err
					}
					sids := make([]string, len(ids))
					for i, v := range ids {
						sids[i] = fmt.Sprint(v)
					}
					return runtime.EntityRefList{Kind: "memory", IDs: sids}, nil
				},
			},
		},
	})
}
