// Code generated by enttui. DO NOT EDIT.

package tuigen

import (
	"context"
	"dbent/gen/ent"
	entSuggestion "dbent/gen/ent/suggestion"
	"encoding/json"

	"github.com/khanakia/entx/enttui/runtime"
)

// registerSuggestion wires *ent.Suggestion into the enttui runtime.
//
// Scope filtering: for every scope key configured in enttui.Config.ScopeFields
// that exists on this schema, the Fetch closure below reads opts.Scope[key]
// and applies a predicate when set. Caller drives this via app.SetScope(key, value).
func registerSuggestion(app *runtime.App, client *ent.Client) {
	runtime.Register(app, runtime.EntitySpec[*ent.Suggestion]{
		Kind:           "suggestion",
		Display:        "Suggestions",
		Group:          "data",
		Icon:           "•",
		LabelKey:       "title",
		BodyKey:        "body",
		IDKey:          "id",
		PageSize:       200,
		MultiSort:      true,
		ShowEdgeCounts: true,
		AllowBulkCopy:  false,
		AllowExport:    false,
		Default: runtime.DefaultView{
			SortField: "created_at",
			SortDir:   runtime.Desc,
			Mode:      "",
		},

		Fetch: func(ctx context.Context, opts runtime.ListOpts) ([]*ent.Suggestion, int, error) {
			q := client.Suggestion.Query()
			// Scope predicate — keyed generically via ListOpts.Scope so the
			// runtime stays decoupled from any specific field name.
			if v := opts.Scope["project_id"]; v != "" {
				q = q.Where(entSuggestion.ProjectID(v))
			}
			// Legacy substring filter — used by the list+preview browser's
			// global `/` prompt. Phase E (Filters slice) supersedes this
			// in the table view but both can coexist.
			if opts.Filter != "" {
				q = q.Where(entSuggestion.Or(
					entSuggestion.IDContainsFold(opts.Filter),
					entSuggestion.ProjectIDContainsFold(opts.Filter),
					entSuggestion.TitleContainsFold(opts.Filter),
					entSuggestion.StatusStrContainsFold(opts.Filter),
					entSuggestion.CreatedByActorIDContainsFold(opts.Filter),
				))
			}
			// Phase E — structured per-column filters. AND-composed.
			// Unsupported operators for a given field type fall through
			// silently rather than erroring — keeps the UI forgiving.
			for _, f := range opts.Filters {
				switch f.Field {
				case "id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entSuggestion.IDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entSuggestion.IDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entSuggestion.IDContainsFold(f.Value))
					}
				case "project_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entSuggestion.ProjectIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entSuggestion.ProjectIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entSuggestion.ProjectIDContainsFold(f.Value))
					}
				case "title":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entSuggestion.TitleEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entSuggestion.TitleNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entSuggestion.TitleContainsFold(f.Value))
					}
				case "status_str":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entSuggestion.StatusStrEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entSuggestion.StatusStrNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entSuggestion.StatusStrContainsFold(f.Value))
					}
				case "created_by_actor_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entSuggestion.CreatedByActorIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entSuggestion.CreatedByActorIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entSuggestion.CreatedByActorIDContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entSuggestion.CreatedByActorIDIsNil())
					case runtime.OpNotNull:
						q = q.Where(entSuggestion.CreatedByActorIDNotNil())
					}
				}
			}
			// Phase D — multi-column sort stack. Each Sort entry walks the
			// generated dispatch; unknown fields are silently skipped.
			if len(opts.Sort) > 0 {
				for _, k := range opts.Sort {
					switch k.Field {
					case "id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entSuggestion.FieldID))
						} else {
							q = q.Order(ent.Desc(entSuggestion.FieldID))
						}
					case "created_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entSuggestion.FieldCreatedAt))
						} else {
							q = q.Order(ent.Desc(entSuggestion.FieldCreatedAt))
						}
					case "updated_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entSuggestion.FieldUpdatedAt))
						} else {
							q = q.Order(ent.Desc(entSuggestion.FieldUpdatedAt))
						}
					case "project_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entSuggestion.FieldProjectID))
						} else {
							q = q.Order(ent.Desc(entSuggestion.FieldProjectID))
						}
					case "title":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entSuggestion.FieldTitle))
						} else {
							q = q.Order(ent.Desc(entSuggestion.FieldTitle))
						}
					case "status_str":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entSuggestion.FieldStatusStr))
						} else {
							q = q.Order(ent.Desc(entSuggestion.FieldStatusStr))
						}
					case "created_by_actor_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entSuggestion.FieldCreatedByActorID))
						} else {
							q = q.Order(ent.Desc(entSuggestion.FieldCreatedByActorID))
						}
					}
				}
			}
			total, err := q.Clone().Count(ctx)
			if err != nil {
				return nil, 0, err
			}
			rows, err := q.Offset(opts.Offset).Limit(opts.Limit).All(ctx)
			return rows, total, err
		},

		// Ent-native JSON for the `J` clipboard shortcut. *ent.Suggestion
		// implements MarshalJSON so eager-loaded edges (from With*())
		// land in the output under `edges` automatically.
		JSON: func(r *ent.Suggestion) ([]byte, error) { return json.Marshal(r) },

		Columns: []runtime.Column[*ent.Suggestion]{
			{
				Key:        "id",
				Label:      "Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Suggestion) string {
					return r.ID
				},
			},
			{
				Key:        "created_at",
				Label:      "Created At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Suggestion) string {
					if r.CreatedAt.IsZero() {
						return ""
					}
					return r.CreatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "updated_at",
				Label:      "Updated At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Suggestion) string {
					if r.UpdatedAt.IsZero() {
						return ""
					}
					return r.UpdatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "project_id",
				Label:      "Project Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Suggestion) string {
					return r.ProjectID
				},
			},
			{
				Key:        "title",
				Label:      "Title",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Suggestion) string {
					return r.Title
				},
			},
			{
				Key:        "body",
				Label:      "Body",
				Sortable:   false,
				Filterable: false,
				Hidden:     true,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Suggestion) string {
					return r.Body
				},
			},
			{
				Key:        "status_str",
				Label:      "Status Str",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Suggestion) string {
					return r.StatusStr
				},
			},
			{
				Key:        "created_by_actor_id",
				Label:      "Created By Actor Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Suggestion) string {
					if r.CreatedByActorID == nil {
						return ""
					}
					return *r.CreatedByActorID
				},
			},
		},
	})
}
