// Code generated by enttui. DO NOT EDIT.

package tuigen

import (
	"context"
	"dbent/gen/ent"
	entRuleVerifierRef "dbent/gen/ent/ruleverifierref"
	"encoding/json"
	"strings"

	"github.com/khanakia/entx/enttui/runtime"
)

// registerRuleVerifierRef wires *ent.RuleVerifierRef into the enttui runtime.
//
// Scope filtering: for every scope key configured in enttui.Config.ScopeFields
// that exists on this schema, the Fetch closure below reads opts.Scope[key]
// and applies a predicate when set. Caller drives this via app.SetScope(key, value).
func registerRuleVerifierRef(app *runtime.App, client *ent.Client) {
	runtime.Register(app, runtime.EntitySpec[*ent.RuleVerifierRef]{
		Kind:           "ruleverifierref",
		Display:        "RuleVerifierRefs",
		Group:          "data",
		Icon:           "•",
		LabelKey:       "id",
		BodyKey:        "",
		IDKey:          "id",
		PageSize:       200,
		MultiSort:      true,
		ShowEdgeCounts: true,
		AllowBulkCopy:  false,
		AllowExport:    false,
		Default: runtime.DefaultView{
			SortField: "created_at",
			SortDir:   runtime.Desc,
			Mode:      "",
		},

		Fetch: func(ctx context.Context, opts runtime.ListOpts) ([]*ent.RuleVerifierRef, int, error) {
			q := client.RuleVerifierRef.Query()
			// Legacy substring filter — used by the list+preview browser's
			// global `/` prompt. Phase E (Filters slice) supersedes this
			// in the table view but both can coexist.
			if opts.Filter != "" {
				q = q.Where(entRuleVerifierRef.Or(
					entRuleVerifierRef.IDContainsFold(opts.Filter),
					entRuleVerifierRef.RuleIDContainsFold(opts.Filter),
					entRuleVerifierRef.VerifierRefContainsFold(opts.Filter),
					entRuleVerifierRef.NotesContainsFold(opts.Filter),
				))
			}
			// Phase E — structured per-column filters. AND-composed.
			// Unsupported operators for a given field type fall through
			// silently rather than erroring — keeps the UI forgiving.
			for _, f := range opts.Filters {
				switch f.Field {
				case "id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entRuleVerifierRef.IDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entRuleVerifierRef.IDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entRuleVerifierRef.IDContainsFold(f.Value))
					}
				case "rule_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entRuleVerifierRef.RuleIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entRuleVerifierRef.RuleIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entRuleVerifierRef.RuleIDContainsFold(f.Value))
					}
				case "verifier_kind":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entRuleVerifierRef.VerifierKindEQ(entRuleVerifierRef.VerifierKind(f.Value)))
					case runtime.OpNeq:
						q = q.Where(entRuleVerifierRef.VerifierKindNEQ(entRuleVerifierRef.VerifierKind(f.Value)))
					case runtime.OpIn, runtime.OpNotIn:
						// Multi-select: condition value is a "|"-joined
						// list of enum strings. Empty entries are dropped.
						parts := strings.Split(f.Value, "|")
						vals := make([]entRuleVerifierRef.VerifierKind, 0, len(parts))
						for _, p := range parts {
							if p == "" {
								continue
							}
							vals = append(vals, entRuleVerifierRef.VerifierKind(p))
						}
						if len(vals) > 0 {
							if f.Op == runtime.OpIn {
								q = q.Where(entRuleVerifierRef.VerifierKindIn(vals...))
							} else {
								q = q.Where(entRuleVerifierRef.VerifierKindNotIn(vals...))
							}
						}
					}
				case "verifier_ref":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entRuleVerifierRef.VerifierRefEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entRuleVerifierRef.VerifierRefNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entRuleVerifierRef.VerifierRefContainsFold(f.Value))
					}
				case "notes":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entRuleVerifierRef.NotesEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entRuleVerifierRef.NotesNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entRuleVerifierRef.NotesContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entRuleVerifierRef.NotesIsNil())
					case runtime.OpNotNull:
						q = q.Where(entRuleVerifierRef.NotesNotNil())
					}
				}
			}
			// Phase D — multi-column sort stack. Each Sort entry walks the
			// generated dispatch; unknown fields are silently skipped.
			if len(opts.Sort) > 0 {
				for _, k := range opts.Sort {
					switch k.Field {
					case "id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entRuleVerifierRef.FieldID))
						} else {
							q = q.Order(ent.Desc(entRuleVerifierRef.FieldID))
						}
					case "created_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entRuleVerifierRef.FieldCreatedAt))
						} else {
							q = q.Order(ent.Desc(entRuleVerifierRef.FieldCreatedAt))
						}
					case "updated_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entRuleVerifierRef.FieldUpdatedAt))
						} else {
							q = q.Order(ent.Desc(entRuleVerifierRef.FieldUpdatedAt))
						}
					case "rule_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entRuleVerifierRef.FieldRuleID))
						} else {
							q = q.Order(ent.Desc(entRuleVerifierRef.FieldRuleID))
						}
					case "verifier_kind":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entRuleVerifierRef.FieldVerifierKind))
						} else {
							q = q.Order(ent.Desc(entRuleVerifierRef.FieldVerifierKind))
						}
					case "verifier_ref":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entRuleVerifierRef.FieldVerifierRef))
						} else {
							q = q.Order(ent.Desc(entRuleVerifierRef.FieldVerifierRef))
						}
					case "notes":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entRuleVerifierRef.FieldNotes))
						} else {
							q = q.Order(ent.Desc(entRuleVerifierRef.FieldNotes))
						}
					}
				}
			}
			total, err := q.Clone().Count(ctx)
			if err != nil {
				return nil, 0, err
			}
			rows, err := q.Offset(opts.Offset).Limit(opts.Limit).All(ctx)
			return rows, total, err
		},

		// Ent-native JSON for the `J` clipboard shortcut. *ent.RuleVerifierRef
		// implements MarshalJSON so eager-loaded edges (from With*())
		// land in the output under `edges` automatically.
		JSON: func(r *ent.RuleVerifierRef) ([]byte, error) { return json.Marshal(r) },

		Columns: []runtime.Column[*ent.RuleVerifierRef]{
			{
				Key:        "id",
				Label:      "Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.RuleVerifierRef) string {
					return r.ID
				},
			},
			{
				Key:        "created_at",
				Label:      "Created At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.RuleVerifierRef) string {
					if r.CreatedAt.IsZero() {
						return ""
					}
					return r.CreatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "updated_at",
				Label:      "Updated At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.RuleVerifierRef) string {
					if r.UpdatedAt.IsZero() {
						return ""
					}
					return r.UpdatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "rule_id",
				Label:      "Rule Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.RuleVerifierRef) string {
					return r.RuleID
				},
			},
			{
				Key:        "verifier_kind",
				Label:      "Verifier Kind",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				EnumValues: []string{
					"regex",
					"shell",
					"go-fn",
					"custom",
				},
				Get: func(r *ent.RuleVerifierRef) string {
					return string(r.VerifierKind)
				},
			},
			{
				Key:        "verifier_ref",
				Label:      "Verifier Ref",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.RuleVerifierRef) string {
					return r.VerifierRef
				},
			},
			{
				Key:        "notes",
				Label:      "Notes",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.RuleVerifierRef) string {
					if r.Notes == nil {
						return ""
					}
					return *r.Notes
				},
			},
		},
	})
}
