// Code generated by enttui. DO NOT EDIT.

package tuigen

import (
	"context"
	"dbent/gen/ent"
	entEntityTag "dbent/gen/ent/entitytag"
	"encoding/json"

	"github.com/khanakia/entx/enttui/runtime"
)

// registerEntityTag wires *ent.EntityTag into the enttui runtime.
//
// Scope filtering: for every scope key configured in enttui.Config.ScopeFields
// that exists on this schema, the Fetch closure below reads opts.Scope[key]
// and applies a predicate when set. Caller drives this via app.SetScope(key, value).
func registerEntityTag(app *runtime.App, client *ent.Client) {
	runtime.Register(app, runtime.EntitySpec[*ent.EntityTag]{
		Kind:           "entitytag",
		Display:        "EntityTags",
		Group:          "data",
		Icon:           "•",
		LabelKey:       "id",
		BodyKey:        "",
		IDKey:          "id",
		PageSize:       200,
		MultiSort:      true,
		ShowEdgeCounts: true,
		AllowBulkCopy:  false,
		AllowExport:    false,
		Default: runtime.DefaultView{
			SortField: "created_at",
			SortDir:   runtime.Desc,
			Mode:      "",
		},

		Fetch: func(ctx context.Context, opts runtime.ListOpts) ([]*ent.EntityTag, int, error) {
			q := client.EntityTag.Query()
			// Legacy substring filter — used by the list+preview browser's
			// global `/` prompt. Phase E (Filters slice) supersedes this
			// in the table view but both can coexist.
			if opts.Filter != "" {
				q = q.Where(entEntityTag.Or(
					entEntityTag.IDContainsFold(opts.Filter),
					entEntityTag.EntityTableContainsFold(opts.Filter),
					entEntityTag.EntityIDContainsFold(opts.Filter),
					entEntityTag.TagIDContainsFold(opts.Filter),
				))
			}
			// Phase E — structured per-column filters. AND-composed.
			// Unsupported operators for a given field type fall through
			// silently rather than erroring — keeps the UI forgiving.
			for _, f := range opts.Filters {
				switch f.Field {
				case "id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entEntityTag.IDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entEntityTag.IDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entEntityTag.IDContainsFold(f.Value))
					}
				case "entity_table":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entEntityTag.EntityTableEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entEntityTag.EntityTableNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entEntityTag.EntityTableContainsFold(f.Value))
					}
				case "entity_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entEntityTag.EntityIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entEntityTag.EntityIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entEntityTag.EntityIDContainsFold(f.Value))
					}
				case "tag_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entEntityTag.TagIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entEntityTag.TagIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entEntityTag.TagIDContainsFold(f.Value))
					}
				}
			}
			// Phase D — multi-column sort stack. Each Sort entry walks the
			// generated dispatch; unknown fields are silently skipped.
			if len(opts.Sort) > 0 {
				for _, k := range opts.Sort {
					switch k.Field {
					case "id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entEntityTag.FieldID))
						} else {
							q = q.Order(ent.Desc(entEntityTag.FieldID))
						}
					case "created_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entEntityTag.FieldCreatedAt))
						} else {
							q = q.Order(ent.Desc(entEntityTag.FieldCreatedAt))
						}
					case "updated_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entEntityTag.FieldUpdatedAt))
						} else {
							q = q.Order(ent.Desc(entEntityTag.FieldUpdatedAt))
						}
					case "entity_table":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entEntityTag.FieldEntityTable))
						} else {
							q = q.Order(ent.Desc(entEntityTag.FieldEntityTable))
						}
					case "entity_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entEntityTag.FieldEntityID))
						} else {
							q = q.Order(ent.Desc(entEntityTag.FieldEntityID))
						}
					case "tag_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entEntityTag.FieldTagID))
						} else {
							q = q.Order(ent.Desc(entEntityTag.FieldTagID))
						}
					}
				}
			}
			total, err := q.Clone().Count(ctx)
			if err != nil {
				return nil, 0, err
			}
			rows, err := q.Offset(opts.Offset).Limit(opts.Limit).All(ctx)
			return rows, total, err
		},

		// Ent-native JSON for the `J` clipboard shortcut. *ent.EntityTag
		// implements MarshalJSON so eager-loaded edges (from With*())
		// land in the output under `edges` automatically.
		JSON: func(r *ent.EntityTag) ([]byte, error) { return json.Marshal(r) },

		Columns: []runtime.Column[*ent.EntityTag]{
			{
				Key:        "id",
				Label:      "Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.EntityTag) string {
					return r.ID
				},
			},
			{
				Key:        "created_at",
				Label:      "Created At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.EntityTag) string {
					if r.CreatedAt.IsZero() {
						return ""
					}
					return r.CreatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "updated_at",
				Label:      "Updated At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.EntityTag) string {
					if r.UpdatedAt.IsZero() {
						return ""
					}
					return r.UpdatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "entity_table",
				Label:      "Entity Table",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.EntityTag) string {
					return r.EntityTable
				},
			},
			{
				Key:        "entity_id",
				Label:      "Entity Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.EntityTag) string {
					return r.EntityID
				},
			},
			{
				Key:        "tag_id",
				Label:      "Tag Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.EntityTag) string {
					return r.TagID
				},
			},
		},
	})
}
