// Code generated by enttui. DO NOT EDIT.

package tuigen

import (
	"context"
	"dbent/gen/ent"
	entArchitectureNote "dbent/gen/ent/architecturenote"
	"encoding/json"

	"github.com/khanakia/entx/enttui/runtime"
)

// registerArchitectureNote wires *ent.ArchitectureNote into the enttui runtime.
//
// Scope filtering: for every scope key configured in enttui.Config.ScopeFields
// that exists on this schema, the Fetch closure below reads opts.Scope[key]
// and applies a predicate when set. Caller drives this via app.SetScope(key, value).
func registerArchitectureNote(app *runtime.App, client *ent.Client) {
	runtime.Register(app, runtime.EntitySpec[*ent.ArchitectureNote]{
		Kind:           "architecturenote",
		Display:        "ArchitectureNotes",
		Group:          "data",
		Icon:           "•",
		LabelKey:       "title",
		BodyKey:        "body",
		IDKey:          "id",
		PageSize:       200,
		MultiSort:      true,
		ShowEdgeCounts: true,
		AllowBulkCopy:  false,
		AllowExport:    false,
		Default: runtime.DefaultView{
			SortField: "created_at",
			SortDir:   runtime.Desc,
			Mode:      "",
		},

		Fetch: func(ctx context.Context, opts runtime.ListOpts) ([]*ent.ArchitectureNote, int, error) {
			q := client.ArchitectureNote.Query()
			// Scope predicate — keyed generically via ListOpts.Scope so the
			// runtime stays decoupled from any specific field name.
			if v := opts.Scope["project_id"]; v != "" {
				q = q.Where(entArchitectureNote.ProjectID(v))
			}
			// Legacy substring filter — used by the list+preview browser's
			// global `/` prompt. Phase E (Filters slice) supersedes this
			// in the table view but both can coexist.
			if opts.Filter != "" {
				q = q.Where(entArchitectureNote.Or(
					entArchitectureNote.IDContainsFold(opts.Filter),
					entArchitectureNote.ProjectIDContainsFold(opts.Filter),
					entArchitectureNote.RepoIDContainsFold(opts.Filter),
					entArchitectureNote.TitleContainsFold(opts.Filter),
					entArchitectureNote.BodyContainsFold(opts.Filter),
					entArchitectureNote.CreatedByActorIDContainsFold(opts.Filter),
				))
			}
			// Phase E — structured per-column filters. AND-composed.
			// Unsupported operators for a given field type fall through
			// silently rather than erroring — keeps the UI forgiving.
			for _, f := range opts.Filters {
				switch f.Field {
				case "id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entArchitectureNote.IDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entArchitectureNote.IDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entArchitectureNote.IDContainsFold(f.Value))
					}
				case "project_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entArchitectureNote.ProjectIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entArchitectureNote.ProjectIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entArchitectureNote.ProjectIDContainsFold(f.Value))
					}
				case "repo_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entArchitectureNote.RepoIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entArchitectureNote.RepoIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entArchitectureNote.RepoIDContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entArchitectureNote.RepoIDIsNil())
					case runtime.OpNotNull:
						q = q.Where(entArchitectureNote.RepoIDNotNil())
					}
				case "title":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entArchitectureNote.TitleEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entArchitectureNote.TitleNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entArchitectureNote.TitleContainsFold(f.Value))
					}
				case "body":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entArchitectureNote.BodyEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entArchitectureNote.BodyNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entArchitectureNote.BodyContainsFold(f.Value))
					}
				case "created_by_actor_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entArchitectureNote.CreatedByActorIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entArchitectureNote.CreatedByActorIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entArchitectureNote.CreatedByActorIDContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entArchitectureNote.CreatedByActorIDIsNil())
					case runtime.OpNotNull:
						q = q.Where(entArchitectureNote.CreatedByActorIDNotNil())
					}
				}
			}
			// Phase D — multi-column sort stack. Each Sort entry walks the
			// generated dispatch; unknown fields are silently skipped.
			if len(opts.Sort) > 0 {
				for _, k := range opts.Sort {
					switch k.Field {
					case "id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entArchitectureNote.FieldID))
						} else {
							q = q.Order(ent.Desc(entArchitectureNote.FieldID))
						}
					case "created_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entArchitectureNote.FieldCreatedAt))
						} else {
							q = q.Order(ent.Desc(entArchitectureNote.FieldCreatedAt))
						}
					case "updated_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entArchitectureNote.FieldUpdatedAt))
						} else {
							q = q.Order(ent.Desc(entArchitectureNote.FieldUpdatedAt))
						}
					case "project_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entArchitectureNote.FieldProjectID))
						} else {
							q = q.Order(ent.Desc(entArchitectureNote.FieldProjectID))
						}
					case "repo_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entArchitectureNote.FieldRepoID))
						} else {
							q = q.Order(ent.Desc(entArchitectureNote.FieldRepoID))
						}
					case "title":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entArchitectureNote.FieldTitle))
						} else {
							q = q.Order(ent.Desc(entArchitectureNote.FieldTitle))
						}
					case "created_by_actor_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entArchitectureNote.FieldCreatedByActorID))
						} else {
							q = q.Order(ent.Desc(entArchitectureNote.FieldCreatedByActorID))
						}
					}
				}
			}
			total, err := q.Clone().Count(ctx)
			if err != nil {
				return nil, 0, err
			}
			rows, err := q.Offset(opts.Offset).Limit(opts.Limit).All(ctx)
			return rows, total, err
		},

		// Ent-native JSON for the `J` clipboard shortcut. *ent.ArchitectureNote
		// implements MarshalJSON so eager-loaded edges (from With*())
		// land in the output under `edges` automatically.
		JSON: func(r *ent.ArchitectureNote) ([]byte, error) { return json.Marshal(r) },

		Columns: []runtime.Column[*ent.ArchitectureNote]{
			{
				Key:        "id",
				Label:      "Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.ArchitectureNote) string {
					return r.ID
				},
			},
			{
				Key:        "created_at",
				Label:      "Created At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.ArchitectureNote) string {
					if r.CreatedAt.IsZero() {
						return ""
					}
					return r.CreatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "updated_at",
				Label:      "Updated At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.ArchitectureNote) string {
					if r.UpdatedAt.IsZero() {
						return ""
					}
					return r.UpdatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "project_id",
				Label:      "Project Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.ArchitectureNote) string {
					return r.ProjectID
				},
			},
			{
				Key:        "repo_id",
				Label:      "Repo Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.ArchitectureNote) string {
					if r.RepoID == nil {
						return ""
					}
					return *r.RepoID
				},
			},
			{
				Key:        "title",
				Label:      "Title",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.ArchitectureNote) string {
					return r.Title
				},
			},
			{
				Key:        "body",
				Label:      "Body",
				Sortable:   false,
				Filterable: true,
				Hidden:     true,
				Width:      0,
				Align:      "",
				Get: func(r *ent.ArchitectureNote) string {
					return r.Body
				},
			},
			{
				Key:        "created_by_actor_id",
				Label:      "Created By Actor Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.ArchitectureNote) string {
					if r.CreatedByActorID == nil {
						return ""
					}
					return *r.CreatedByActorID
				},
			},
		},
	})
}
