// Code generated by enttui. DO NOT EDIT.

package tuigen

import (
	"context"
	"dbent/gen/ent"
	entDBConfig "dbent/gen/ent/dbconfig"
	"encoding/json"

	"github.com/khanakia/entx/enttui/runtime"
)

// registerDBConfig wires *ent.DBConfig into the enttui runtime.
//
// Scope filtering: for every scope key configured in enttui.Config.ScopeFields
// that exists on this schema, the Fetch closure below reads opts.Scope[key]
// and applies a predicate when set. Caller drives this via app.SetScope(key, value).
func registerDBConfig(app *runtime.App, client *ent.Client) {
	runtime.Register(app, runtime.EntitySpec[*ent.DBConfig]{
		Kind:           "dbconfig",
		Display:        "DBConfigs",
		Group:          "data",
		Icon:           "•",
		LabelKey:       "id",
		BodyKey:        "",
		IDKey:          "id",
		PageSize:       200,
		MultiSort:      true,
		ShowEdgeCounts: true,
		AllowBulkCopy:  false,
		AllowExport:    false,
		Default: runtime.DefaultView{
			SortField: "created_at",
			SortDir:   runtime.Desc,
			Mode:      "",
		},

		Fetch: func(ctx context.Context, opts runtime.ListOpts) ([]*ent.DBConfig, int, error) {
			q := client.DBConfig.Query()
			// Legacy substring filter — used by the list+preview browser's
			// global `/` prompt. Phase E (Filters slice) supersedes this
			// in the table view but both can coexist.
			if opts.Filter != "" {
				q = q.Where(entDBConfig.Or(
					entDBConfig.IDContainsFold(opts.Filter),
					entDBConfig.KeyContainsFold(opts.Filter),
					entDBConfig.ValueContainsFold(opts.Filter),
				))
			}
			// Phase E — structured per-column filters. AND-composed.
			// Unsupported operators for a given field type fall through
			// silently rather than erroring — keeps the UI forgiving.
			for _, f := range opts.Filters {
				switch f.Field {
				case "id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entDBConfig.IDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entDBConfig.IDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entDBConfig.IDContainsFold(f.Value))
					}
				case "key":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entDBConfig.KeyEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entDBConfig.KeyNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entDBConfig.KeyContainsFold(f.Value))
					}
				case "value":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entDBConfig.ValueEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entDBConfig.ValueNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entDBConfig.ValueContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entDBConfig.ValueIsNil())
					case runtime.OpNotNull:
						q = q.Where(entDBConfig.ValueNotNil())
					}
				}
			}
			// Phase D — multi-column sort stack. Each Sort entry walks the
			// generated dispatch; unknown fields are silently skipped.
			if len(opts.Sort) > 0 {
				for _, k := range opts.Sort {
					switch k.Field {
					case "id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entDBConfig.FieldID))
						} else {
							q = q.Order(ent.Desc(entDBConfig.FieldID))
						}
					case "created_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entDBConfig.FieldCreatedAt))
						} else {
							q = q.Order(ent.Desc(entDBConfig.FieldCreatedAt))
						}
					case "updated_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entDBConfig.FieldUpdatedAt))
						} else {
							q = q.Order(ent.Desc(entDBConfig.FieldUpdatedAt))
						}
					case "key":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entDBConfig.FieldKey))
						} else {
							q = q.Order(ent.Desc(entDBConfig.FieldKey))
						}
					case "value":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entDBConfig.FieldValue))
						} else {
							q = q.Order(ent.Desc(entDBConfig.FieldValue))
						}
					case "setting_updated_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entDBConfig.FieldSettingUpdatedAt))
						} else {
							q = q.Order(ent.Desc(entDBConfig.FieldSettingUpdatedAt))
						}
					}
				}
			}
			total, err := q.Clone().Count(ctx)
			if err != nil {
				return nil, 0, err
			}
			rows, err := q.Offset(opts.Offset).Limit(opts.Limit).All(ctx)
			return rows, total, err
		},

		// Ent-native JSON for the `J` clipboard shortcut. *ent.DBConfig
		// implements MarshalJSON so eager-loaded edges (from With*())
		// land in the output under `edges` automatically.
		JSON: func(r *ent.DBConfig) ([]byte, error) { return json.Marshal(r) },

		Columns: []runtime.Column[*ent.DBConfig]{
			{
				Key:        "id",
				Label:      "Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.DBConfig) string {
					return r.ID
				},
			},
			{
				Key:        "created_at",
				Label:      "Created At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.DBConfig) string {
					if r.CreatedAt.IsZero() {
						return ""
					}
					return r.CreatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "updated_at",
				Label:      "Updated At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.DBConfig) string {
					if r.UpdatedAt.IsZero() {
						return ""
					}
					return r.UpdatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "key",
				Label:      "Key",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.DBConfig) string {
					return r.Key
				},
			},
			{
				Key:        "value",
				Label:      "Value",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.DBConfig) string {
					if r.Value == nil {
						return ""
					}
					return *r.Value
				},
			},
			{
				Key:        "setting_updated_at",
				Label:      "Setting Updated At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.DBConfig) string {
					if r.SettingUpdatedAt.IsZero() {
						return ""
					}
					return r.SettingUpdatedAt.Format("2006-01-02 15:04:05")
				},
			},
		},
	})
}
