// Code generated by enttui. DO NOT EDIT.

package tuigen

import (
	"context"
	"dbent/gen/ent"
	entActivityArchive "dbent/gen/ent/activityarchive"
	"encoding/json"

	"github.com/khanakia/entx/enttui/runtime"
)

// registerActivityArchive wires *ent.ActivityArchive into the enttui runtime.
//
// Scope filtering: for every scope key configured in enttui.Config.ScopeFields
// that exists on this schema, the Fetch closure below reads opts.Scope[key]
// and applies a predicate when set. Caller drives this via app.SetScope(key, value).
func registerActivityArchive(app *runtime.App, client *ent.Client) {
	runtime.Register(app, runtime.EntitySpec[*ent.ActivityArchive]{
		Kind:           "activityarchive",
		Display:        "ActivityArchives",
		Group:          "data",
		Icon:           "•",
		LabelKey:       "id",
		BodyKey:        "body",
		IDKey:          "id",
		PageSize:       200,
		MultiSort:      true,
		ShowEdgeCounts: true,
		AllowBulkCopy:  false,
		AllowExport:    false,
		Default: runtime.DefaultView{
			SortField: "created_at",
			SortDir:   runtime.Desc,
			Mode:      "",
		},

		Fetch: func(ctx context.Context, opts runtime.ListOpts) ([]*ent.ActivityArchive, int, error) {
			q := client.ActivityArchive.Query()
			// Scope predicate — keyed generically via ListOpts.Scope so the
			// runtime stays decoupled from any specific field name.
			if v := opts.Scope["project_id"]; v != "" {
				q = q.Where(entActivityArchive.ProjectID(v))
			}
			// Legacy substring filter — used by the list+preview browser's
			// global `/` prompt. Phase E (Filters slice) supersedes this
			// in the table view but both can coexist.
			if opts.Filter != "" {
				q = q.Where(entActivityArchive.Or(
					entActivityArchive.IDContainsFold(opts.Filter),
					entActivityArchive.ProjectIDContainsFold(opts.Filter),
					entActivityArchive.KindContainsFold(opts.Filter),
				))
			}
			// Phase E — structured per-column filters. AND-composed.
			// Unsupported operators for a given field type fall through
			// silently rather than erroring — keeps the UI forgiving.
			for _, f := range opts.Filters {
				switch f.Field {
				case "id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entActivityArchive.IDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entActivityArchive.IDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entActivityArchive.IDContainsFold(f.Value))
					}
				case "project_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entActivityArchive.ProjectIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entActivityArchive.ProjectIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entActivityArchive.ProjectIDContainsFold(f.Value))
					}
				case "kind":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entActivityArchive.KindEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entActivityArchive.KindNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entActivityArchive.KindContainsFold(f.Value))
					}
				}
			}
			// Phase D — multi-column sort stack. Each Sort entry walks the
			// generated dispatch; unknown fields are silently skipped.
			if len(opts.Sort) > 0 {
				for _, k := range opts.Sort {
					switch k.Field {
					case "id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entActivityArchive.FieldID))
						} else {
							q = q.Order(ent.Desc(entActivityArchive.FieldID))
						}
					case "created_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entActivityArchive.FieldCreatedAt))
						} else {
							q = q.Order(ent.Desc(entActivityArchive.FieldCreatedAt))
						}
					case "updated_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entActivityArchive.FieldUpdatedAt))
						} else {
							q = q.Order(ent.Desc(entActivityArchive.FieldUpdatedAt))
						}
					case "project_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entActivityArchive.FieldProjectID))
						} else {
							q = q.Order(ent.Desc(entActivityArchive.FieldProjectID))
						}
					case "kind":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entActivityArchive.FieldKind))
						} else {
							q = q.Order(ent.Desc(entActivityArchive.FieldKind))
						}
					case "archived_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entActivityArchive.FieldArchivedAt))
						} else {
							q = q.Order(ent.Desc(entActivityArchive.FieldArchivedAt))
						}
					}
				}
			}
			total, err := q.Clone().Count(ctx)
			if err != nil {
				return nil, 0, err
			}
			rows, err := q.Offset(opts.Offset).Limit(opts.Limit).All(ctx)
			return rows, total, err
		},

		// Ent-native JSON for the `J` clipboard shortcut. *ent.ActivityArchive
		// implements MarshalJSON so eager-loaded edges (from With*())
		// land in the output under `edges` automatically.
		JSON: func(r *ent.ActivityArchive) ([]byte, error) { return json.Marshal(r) },

		Columns: []runtime.Column[*ent.ActivityArchive]{
			{
				Key:        "id",
				Label:      "Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.ActivityArchive) string {
					return r.ID
				},
			},
			{
				Key:        "created_at",
				Label:      "Created At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.ActivityArchive) string {
					if r.CreatedAt.IsZero() {
						return ""
					}
					return r.CreatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "updated_at",
				Label:      "Updated At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.ActivityArchive) string {
					if r.UpdatedAt.IsZero() {
						return ""
					}
					return r.UpdatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "project_id",
				Label:      "Project Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.ActivityArchive) string {
					return r.ProjectID
				},
			},
			{
				Key:        "kind",
				Label:      "Kind",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.ActivityArchive) string {
					return r.Kind
				},
			},
			{
				Key:        "body",
				Label:      "Body",
				Sortable:   false,
				Filterable: false,
				Hidden:     true,
				Width:      0,
				Align:      "",
				Get: func(r *ent.ActivityArchive) string {
					if r.Body == nil {
						return ""
					}
					return *r.Body
				},
			},
			{
				Key:        "archived_at",
				Label:      "Archived At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.ActivityArchive) string {
					if r.ArchivedAt.IsZero() {
						return ""
					}
					return r.ArchivedAt.Format("2006-01-02 15:04:05")
				},
			},
		},
	})
}
