// Code generated by enttui. DO NOT EDIT.

package tuigen

import (
	"context"
	"dbent/gen/ent"
	entRenderHistory "dbent/gen/ent/renderhistory"
	"encoding/json"
	"fmt"

	"github.com/khanakia/entx/enttui/runtime"
)

// registerRenderHistory wires *ent.RenderHistory into the enttui runtime.
//
// Scope filtering: for every scope key configured in enttui.Config.ScopeFields
// that exists on this schema, the Fetch closure below reads opts.Scope[key]
// and applies a predicate when set. Caller drives this via app.SetScope(key, value).
func registerRenderHistory(app *runtime.App, client *ent.Client) {
	runtime.Register(app, runtime.EntitySpec[*ent.RenderHistory]{
		Kind:           "renderhistory",
		Display:        "RenderHistories",
		Group:          "data",
		Icon:           "•",
		LabelKey:       "id",
		BodyKey:        "",
		IDKey:          "id",
		PageSize:       200,
		MultiSort:      true,
		ShowEdgeCounts: true,
		AllowBulkCopy:  false,
		AllowExport:    false,
		Default: runtime.DefaultView{
			SortField: "created_at",
			SortDir:   runtime.Desc,
			Mode:      "",
		},

		Fetch: func(ctx context.Context, opts runtime.ListOpts) ([]*ent.RenderHistory, int, error) {
			q := client.RenderHistory.Query()
			// Scope predicate — keyed generically via ListOpts.Scope so the
			// runtime stays decoupled from any specific field name.
			if v := opts.Scope["project_id"]; v != "" {
				q = q.Where(entRenderHistory.ProjectID(v))
			}
			// Legacy substring filter — used by the list+preview browser's
			// global `/` prompt. Phase E (Filters slice) supersedes this
			// in the table view but both can coexist.
			if opts.Filter != "" {
				q = q.Where(entRenderHistory.Or(
					entRenderHistory.IDContainsFold(opts.Filter),
					entRenderHistory.ProjectIDContainsFold(opts.Filter),
					entRenderHistory.RepoIDContainsFold(opts.Filter),
					entRenderHistory.TargetPathContainsFold(opts.Filter),
					entRenderHistory.RenderedTextContainsFold(opts.Filter),
					entRenderHistory.RenderedSha256ContainsFold(opts.Filter),
					entRenderHistory.ScopeSummaryContainsFold(opts.Filter),
					entRenderHistory.RenderedByActorIDContainsFold(opts.Filter),
				))
			}
			// Phase E — structured per-column filters. AND-composed.
			// Unsupported operators for a given field type fall through
			// silently rather than erroring — keeps the UI forgiving.
			for _, f := range opts.Filters {
				switch f.Field {
				case "id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entRenderHistory.IDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entRenderHistory.IDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entRenderHistory.IDContainsFold(f.Value))
					}
				case "project_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entRenderHistory.ProjectIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entRenderHistory.ProjectIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entRenderHistory.ProjectIDContainsFold(f.Value))
					}
				case "repo_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entRenderHistory.RepoIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entRenderHistory.RepoIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entRenderHistory.RepoIDContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entRenderHistory.RepoIDIsNil())
					case runtime.OpNotNull:
						q = q.Where(entRenderHistory.RepoIDNotNil())
					}
				case "target_path":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entRenderHistory.TargetPathEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entRenderHistory.TargetPathNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entRenderHistory.TargetPathContainsFold(f.Value))
					}
				case "rendered_text":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entRenderHistory.RenderedTextEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entRenderHistory.RenderedTextNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entRenderHistory.RenderedTextContainsFold(f.Value))
					}
				case "rendered_sha256":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entRenderHistory.RenderedSha256EQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entRenderHistory.RenderedSha256NEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entRenderHistory.RenderedSha256ContainsFold(f.Value))
					}
				case "scope_summary":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entRenderHistory.ScopeSummaryEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entRenderHistory.ScopeSummaryNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entRenderHistory.ScopeSummaryContainsFold(f.Value))
					}
				case "rendered_by_actor_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entRenderHistory.RenderedByActorIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entRenderHistory.RenderedByActorIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entRenderHistory.RenderedByActorIDContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entRenderHistory.RenderedByActorIDIsNil())
					case runtime.OpNotNull:
						q = q.Where(entRenderHistory.RenderedByActorIDNotNil())
					}
				}
			}
			// Phase D — multi-column sort stack. Each Sort entry walks the
			// generated dispatch; unknown fields are silently skipped.
			if len(opts.Sort) > 0 {
				for _, k := range opts.Sort {
					switch k.Field {
					case "id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entRenderHistory.FieldID))
						} else {
							q = q.Order(ent.Desc(entRenderHistory.FieldID))
						}
					case "created_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entRenderHistory.FieldCreatedAt))
						} else {
							q = q.Order(ent.Desc(entRenderHistory.FieldCreatedAt))
						}
					case "updated_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entRenderHistory.FieldUpdatedAt))
						} else {
							q = q.Order(ent.Desc(entRenderHistory.FieldUpdatedAt))
						}
					case "project_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entRenderHistory.FieldProjectID))
						} else {
							q = q.Order(ent.Desc(entRenderHistory.FieldProjectID))
						}
					case "repo_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entRenderHistory.FieldRepoID))
						} else {
							q = q.Order(ent.Desc(entRenderHistory.FieldRepoID))
						}
					case "target_path":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entRenderHistory.FieldTargetPath))
						} else {
							q = q.Order(ent.Desc(entRenderHistory.FieldTargetPath))
						}
					case "rendered_text":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entRenderHistory.FieldRenderedText))
						} else {
							q = q.Order(ent.Desc(entRenderHistory.FieldRenderedText))
						}
					case "rendered_sha256":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entRenderHistory.FieldRenderedSha256))
						} else {
							q = q.Order(ent.Desc(entRenderHistory.FieldRenderedSha256))
						}
					case "scope_summary":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entRenderHistory.FieldScopeSummary))
						} else {
							q = q.Order(ent.Desc(entRenderHistory.FieldScopeSummary))
						}
					case "rendered_by_actor_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entRenderHistory.FieldRenderedByActorID))
						} else {
							q = q.Order(ent.Desc(entRenderHistory.FieldRenderedByActorID))
						}
					}
				}
			}
			total, err := q.Clone().Count(ctx)
			if err != nil {
				return nil, 0, err
			}
			rows, err := q.Offset(opts.Offset).Limit(opts.Limit).All(ctx)
			return rows, total, err
		},

		// Ent-native JSON for the `J` clipboard shortcut. *ent.RenderHistory
		// implements MarshalJSON so eager-loaded edges (from With*())
		// land in the output under `edges` automatically.
		JSON: func(r *ent.RenderHistory) ([]byte, error) { return json.Marshal(r) },

		Columns: []runtime.Column[*ent.RenderHistory]{
			{
				Key:        "id",
				Label:      "Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.RenderHistory) string {
					return r.ID
				},
			},
			{
				Key:        "created_at",
				Label:      "Created At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.RenderHistory) string {
					if r.CreatedAt.IsZero() {
						return ""
					}
					return r.CreatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "updated_at",
				Label:      "Updated At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.RenderHistory) string {
					if r.UpdatedAt.IsZero() {
						return ""
					}
					return r.UpdatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "project_id",
				Label:      "Project Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.RenderHistory) string {
					return r.ProjectID
				},
			},
			{
				Key:        "repo_id",
				Label:      "Repo Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.RenderHistory) string {
					if r.RepoID == nil {
						return ""
					}
					return *r.RepoID
				},
			},
			{
				Key:        "target_path",
				Label:      "Target Path",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.RenderHistory) string {
					return r.TargetPath
				},
			},
			{
				Key:        "rendered_text",
				Label:      "Rendered Text",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.RenderHistory) string {
					return r.RenderedText
				},
			},
			{
				Key:        "rendered_sha256",
				Label:      "Rendered Sha256",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.RenderHistory) string {
					return r.RenderedSha256
				},
			},
			{
				Key:        "total_bytes",
				Label:      "Total Bytes",
				Sortable:   false,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.RenderHistory) string {
					return fmt.Sprintf("%v", r.TotalBytes)
				},
			},
			{
				Key:        "total_tokens",
				Label:      "Total Tokens",
				Sortable:   false,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.RenderHistory) string {
					if r.TotalTokens == nil {
						return ""
					}
					return fmt.Sprintf("%v", *r.TotalTokens)
				},
			},
			{
				Key:        "scope_summary",
				Label:      "Scope Summary",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.RenderHistory) string {
					return r.ScopeSummary
				},
			},
			{
				Key:        "rendered_by_actor_id",
				Label:      "Rendered By Actor Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.RenderHistory) string {
					if r.RenderedByActorID == nil {
						return ""
					}
					return *r.RenderedByActorID
				},
			},
		},
	})
}
