// Code generated by enttui. DO NOT EDIT.

package tuigen

import (
	"context"
	"dbent/gen/ent"
	entPattern "dbent/gen/ent/pattern"
	"encoding/json"
	"fmt"

	"github.com/khanakia/entx/enttui/runtime"
)

// registerPattern wires *ent.Pattern into the enttui runtime.
//
// Scope filtering: for every scope key configured in enttui.Config.ScopeFields
// that exists on this schema, the Fetch closure below reads opts.Scope[key]
// and applies a predicate when set. Caller drives this via app.SetScope(key, value).
func registerPattern(app *runtime.App, client *ent.Client) {
	runtime.Register(app, runtime.EntitySpec[*ent.Pattern]{
		Kind:           "pattern",
		Display:        "Patterns",
		Group:          "data",
		Icon:           "•",
		LabelKey:       "title",
		BodyKey:        "body",
		IDKey:          "id",
		PageSize:       200,
		MultiSort:      true,
		ShowEdgeCounts: true,
		AllowBulkCopy:  false,
		AllowExport:    false,
		Default: runtime.DefaultView{
			SortField: "created_at",
			SortDir:   runtime.Desc,
			Mode:      "",
		},

		Fetch: func(ctx context.Context, opts runtime.ListOpts) ([]*ent.Pattern, int, error) {
			q := client.Pattern.Query()
			// Scope predicate — keyed generically via ListOpts.Scope so the
			// runtime stays decoupled from any specific field name.
			if v := opts.Scope["project_id"]; v != "" {
				q = q.Where(entPattern.ProjectID(v))
			}
			// Legacy substring filter — used by the list+preview browser's
			// global `/` prompt. Phase E (Filters slice) supersedes this
			// in the table view but both can coexist.
			if opts.Filter != "" {
				q = q.Where(entPattern.Or(
					entPattern.IDContainsFold(opts.Filter),
					entPattern.SourceKindContainsFold(opts.Filter),
					entPattern.SourceRefContainsFold(opts.Filter),
					entPattern.ProjectIDContainsFold(opts.Filter),
					entPattern.RepoIDContainsFold(opts.Filter),
					entPattern.TitleContainsFold(opts.Filter),
					entPattern.BodyContainsFold(opts.Filter),
					entPattern.LanguageContainsFold(opts.Filter),
					entPattern.SupersededByIDContainsFold(opts.Filter),
					entPattern.CreatedByActorIDContainsFold(opts.Filter),
				))
			}
			// Phase E — structured per-column filters. AND-composed.
			// Unsupported operators for a given field type fall through
			// silently rather than erroring — keeps the UI forgiving.
			for _, f := range opts.Filters {
				switch f.Field {
				case "id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entPattern.IDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entPattern.IDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entPattern.IDContainsFold(f.Value))
					}
				case "source_kind":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entPattern.SourceKindEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entPattern.SourceKindNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entPattern.SourceKindContainsFold(f.Value))
					}
				case "source_ref":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entPattern.SourceRefEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entPattern.SourceRefNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entPattern.SourceRefContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entPattern.SourceRefIsNil())
					case runtime.OpNotNull:
						q = q.Where(entPattern.SourceRefNotNil())
					}
				case "project_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entPattern.ProjectIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entPattern.ProjectIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entPattern.ProjectIDContainsFold(f.Value))
					}
				case "repo_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entPattern.RepoIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entPattern.RepoIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entPattern.RepoIDContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entPattern.RepoIDIsNil())
					case runtime.OpNotNull:
						q = q.Where(entPattern.RepoIDNotNil())
					}
				case "title":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entPattern.TitleEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entPattern.TitleNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entPattern.TitleContainsFold(f.Value))
					}
				case "body":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entPattern.BodyEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entPattern.BodyNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entPattern.BodyContainsFold(f.Value))
					}
				case "language":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entPattern.LanguageEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entPattern.LanguageNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entPattern.LanguageContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entPattern.LanguageIsNil())
					case runtime.OpNotNull:
						q = q.Where(entPattern.LanguageNotNil())
					}
				case "superseded_by_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entPattern.SupersededByIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entPattern.SupersededByIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entPattern.SupersededByIDContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entPattern.SupersededByIDIsNil())
					case runtime.OpNotNull:
						q = q.Where(entPattern.SupersededByIDNotNil())
					}
				case "created_by_actor_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entPattern.CreatedByActorIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entPattern.CreatedByActorIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entPattern.CreatedByActorIDContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entPattern.CreatedByActorIDIsNil())
					case runtime.OpNotNull:
						q = q.Where(entPattern.CreatedByActorIDNotNil())
					}
				}
			}
			// Phase D — multi-column sort stack. Each Sort entry walks the
			// generated dispatch; unknown fields are silently skipped.
			if len(opts.Sort) > 0 {
				for _, k := range opts.Sort {
					switch k.Field {
					case "id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entPattern.FieldID))
						} else {
							q = q.Order(ent.Desc(entPattern.FieldID))
						}
					case "created_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entPattern.FieldCreatedAt))
						} else {
							q = q.Order(ent.Desc(entPattern.FieldCreatedAt))
						}
					case "updated_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entPattern.FieldUpdatedAt))
						} else {
							q = q.Order(ent.Desc(entPattern.FieldUpdatedAt))
						}
					case "last_accessed_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entPattern.FieldLastAccessedAt))
						} else {
							q = q.Order(ent.Desc(entPattern.FieldLastAccessedAt))
						}
					case "last_validated_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entPattern.FieldLastValidatedAt))
						} else {
							q = q.Order(ent.Desc(entPattern.FieldLastValidatedAt))
						}
					case "archived_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entPattern.FieldArchivedAt))
						} else {
							q = q.Order(ent.Desc(entPattern.FieldArchivedAt))
						}
					case "source_kind":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entPattern.FieldSourceKind))
						} else {
							q = q.Order(ent.Desc(entPattern.FieldSourceKind))
						}
					case "source_ref":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entPattern.FieldSourceRef))
						} else {
							q = q.Order(ent.Desc(entPattern.FieldSourceRef))
						}
					case "project_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entPattern.FieldProjectID))
						} else {
							q = q.Order(ent.Desc(entPattern.FieldProjectID))
						}
					case "repo_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entPattern.FieldRepoID))
						} else {
							q = q.Order(ent.Desc(entPattern.FieldRepoID))
						}
					case "title":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entPattern.FieldTitle))
						} else {
							q = q.Order(ent.Desc(entPattern.FieldTitle))
						}
					case "language":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entPattern.FieldLanguage))
						} else {
							q = q.Order(ent.Desc(entPattern.FieldLanguage))
						}
					case "superseded_by_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entPattern.FieldSupersededByID))
						} else {
							q = q.Order(ent.Desc(entPattern.FieldSupersededByID))
						}
					case "created_by_actor_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entPattern.FieldCreatedByActorID))
						} else {
							q = q.Order(ent.Desc(entPattern.FieldCreatedByActorID))
						}
					}
				}
			}
			total, err := q.Clone().Count(ctx)
			if err != nil {
				return nil, 0, err
			}
			rows, err := q.Offset(opts.Offset).Limit(opts.Limit).All(ctx)
			return rows, total, err
		},

		// Ent-native JSON for the `J` clipboard shortcut. *ent.Pattern
		// implements MarshalJSON so eager-loaded edges (from With*())
		// land in the output under `edges` automatically.
		JSON: func(r *ent.Pattern) ([]byte, error) { return json.Marshal(r) },

		Columns: []runtime.Column[*ent.Pattern]{
			{
				Key:        "id",
				Label:      "Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Pattern) string {
					return r.ID
				},
			},
			{
				Key:        "created_at",
				Label:      "Created At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Pattern) string {
					if r.CreatedAt.IsZero() {
						return ""
					}
					return r.CreatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "updated_at",
				Label:      "Updated At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Pattern) string {
					if r.UpdatedAt.IsZero() {
						return ""
					}
					return r.UpdatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "trust_score",
				Label:      "Trust Score",
				Sortable:   false,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Pattern) string {
					return fmt.Sprintf("%v", r.TrustScore)
				},
			},
			{
				Key:        "confidence",
				Label:      "Confidence",
				Sortable:   false,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Pattern) string {
					if r.Confidence == nil {
						return ""
					}
					return fmt.Sprintf("%v", *r.Confidence)
				},
			},
			{
				Key:        "last_accessed_at",
				Label:      "Last Accessed At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Pattern) string {
					if r.LastAccessedAt == nil || r.LastAccessedAt.IsZero() {
						return ""
					}
					return r.LastAccessedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "last_validated_at",
				Label:      "Last Validated At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Pattern) string {
					if r.LastValidatedAt == nil || r.LastValidatedAt.IsZero() {
						return ""
					}
					return r.LastValidatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "archived_at",
				Label:      "Archived At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Pattern) string {
					if r.ArchivedAt == nil || r.ArchivedAt.IsZero() {
						return ""
					}
					return r.ArchivedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "source_kind",
				Label:      "Source Kind",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Pattern) string {
					return r.SourceKind
				},
			},
			{
				Key:        "source_ref",
				Label:      "Source Ref",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Pattern) string {
					if r.SourceRef == nil {
						return ""
					}
					return *r.SourceRef
				},
			},
			{
				Key:        "project_id",
				Label:      "Project Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Pattern) string {
					return r.ProjectID
				},
			},
			{
				Key:        "repo_id",
				Label:      "Repo Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Pattern) string {
					if r.RepoID == nil {
						return ""
					}
					return *r.RepoID
				},
			},
			{
				Key:        "title",
				Label:      "Title",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Pattern) string {
					return r.Title
				},
			},
			{
				Key:        "body",
				Label:      "Body",
				Sortable:   false,
				Filterable: true,
				Hidden:     true,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Pattern) string {
					return r.Body
				},
			},
			{
				Key:        "language",
				Label:      "Language",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Pattern) string {
					if r.Language == nil {
						return ""
					}
					return *r.Language
				},
			},
			{
				Key:        "superseded_by_id",
				Label:      "Superseded By Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Pattern) string {
					if r.SupersededByID == nil {
						return ""
					}
					return *r.SupersededByID
				},
			},
			{
				Key:        "created_by_actor_id",
				Label:      "Created By Actor Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Pattern) string {
					if r.CreatedByActorID == nil {
						return ""
					}
					return *r.CreatedByActorID
				},
			},
		},
	})
}
