// Code generated by enttui. DO NOT EDIT.

package tuigen

import (
	"context"
	"dbent/gen/ent"
	entTechDocPage "dbent/gen/ent/techdocpage"
	"encoding/json"
	"fmt"

	"github.com/khanakia/entx/enttui/runtime"
)

// registerTechDocPage wires *ent.TechDocPage into the enttui runtime.
//
// Scope filtering: for every scope key configured in enttui.Config.ScopeFields
// that exists on this schema, the Fetch closure below reads opts.Scope[key]
// and applies a predicate when set. Caller drives this via app.SetScope(key, value).
func registerTechDocPage(app *runtime.App, client *ent.Client) {
	runtime.Register(app, runtime.EntitySpec[*ent.TechDocPage]{
		Kind:           "techdocpage",
		Display:        "TechDocPages",
		Group:          "data",
		Icon:           "•",
		LabelKey:       "title",
		BodyKey:        "body",
		IDKey:          "id",
		PageSize:       200,
		MultiSort:      true,
		ShowEdgeCounts: true,
		AllowBulkCopy:  false,
		AllowExport:    false,
		Default: runtime.DefaultView{
			SortField: "created_at",
			SortDir:   runtime.Desc,
			Mode:      "",
		},

		Fetch: func(ctx context.Context, opts runtime.ListOpts) ([]*ent.TechDocPage, int, error) {
			q := client.TechDocPage.Query()
			// Scope predicate — keyed generically via ListOpts.Scope so the
			// runtime stays decoupled from any specific field name.
			if v := opts.Scope["project_id"]; v != "" {
				q = q.Where(entTechDocPage.ProjectID(v))
			}
			// Legacy substring filter — used by the list+preview browser's
			// global `/` prompt. Phase E (Filters slice) supersedes this
			// in the table view but both can coexist.
			if opts.Filter != "" {
				q = q.Where(entTechDocPage.Or(
					entTechDocPage.IDContainsFold(opts.Filter),
					entTechDocPage.ProjectIDContainsFold(opts.Filter),
					entTechDocPage.TechDocIDContainsFold(opts.Filter),
					entTechDocPage.URLContainsFold(opts.Filter),
					entTechDocPage.TitleContainsFold(opts.Filter),
					entTechDocPage.ContentShaContainsFold(opts.Filter),
				))
			}
			// Phase E — structured per-column filters. AND-composed.
			// Unsupported operators for a given field type fall through
			// silently rather than erroring — keeps the UI forgiving.
			for _, f := range opts.Filters {
				switch f.Field {
				case "id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entTechDocPage.IDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entTechDocPage.IDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entTechDocPage.IDContainsFold(f.Value))
					}
				case "project_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entTechDocPage.ProjectIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entTechDocPage.ProjectIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entTechDocPage.ProjectIDContainsFold(f.Value))
					}
				case "tech_doc_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entTechDocPage.TechDocIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entTechDocPage.TechDocIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entTechDocPage.TechDocIDContainsFold(f.Value))
					}
				case "url":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entTechDocPage.URLEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entTechDocPage.URLNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entTechDocPage.URLContainsFold(f.Value))
					}
				case "title":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entTechDocPage.TitleEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entTechDocPage.TitleNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entTechDocPage.TitleContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entTechDocPage.TitleIsNil())
					case runtime.OpNotNull:
						q = q.Where(entTechDocPage.TitleNotNil())
					}
				case "content_sha":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entTechDocPage.ContentShaEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entTechDocPage.ContentShaNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entTechDocPage.ContentShaContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entTechDocPage.ContentShaIsNil())
					case runtime.OpNotNull:
						q = q.Where(entTechDocPage.ContentShaNotNil())
					}
				}
			}
			// Phase D — multi-column sort stack. Each Sort entry walks the
			// generated dispatch; unknown fields are silently skipped.
			if len(opts.Sort) > 0 {
				for _, k := range opts.Sort {
					switch k.Field {
					case "id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entTechDocPage.FieldID))
						} else {
							q = q.Order(ent.Desc(entTechDocPage.FieldID))
						}
					case "created_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entTechDocPage.FieldCreatedAt))
						} else {
							q = q.Order(ent.Desc(entTechDocPage.FieldCreatedAt))
						}
					case "updated_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entTechDocPage.FieldUpdatedAt))
						} else {
							q = q.Order(ent.Desc(entTechDocPage.FieldUpdatedAt))
						}
					case "project_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entTechDocPage.FieldProjectID))
						} else {
							q = q.Order(ent.Desc(entTechDocPage.FieldProjectID))
						}
					case "tech_doc_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entTechDocPage.FieldTechDocID))
						} else {
							q = q.Order(ent.Desc(entTechDocPage.FieldTechDocID))
						}
					case "url":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entTechDocPage.FieldURL))
						} else {
							q = q.Order(ent.Desc(entTechDocPage.FieldURL))
						}
					case "title":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entTechDocPage.FieldTitle))
						} else {
							q = q.Order(ent.Desc(entTechDocPage.FieldTitle))
						}
					case "content_sha":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entTechDocPage.FieldContentSha))
						} else {
							q = q.Order(ent.Desc(entTechDocPage.FieldContentSha))
						}
					}
				}
			}
			total, err := q.Clone().Count(ctx)
			if err != nil {
				return nil, 0, err
			}
			rows, err := q.Offset(opts.Offset).Limit(opts.Limit).All(ctx)
			return rows, total, err
		},

		// Ent-native JSON for the `J` clipboard shortcut. *ent.TechDocPage
		// implements MarshalJSON so eager-loaded edges (from With*())
		// land in the output under `edges` automatically.
		JSON: func(r *ent.TechDocPage) ([]byte, error) { return json.Marshal(r) },

		Columns: []runtime.Column[*ent.TechDocPage]{
			{
				Key:        "id",
				Label:      "Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.TechDocPage) string {
					return r.ID
				},
			},
			{
				Key:        "created_at",
				Label:      "Created At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.TechDocPage) string {
					if r.CreatedAt.IsZero() {
						return ""
					}
					return r.CreatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "updated_at",
				Label:      "Updated At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.TechDocPage) string {
					if r.UpdatedAt.IsZero() {
						return ""
					}
					return r.UpdatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "project_id",
				Label:      "Project Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.TechDocPage) string {
					return r.ProjectID
				},
			},
			{
				Key:        "tech_doc_id",
				Label:      "Tech Doc Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.TechDocPage) string {
					return r.TechDocID
				},
			},
			{
				Key:        "url",
				Label:      "Url",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.TechDocPage) string {
					return r.URL
				},
			},
			{
				Key:        "title",
				Label:      "Title",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.TechDocPage) string {
					if r.Title == nil {
						return ""
					}
					return *r.Title
				},
			},
			{
				Key:        "body",
				Label:      "Body",
				Sortable:   false,
				Filterable: false,
				Hidden:     true,
				Width:      0,
				Align:      "",
				Get: func(r *ent.TechDocPage) string {
					return r.Body
				},
			},
			{
				Key:        "content_sha",
				Label:      "Content Sha",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.TechDocPage) string {
					if r.ContentSha == nil {
						return ""
					}
					return *r.ContentSha
				},
			},
		},

		Edges: []runtime.EdgeSpec[*ent.TechDocPage]{
			{
				Name: "tech_doc", Display: "→ TechDocs", Kind: runtime.EdgeUpward, Trigger: "t",
				// Count is emitted for BOTH upward and drill edges. For
				// upward edges it returns 0 or 1 (parent exists / doesn't).
				// For drill edges, the child row count.
				Count: func(ctx context.Context, r *ent.TechDocPage) (int, error) {
					return client.TechDocPage.QueryTechDoc(r).Count(ctx)
				},
				ResolveUpward: func(ctx context.Context, r *ent.TechDocPage) (runtime.EntityRef, error) {
					tgt, err := client.TechDocPage.QueryTechDoc(r).Only(ctx)
					if err != nil {
						return runtime.EntityRef{}, err
					}
					return runtime.EntityRef{Kind: "techdoc", ID: fmt.Sprint(tgt.ID)}, nil
				},
			},
		},
	})
}
