// Code generated by enttui. DO NOT EDIT.

package tuigen

import (
	"context"
	"dbent/gen/ent"
	entDraft "dbent/gen/ent/draft"
	"encoding/json"
	"fmt"

	"github.com/khanakia/entx/enttui/runtime"
)

// registerDraft wires *ent.Draft into the enttui runtime.
//
// Scope filtering: for every scope key configured in enttui.Config.ScopeFields
// that exists on this schema, the Fetch closure below reads opts.Scope[key]
// and applies a predicate when set. Caller drives this via app.SetScope(key, value).
func registerDraft(app *runtime.App, client *ent.Client) {
	runtime.Register(app, runtime.EntitySpec[*ent.Draft]{
		Kind:           "draft",
		Display:        "Drafts",
		Group:          "data",
		Icon:           "•",
		LabelKey:       "id",
		BodyKey:        "body",
		IDKey:          "id",
		PageSize:       200,
		MultiSort:      true,
		ShowEdgeCounts: true,
		AllowBulkCopy:  false,
		AllowExport:    false,
		Default: runtime.DefaultView{
			SortField: "created_at",
			SortDir:   runtime.Desc,
			Mode:      "",
		},

		Fetch: func(ctx context.Context, opts runtime.ListOpts) ([]*ent.Draft, int, error) {
			q := client.Draft.Query()
			// Legacy substring filter — used by the list+preview browser's
			// global `/` prompt. Phase E (Filters slice) supersedes this
			// in the table view but both can coexist.
			if opts.Filter != "" {
				q = q.Where(entDraft.Or(
					entDraft.IDContainsFold(opts.Filter),
					entDraft.TargetTableContainsFold(opts.Filter),
					entDraft.TargetIDContainsFold(opts.Filter),
					entDraft.ActorIDContainsFold(opts.Filter),
				))
			}
			// Phase E — structured per-column filters. AND-composed.
			// Unsupported operators for a given field type fall through
			// silently rather than erroring — keeps the UI forgiving.
			for _, f := range opts.Filters {
				switch f.Field {
				case "id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entDraft.IDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entDraft.IDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entDraft.IDContainsFold(f.Value))
					}
				case "target_table":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entDraft.TargetTableEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entDraft.TargetTableNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entDraft.TargetTableContainsFold(f.Value))
					}
				case "target_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entDraft.TargetIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entDraft.TargetIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entDraft.TargetIDContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entDraft.TargetIDIsNil())
					case runtime.OpNotNull:
						q = q.Where(entDraft.TargetIDNotNil())
					}
				case "actor_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entDraft.ActorIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entDraft.ActorIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entDraft.ActorIDContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entDraft.ActorIDIsNil())
					case runtime.OpNotNull:
						q = q.Where(entDraft.ActorIDNotNil())
					}
				}
			}
			// Phase D — multi-column sort stack. Each Sort entry walks the
			// generated dispatch; unknown fields are silently skipped.
			if len(opts.Sort) > 0 {
				for _, k := range opts.Sort {
					switch k.Field {
					case "id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entDraft.FieldID))
						} else {
							q = q.Order(ent.Desc(entDraft.FieldID))
						}
					case "created_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entDraft.FieldCreatedAt))
						} else {
							q = q.Order(ent.Desc(entDraft.FieldCreatedAt))
						}
					case "updated_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entDraft.FieldUpdatedAt))
						} else {
							q = q.Order(ent.Desc(entDraft.FieldUpdatedAt))
						}
					case "target_table":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entDraft.FieldTargetTable))
						} else {
							q = q.Order(ent.Desc(entDraft.FieldTargetTable))
						}
					case "target_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entDraft.FieldTargetID))
						} else {
							q = q.Order(ent.Desc(entDraft.FieldTargetID))
						}
					case "actor_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entDraft.FieldActorID))
						} else {
							q = q.Order(ent.Desc(entDraft.FieldActorID))
						}
					case "started_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entDraft.FieldStartedAt))
						} else {
							q = q.Order(ent.Desc(entDraft.FieldStartedAt))
						}
					}
				}
			}
			total, err := q.Clone().Count(ctx)
			if err != nil {
				return nil, 0, err
			}
			rows, err := q.Offset(opts.Offset).Limit(opts.Limit).All(ctx)
			return rows, total, err
		},

		// Ent-native JSON for the `J` clipboard shortcut. *ent.Draft
		// implements MarshalJSON so eager-loaded edges (from With*())
		// land in the output under `edges` automatically.
		JSON: func(r *ent.Draft) ([]byte, error) { return json.Marshal(r) },

		Columns: []runtime.Column[*ent.Draft]{
			{
				Key:        "id",
				Label:      "Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Draft) string {
					return r.ID
				},
			},
			{
				Key:        "created_at",
				Label:      "Created At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Draft) string {
					if r.CreatedAt.IsZero() {
						return ""
					}
					return r.CreatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "updated_at",
				Label:      "Updated At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Draft) string {
					if r.UpdatedAt.IsZero() {
						return ""
					}
					return r.UpdatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "target_table",
				Label:      "Target Table",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Draft) string {
					return r.TargetTable
				},
			},
			{
				Key:        "target_id",
				Label:      "Target Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Draft) string {
					if r.TargetID == nil {
						return ""
					}
					return *r.TargetID
				},
			},
			{
				Key:        "body",
				Label:      "Body",
				Sortable:   false,
				Filterable: false,
				Hidden:     true,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Draft) string {
					return r.Body
				},
			},
			{
				Key:        "actor_id",
				Label:      "Actor Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Draft) string {
					if r.ActorID == nil {
						return ""
					}
					return *r.ActorID
				},
			},
			{
				Key:        "started_at",
				Label:      "Started At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Draft) string {
					if r.StartedAt.IsZero() {
						return ""
					}
					return r.StartedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "pid",
				Label:      "Pid",
				Sortable:   false,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Draft) string {
					if r.Pid == nil {
						return ""
					}
					return fmt.Sprintf("%v", *r.Pid)
				},
			},
		},
	})
}
