// Code generated by enttui. DO NOT EDIT.

package tuigen

import (
	"context"
	"dbent/gen/ent"
	entDecision "dbent/gen/ent/decision"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/khanakia/entx/enttui/runtime"
)

// registerDecision wires *ent.Decision into the enttui runtime.
//
// Scope filtering: for every scope key configured in enttui.Config.ScopeFields
// that exists on this schema, the Fetch closure below reads opts.Scope[key]
// and applies a predicate when set. Caller drives this via app.SetScope(key, value).
func registerDecision(app *runtime.App, client *ent.Client) {
	runtime.Register(app, runtime.EntitySpec[*ent.Decision]{
		Kind:           "decision",
		Display:        "Decisions",
		Group:          "data",
		Icon:           "•",
		LabelKey:       "title",
		BodyKey:        "body",
		IDKey:          "id",
		PageSize:       200,
		MultiSort:      true,
		ShowEdgeCounts: true,
		AllowBulkCopy:  false,
		AllowExport:    false,
		Default: runtime.DefaultView{
			SortField: "created_at",
			SortDir:   runtime.Desc,
			Mode:      "",
		},

		Fetch: func(ctx context.Context, opts runtime.ListOpts) ([]*ent.Decision, int, error) {
			q := client.Decision.Query()
			// Scope predicate — keyed generically via ListOpts.Scope so the
			// runtime stays decoupled from any specific field name.
			if v := opts.Scope["project_id"]; v != "" {
				q = q.Where(entDecision.ProjectID(v))
			}
			// Legacy substring filter — used by the list+preview browser's
			// global `/` prompt. Phase E (Filters slice) supersedes this
			// in the table view but both can coexist.
			if opts.Filter != "" {
				q = q.Where(entDecision.Or(
					entDecision.IDContainsFold(opts.Filter),
					entDecision.SourceKindContainsFold(opts.Filter),
					entDecision.SourceRefContainsFold(opts.Filter),
					entDecision.ProjectIDContainsFold(opts.Filter),
					entDecision.RepoIDContainsFold(opts.Filter),
					entDecision.TitleContainsFold(opts.Filter),
					entDecision.BodyContainsFold(opts.Filter),
					entDecision.SupersededByIDContainsFold(opts.Filter),
					entDecision.CreatedByActorIDContainsFold(opts.Filter),
				))
			}
			// Phase E — structured per-column filters. AND-composed.
			// Unsupported operators for a given field type fall through
			// silently rather than erroring — keeps the UI forgiving.
			for _, f := range opts.Filters {
				switch f.Field {
				case "id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entDecision.IDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entDecision.IDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entDecision.IDContainsFold(f.Value))
					}
				case "source_kind":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entDecision.SourceKindEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entDecision.SourceKindNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entDecision.SourceKindContainsFold(f.Value))
					}
				case "source_ref":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entDecision.SourceRefEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entDecision.SourceRefNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entDecision.SourceRefContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entDecision.SourceRefIsNil())
					case runtime.OpNotNull:
						q = q.Where(entDecision.SourceRefNotNil())
					}
				case "project_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entDecision.ProjectIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entDecision.ProjectIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entDecision.ProjectIDContainsFold(f.Value))
					}
				case "repo_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entDecision.RepoIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entDecision.RepoIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entDecision.RepoIDContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entDecision.RepoIDIsNil())
					case runtime.OpNotNull:
						q = q.Where(entDecision.RepoIDNotNil())
					}
				case "title":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entDecision.TitleEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entDecision.TitleNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entDecision.TitleContainsFold(f.Value))
					}
				case "body":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entDecision.BodyEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entDecision.BodyNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entDecision.BodyContainsFold(f.Value))
					}
				case "status":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entDecision.StatusEQ(entDecision.Status(f.Value)))
					case runtime.OpNeq:
						q = q.Where(entDecision.StatusNEQ(entDecision.Status(f.Value)))
					case runtime.OpIn, runtime.OpNotIn:
						// Multi-select: condition value is a "|"-joined
						// list of enum strings. Empty entries are dropped.
						parts := strings.Split(f.Value, "|")
						vals := make([]entDecision.Status, 0, len(parts))
						for _, p := range parts {
							if p == "" {
								continue
							}
							vals = append(vals, entDecision.Status(p))
						}
						if len(vals) > 0 {
							if f.Op == runtime.OpIn {
								q = q.Where(entDecision.StatusIn(vals...))
							} else {
								q = q.Where(entDecision.StatusNotIn(vals...))
							}
						}
					}
				case "superseded_by_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entDecision.SupersededByIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entDecision.SupersededByIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entDecision.SupersededByIDContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entDecision.SupersededByIDIsNil())
					case runtime.OpNotNull:
						q = q.Where(entDecision.SupersededByIDNotNil())
					}
				case "created_by_actor_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entDecision.CreatedByActorIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entDecision.CreatedByActorIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entDecision.CreatedByActorIDContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entDecision.CreatedByActorIDIsNil())
					case runtime.OpNotNull:
						q = q.Where(entDecision.CreatedByActorIDNotNil())
					}
				}
			}
			// Phase D — multi-column sort stack. Each Sort entry walks the
			// generated dispatch; unknown fields are silently skipped.
			if len(opts.Sort) > 0 {
				for _, k := range opts.Sort {
					switch k.Field {
					case "id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entDecision.FieldID))
						} else {
							q = q.Order(ent.Desc(entDecision.FieldID))
						}
					case "created_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entDecision.FieldCreatedAt))
						} else {
							q = q.Order(ent.Desc(entDecision.FieldCreatedAt))
						}
					case "updated_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entDecision.FieldUpdatedAt))
						} else {
							q = q.Order(ent.Desc(entDecision.FieldUpdatedAt))
						}
					case "last_accessed_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entDecision.FieldLastAccessedAt))
						} else {
							q = q.Order(ent.Desc(entDecision.FieldLastAccessedAt))
						}
					case "last_validated_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entDecision.FieldLastValidatedAt))
						} else {
							q = q.Order(ent.Desc(entDecision.FieldLastValidatedAt))
						}
					case "archived_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entDecision.FieldArchivedAt))
						} else {
							q = q.Order(ent.Desc(entDecision.FieldArchivedAt))
						}
					case "source_kind":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entDecision.FieldSourceKind))
						} else {
							q = q.Order(ent.Desc(entDecision.FieldSourceKind))
						}
					case "source_ref":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entDecision.FieldSourceRef))
						} else {
							q = q.Order(ent.Desc(entDecision.FieldSourceRef))
						}
					case "project_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entDecision.FieldProjectID))
						} else {
							q = q.Order(ent.Desc(entDecision.FieldProjectID))
						}
					case "repo_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entDecision.FieldRepoID))
						} else {
							q = q.Order(ent.Desc(entDecision.FieldRepoID))
						}
					case "title":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entDecision.FieldTitle))
						} else {
							q = q.Order(ent.Desc(entDecision.FieldTitle))
						}
					case "status":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entDecision.FieldStatus))
						} else {
							q = q.Order(ent.Desc(entDecision.FieldStatus))
						}
					case "superseded_by_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entDecision.FieldSupersededByID))
						} else {
							q = q.Order(ent.Desc(entDecision.FieldSupersededByID))
						}
					case "created_by_actor_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entDecision.FieldCreatedByActorID))
						} else {
							q = q.Order(ent.Desc(entDecision.FieldCreatedByActorID))
						}
					}
				}
			}
			total, err := q.Clone().Count(ctx)
			if err != nil {
				return nil, 0, err
			}
			rows, err := q.Offset(opts.Offset).Limit(opts.Limit).All(ctx)
			return rows, total, err
		},

		// Ent-native JSON for the `J` clipboard shortcut. *ent.Decision
		// implements MarshalJSON so eager-loaded edges (from With*())
		// land in the output under `edges` automatically.
		JSON: func(r *ent.Decision) ([]byte, error) { return json.Marshal(r) },

		Columns: []runtime.Column[*ent.Decision]{
			{
				Key:        "id",
				Label:      "Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Decision) string {
					return r.ID
				},
			},
			{
				Key:        "created_at",
				Label:      "Created At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Decision) string {
					if r.CreatedAt.IsZero() {
						return ""
					}
					return r.CreatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "updated_at",
				Label:      "Updated At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Decision) string {
					if r.UpdatedAt.IsZero() {
						return ""
					}
					return r.UpdatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "trust_score",
				Label:      "Trust Score",
				Sortable:   false,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Decision) string {
					return fmt.Sprintf("%v", r.TrustScore)
				},
			},
			{
				Key:        "confidence",
				Label:      "Confidence",
				Sortable:   false,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Decision) string {
					if r.Confidence == nil {
						return ""
					}
					return fmt.Sprintf("%v", *r.Confidence)
				},
			},
			{
				Key:        "last_accessed_at",
				Label:      "Last Accessed At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Decision) string {
					if r.LastAccessedAt == nil || r.LastAccessedAt.IsZero() {
						return ""
					}
					return r.LastAccessedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "last_validated_at",
				Label:      "Last Validated At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Decision) string {
					if r.LastValidatedAt == nil || r.LastValidatedAt.IsZero() {
						return ""
					}
					return r.LastValidatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "archived_at",
				Label:      "Archived At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Decision) string {
					if r.ArchivedAt == nil || r.ArchivedAt.IsZero() {
						return ""
					}
					return r.ArchivedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "source_kind",
				Label:      "Source Kind",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Decision) string {
					return r.SourceKind
				},
			},
			{
				Key:        "source_ref",
				Label:      "Source Ref",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Decision) string {
					if r.SourceRef == nil {
						return ""
					}
					return *r.SourceRef
				},
			},
			{
				Key:        "project_id",
				Label:      "Project Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Decision) string {
					return r.ProjectID
				},
			},
			{
				Key:        "repo_id",
				Label:      "Repo Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Decision) string {
					if r.RepoID == nil {
						return ""
					}
					return *r.RepoID
				},
			},
			{
				Key:        "title",
				Label:      "Title",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Decision) string {
					return r.Title
				},
			},
			{
				Key:        "body",
				Label:      "Body",
				Sortable:   false,
				Filterable: true,
				Hidden:     true,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Decision) string {
					return r.Body
				},
			},
			{
				Key:        "status",
				Label:      "Status",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				EnumValues: []string{
					"proposed",
					"accepted",
					"superseded",
					"deprecated",
				},
				Get: func(r *ent.Decision) string {
					return string(r.Status)
				},
			},
			{
				Key:        "superseded_by_id",
				Label:      "Superseded By Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Decision) string {
					if r.SupersededByID == nil {
						return ""
					}
					return *r.SupersededByID
				},
			},
			{
				Key:        "created_by_actor_id",
				Label:      "Created By Actor Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Decision) string {
					if r.CreatedByActorID == nil {
						return ""
					}
					return *r.CreatedByActorID
				},
			},
		},
	})
}
