// Code generated by enttui. DO NOT EDIT.

package tuigen

import (
	"context"
	"dbent/gen/ent"
	entAssembleRun "dbent/gen/ent/assemblerun"
	"encoding/json"
	"fmt"

	"github.com/khanakia/entx/enttui/runtime"
)

// registerAssembleRun wires *ent.AssembleRun into the enttui runtime.
//
// Scope filtering: for every scope key configured in enttui.Config.ScopeFields
// that exists on this schema, the Fetch closure below reads opts.Scope[key]
// and applies a predicate when set. Caller drives this via app.SetScope(key, value).
func registerAssembleRun(app *runtime.App, client *ent.Client) {
	runtime.Register(app, runtime.EntitySpec[*ent.AssembleRun]{
		Kind:           "assemblerun",
		Display:        "AssembleRuns",
		Group:          "data",
		Icon:           "•",
		LabelKey:       "id",
		BodyKey:        "",
		IDKey:          "id",
		PageSize:       200,
		MultiSort:      true,
		ShowEdgeCounts: true,
		AllowBulkCopy:  false,
		AllowExport:    false,
		Default: runtime.DefaultView{
			SortField: "created_at",
			SortDir:   runtime.Desc,
			Mode:      "",
		},

		Fetch: func(ctx context.Context, opts runtime.ListOpts) ([]*ent.AssembleRun, int, error) {
			q := client.AssembleRun.Query()
			// Scope predicate — keyed generically via ListOpts.Scope so the
			// runtime stays decoupled from any specific field name.
			if v := opts.Scope["project_id"]; v != "" {
				q = q.Where(entAssembleRun.ProjectID(v))
			}
			// Legacy substring filter — used by the list+preview browser's
			// global `/` prompt. Phase E (Filters slice) supersedes this
			// in the table view but both can coexist.
			if opts.Filter != "" {
				q = q.Where(entAssembleRun.Or(
					entAssembleRun.IDContainsFold(opts.Filter),
					entAssembleRun.ProjectIDContainsFold(opts.Filter),
					entAssembleRun.QueryTextContainsFold(opts.Filter),
					entAssembleRun.RenderedTargetContainsFold(opts.Filter),
					entAssembleRun.CreatedByActorIDContainsFold(opts.Filter),
				))
			}
			// Phase E — structured per-column filters. AND-composed.
			// Unsupported operators for a given field type fall through
			// silently rather than erroring — keeps the UI forgiving.
			for _, f := range opts.Filters {
				switch f.Field {
				case "id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entAssembleRun.IDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entAssembleRun.IDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entAssembleRun.IDContainsFold(f.Value))
					}
				case "project_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entAssembleRun.ProjectIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entAssembleRun.ProjectIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entAssembleRun.ProjectIDContainsFold(f.Value))
					}
				case "query_text":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entAssembleRun.QueryTextEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entAssembleRun.QueryTextNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entAssembleRun.QueryTextContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entAssembleRun.QueryTextIsNil())
					case runtime.OpNotNull:
						q = q.Where(entAssembleRun.QueryTextNotNil())
					}
				case "rendered_target":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entAssembleRun.RenderedTargetEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entAssembleRun.RenderedTargetNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entAssembleRun.RenderedTargetContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entAssembleRun.RenderedTargetIsNil())
					case runtime.OpNotNull:
						q = q.Where(entAssembleRun.RenderedTargetNotNil())
					}
				case "created_by_actor_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entAssembleRun.CreatedByActorIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entAssembleRun.CreatedByActorIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entAssembleRun.CreatedByActorIDContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entAssembleRun.CreatedByActorIDIsNil())
					case runtime.OpNotNull:
						q = q.Where(entAssembleRun.CreatedByActorIDNotNil())
					}
				}
			}
			// Phase D — multi-column sort stack. Each Sort entry walks the
			// generated dispatch; unknown fields are silently skipped.
			if len(opts.Sort) > 0 {
				for _, k := range opts.Sort {
					switch k.Field {
					case "id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entAssembleRun.FieldID))
						} else {
							q = q.Order(ent.Desc(entAssembleRun.FieldID))
						}
					case "created_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entAssembleRun.FieldCreatedAt))
						} else {
							q = q.Order(ent.Desc(entAssembleRun.FieldCreatedAt))
						}
					case "updated_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entAssembleRun.FieldUpdatedAt))
						} else {
							q = q.Order(ent.Desc(entAssembleRun.FieldUpdatedAt))
						}
					case "project_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entAssembleRun.FieldProjectID))
						} else {
							q = q.Order(ent.Desc(entAssembleRun.FieldProjectID))
						}
					case "query_text":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entAssembleRun.FieldQueryText))
						} else {
							q = q.Order(ent.Desc(entAssembleRun.FieldQueryText))
						}
					case "rendered_target":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entAssembleRun.FieldRenderedTarget))
						} else {
							q = q.Order(ent.Desc(entAssembleRun.FieldRenderedTarget))
						}
					case "created_by_actor_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entAssembleRun.FieldCreatedByActorID))
						} else {
							q = q.Order(ent.Desc(entAssembleRun.FieldCreatedByActorID))
						}
					}
				}
			}
			total, err := q.Clone().Count(ctx)
			if err != nil {
				return nil, 0, err
			}
			rows, err := q.Offset(opts.Offset).Limit(opts.Limit).All(ctx)
			return rows, total, err
		},

		// Ent-native JSON for the `J` clipboard shortcut. *ent.AssembleRun
		// implements MarshalJSON so eager-loaded edges (from With*())
		// land in the output under `edges` automatically.
		JSON: func(r *ent.AssembleRun) ([]byte, error) { return json.Marshal(r) },

		Columns: []runtime.Column[*ent.AssembleRun]{
			{
				Key:        "id",
				Label:      "Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.AssembleRun) string {
					return r.ID
				},
			},
			{
				Key:        "created_at",
				Label:      "Created At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.AssembleRun) string {
					if r.CreatedAt.IsZero() {
						return ""
					}
					return r.CreatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "updated_at",
				Label:      "Updated At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.AssembleRun) string {
					if r.UpdatedAt.IsZero() {
						return ""
					}
					return r.UpdatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "project_id",
				Label:      "Project Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.AssembleRun) string {
					return r.ProjectID
				},
			},
			{
				Key:        "query_text",
				Label:      "Query Text",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.AssembleRun) string {
					if r.QueryText == nil {
						return ""
					}
					return *r.QueryText
				},
			},
			{
				Key:        "rendered_target",
				Label:      "Rendered Target",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.AssembleRun) string {
					if r.RenderedTarget == nil {
						return ""
					}
					return *r.RenderedTarget
				},
			},
			{
				Key:        "total_bytes",
				Label:      "Total Bytes",
				Sortable:   false,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.AssembleRun) string {
					if r.TotalBytes == nil {
						return ""
					}
					return fmt.Sprintf("%v", *r.TotalBytes)
				},
			},
			{
				Key:        "created_by_actor_id",
				Label:      "Created By Actor Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.AssembleRun) string {
					if r.CreatedByActorID == nil {
						return ""
					}
					return *r.CreatedByActorID
				},
			},
		},

		Edges: []runtime.EdgeSpec[*ent.AssembleRun]{
			{
				Name: "citations", Display: "AssembleCitations", Kind: runtime.EdgeDrill, Trigger: "c",
				// Count is emitted for BOTH upward and drill edges. For
				// upward edges it returns 0 or 1 (parent exists / doesn't).
				// For drill edges, the child row count.
				Count: func(ctx context.Context, r *ent.AssembleRun) (int, error) {
					return client.AssembleRun.QueryCitations(r).Count(ctx)
				},
				ResolveDrill: func(ctx context.Context, r *ent.AssembleRun) (runtime.EntityRefList, error) {
					ids, err := client.AssembleRun.QueryCitations(r).IDs(ctx)
					if err != nil {
						return runtime.EntityRefList{}, err
					}
					sids := make([]string, len(ids))
					for i, v := range ids {
						sids[i] = fmt.Sprint(v)
					}
					return runtime.EntityRefList{Kind: "assemblecitation", IDs: sids}, nil
				},
			},
		},
	})
}
