// Code generated by enttui. DO NOT EDIT.

package tuigen

import (
	"context"
	"dbent/gen/ent"
	entCodeFile "dbent/gen/ent/codefile"
	"encoding/json"
	"fmt"

	"github.com/khanakia/entx/enttui/runtime"
)

// registerCodeFile wires *ent.CodeFile into the enttui runtime.
//
// Scope filtering: for every scope key configured in enttui.Config.ScopeFields
// that exists on this schema, the Fetch closure below reads opts.Scope[key]
// and applies a predicate when set. Caller drives this via app.SetScope(key, value).
func registerCodeFile(app *runtime.App, client *ent.Client) {
	runtime.Register(app, runtime.EntitySpec[*ent.CodeFile]{
		Kind:           "codefile",
		Display:        "CodeFiles",
		Group:          "data",
		Icon:           "•",
		LabelKey:       "id",
		BodyKey:        "",
		IDKey:          "id",
		PageSize:       200,
		MultiSort:      true,
		ShowEdgeCounts: true,
		AllowBulkCopy:  false,
		AllowExport:    false,
		Default: runtime.DefaultView{
			SortField: "created_at",
			SortDir:   runtime.Desc,
			Mode:      "",
		},

		Fetch: func(ctx context.Context, opts runtime.ListOpts) ([]*ent.CodeFile, int, error) {
			q := client.CodeFile.Query()
			// Scope predicate — keyed generically via ListOpts.Scope so the
			// runtime stays decoupled from any specific field name.
			if v := opts.Scope["project_id"]; v != "" {
				q = q.Where(entCodeFile.ProjectID(v))
			}
			// Legacy substring filter — used by the list+preview browser's
			// global `/` prompt. Phase E (Filters slice) supersedes this
			// in the table view but both can coexist.
			if opts.Filter != "" {
				q = q.Where(entCodeFile.Or(
					entCodeFile.IDContainsFold(opts.Filter),
					entCodeFile.ProjectIDContainsFold(opts.Filter),
					entCodeFile.RepoIDContainsFold(opts.Filter),
					entCodeFile.PathContainsFold(opts.Filter),
					entCodeFile.LanguageContainsFold(opts.Filter),
					entCodeFile.ContentShaContainsFold(opts.Filter),
				))
			}
			// Phase E — structured per-column filters. AND-composed.
			// Unsupported operators for a given field type fall through
			// silently rather than erroring — keeps the UI forgiving.
			for _, f := range opts.Filters {
				switch f.Field {
				case "id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entCodeFile.IDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entCodeFile.IDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entCodeFile.IDContainsFold(f.Value))
					}
				case "project_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entCodeFile.ProjectIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entCodeFile.ProjectIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entCodeFile.ProjectIDContainsFold(f.Value))
					}
				case "repo_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entCodeFile.RepoIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entCodeFile.RepoIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entCodeFile.RepoIDContainsFold(f.Value))
					}
				case "path":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entCodeFile.PathEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entCodeFile.PathNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entCodeFile.PathContainsFold(f.Value))
					}
				case "language":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entCodeFile.LanguageEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entCodeFile.LanguageNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entCodeFile.LanguageContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entCodeFile.LanguageIsNil())
					case runtime.OpNotNull:
						q = q.Where(entCodeFile.LanguageNotNil())
					}
				case "content_sha":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entCodeFile.ContentShaEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entCodeFile.ContentShaNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entCodeFile.ContentShaContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entCodeFile.ContentShaIsNil())
					case runtime.OpNotNull:
						q = q.Where(entCodeFile.ContentShaNotNil())
					}
				}
			}
			// Phase D — multi-column sort stack. Each Sort entry walks the
			// generated dispatch; unknown fields are silently skipped.
			if len(opts.Sort) > 0 {
				for _, k := range opts.Sort {
					switch k.Field {
					case "id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entCodeFile.FieldID))
						} else {
							q = q.Order(ent.Desc(entCodeFile.FieldID))
						}
					case "created_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entCodeFile.FieldCreatedAt))
						} else {
							q = q.Order(ent.Desc(entCodeFile.FieldCreatedAt))
						}
					case "updated_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entCodeFile.FieldUpdatedAt))
						} else {
							q = q.Order(ent.Desc(entCodeFile.FieldUpdatedAt))
						}
					case "project_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entCodeFile.FieldProjectID))
						} else {
							q = q.Order(ent.Desc(entCodeFile.FieldProjectID))
						}
					case "repo_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entCodeFile.FieldRepoID))
						} else {
							q = q.Order(ent.Desc(entCodeFile.FieldRepoID))
						}
					case "path":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entCodeFile.FieldPath))
						} else {
							q = q.Order(ent.Desc(entCodeFile.FieldPath))
						}
					case "language":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entCodeFile.FieldLanguage))
						} else {
							q = q.Order(ent.Desc(entCodeFile.FieldLanguage))
						}
					case "content_sha":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entCodeFile.FieldContentSha))
						} else {
							q = q.Order(ent.Desc(entCodeFile.FieldContentSha))
						}
					case "last_indexed_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entCodeFile.FieldLastIndexedAt))
						} else {
							q = q.Order(ent.Desc(entCodeFile.FieldLastIndexedAt))
						}
					case "archived_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entCodeFile.FieldArchivedAt))
						} else {
							q = q.Order(ent.Desc(entCodeFile.FieldArchivedAt))
						}
					}
				}
			}
			total, err := q.Clone().Count(ctx)
			if err != nil {
				return nil, 0, err
			}
			rows, err := q.Offset(opts.Offset).Limit(opts.Limit).All(ctx)
			return rows, total, err
		},

		// Ent-native JSON for the `J` clipboard shortcut. *ent.CodeFile
		// implements MarshalJSON so eager-loaded edges (from With*())
		// land in the output under `edges` automatically.
		JSON: func(r *ent.CodeFile) ([]byte, error) { return json.Marshal(r) },

		Columns: []runtime.Column[*ent.CodeFile]{
			{
				Key:        "id",
				Label:      "Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.CodeFile) string {
					return r.ID
				},
			},
			{
				Key:        "created_at",
				Label:      "Created At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.CodeFile) string {
					if r.CreatedAt.IsZero() {
						return ""
					}
					return r.CreatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "updated_at",
				Label:      "Updated At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.CodeFile) string {
					if r.UpdatedAt.IsZero() {
						return ""
					}
					return r.UpdatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "project_id",
				Label:      "Project Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.CodeFile) string {
					return r.ProjectID
				},
			},
			{
				Key:        "repo_id",
				Label:      "Repo Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.CodeFile) string {
					return r.RepoID
				},
			},
			{
				Key:        "path",
				Label:      "Path",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.CodeFile) string {
					return r.Path
				},
			},
			{
				Key:        "language",
				Label:      "Language",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.CodeFile) string {
					if r.Language == nil {
						return ""
					}
					return *r.Language
				},
			},
			{
				Key:        "size_bytes",
				Label:      "Size Bytes",
				Sortable:   false,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.CodeFile) string {
					if r.SizeBytes == nil {
						return ""
					}
					return fmt.Sprintf("%v", *r.SizeBytes)
				},
			},
			{
				Key:        "content_sha",
				Label:      "Content Sha",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.CodeFile) string {
					if r.ContentSha == nil {
						return ""
					}
					return *r.ContentSha
				},
			},
			{
				Key:        "last_indexed_at",
				Label:      "Last Indexed At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.CodeFile) string {
					if r.LastIndexedAt.IsZero() {
						return ""
					}
					return r.LastIndexedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "archived_at",
				Label:      "Archived At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.CodeFile) string {
					if r.ArchivedAt == nil || r.ArchivedAt.IsZero() {
						return ""
					}
					return r.ArchivedAt.Format("2006-01-02 15:04:05")
				},
			},
		},
	})
}
