// Code generated by enttui. DO NOT EDIT.

package tuigen

import (
	"context"
	"dbent/gen/ent"
	entRunStep "dbent/gen/ent/runstep"
	"encoding/json"
	"fmt"

	"github.com/khanakia/entx/enttui/runtime"
)

// registerRunStep wires *ent.RunStep into the enttui runtime.
//
// Scope filtering: for every scope key configured in enttui.Config.ScopeFields
// that exists on this schema, the Fetch closure below reads opts.Scope[key]
// and applies a predicate when set. Caller drives this via app.SetScope(key, value).
func registerRunStep(app *runtime.App, client *ent.Client) {
	runtime.Register(app, runtime.EntitySpec[*ent.RunStep]{
		Kind:           "runstep",
		Display:        "RunSteps",
		Group:          "data",
		Icon:           "•",
		LabelKey:       "id",
		BodyKey:        "",
		IDKey:          "id",
		PageSize:       200,
		MultiSort:      true,
		ShowEdgeCounts: true,
		AllowBulkCopy:  false,
		AllowExport:    false,
		Default: runtime.DefaultView{
			SortField: "created_at",
			SortDir:   runtime.Desc,
			Mode:      "",
		},

		Fetch: func(ctx context.Context, opts runtime.ListOpts) ([]*ent.RunStep, int, error) {
			q := client.RunStep.Query()
			// Scope predicate — keyed generically via ListOpts.Scope so the
			// runtime stays decoupled from any specific field name.
			if v := opts.Scope["project_id"]; v != "" {
				q = q.Where(entRunStep.ProjectID(v))
			}
			// Legacy substring filter — used by the list+preview browser's
			// global `/` prompt. Phase E (Filters slice) supersedes this
			// in the table view but both can coexist.
			if opts.Filter != "" {
				q = q.Where(entRunStep.Or(
					entRunStep.IDContainsFold(opts.Filter),
					entRunStep.ProjectIDContainsFold(opts.Filter),
					entRunStep.RunIDContainsFold(opts.Filter),
					entRunStep.KindContainsFold(opts.Filter),
					entRunStep.StatusStrContainsFold(opts.Filter),
					entRunStep.PayloadContainsFold(opts.Filter),
				))
			}
			// Phase E — structured per-column filters. AND-composed.
			// Unsupported operators for a given field type fall through
			// silently rather than erroring — keeps the UI forgiving.
			for _, f := range opts.Filters {
				switch f.Field {
				case "id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entRunStep.IDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entRunStep.IDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entRunStep.IDContainsFold(f.Value))
					}
				case "project_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entRunStep.ProjectIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entRunStep.ProjectIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entRunStep.ProjectIDContainsFold(f.Value))
					}
				case "run_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entRunStep.RunIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entRunStep.RunIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entRunStep.RunIDContainsFold(f.Value))
					}
				case "kind":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entRunStep.KindEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entRunStep.KindNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entRunStep.KindContainsFold(f.Value))
					}
				case "status_str":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entRunStep.StatusStrEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entRunStep.StatusStrNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entRunStep.StatusStrContainsFold(f.Value))
					}
				case "payload":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entRunStep.PayloadEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entRunStep.PayloadNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entRunStep.PayloadContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entRunStep.PayloadIsNil())
					case runtime.OpNotNull:
						q = q.Where(entRunStep.PayloadNotNil())
					}
				}
			}
			// Phase D — multi-column sort stack. Each Sort entry walks the
			// generated dispatch; unknown fields are silently skipped.
			if len(opts.Sort) > 0 {
				for _, k := range opts.Sort {
					switch k.Field {
					case "id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entRunStep.FieldID))
						} else {
							q = q.Order(ent.Desc(entRunStep.FieldID))
						}
					case "created_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entRunStep.FieldCreatedAt))
						} else {
							q = q.Order(ent.Desc(entRunStep.FieldCreatedAt))
						}
					case "updated_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entRunStep.FieldUpdatedAt))
						} else {
							q = q.Order(ent.Desc(entRunStep.FieldUpdatedAt))
						}
					case "project_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entRunStep.FieldProjectID))
						} else {
							q = q.Order(ent.Desc(entRunStep.FieldProjectID))
						}
					case "run_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entRunStep.FieldRunID))
						} else {
							q = q.Order(ent.Desc(entRunStep.FieldRunID))
						}
					case "kind":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entRunStep.FieldKind))
						} else {
							q = q.Order(ent.Desc(entRunStep.FieldKind))
						}
					case "status_str":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entRunStep.FieldStatusStr))
						} else {
							q = q.Order(ent.Desc(entRunStep.FieldStatusStr))
						}
					case "payload":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entRunStep.FieldPayload))
						} else {
							q = q.Order(ent.Desc(entRunStep.FieldPayload))
						}
					}
				}
			}
			total, err := q.Clone().Count(ctx)
			if err != nil {
				return nil, 0, err
			}
			rows, err := q.Offset(opts.Offset).Limit(opts.Limit).All(ctx)
			return rows, total, err
		},

		// Ent-native JSON for the `J` clipboard shortcut. *ent.RunStep
		// implements MarshalJSON so eager-loaded edges (from With*())
		// land in the output under `edges` automatically.
		JSON: func(r *ent.RunStep) ([]byte, error) { return json.Marshal(r) },

		Columns: []runtime.Column[*ent.RunStep]{
			{
				Key:        "id",
				Label:      "Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.RunStep) string {
					return r.ID
				},
			},
			{
				Key:        "created_at",
				Label:      "Created At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.RunStep) string {
					if r.CreatedAt.IsZero() {
						return ""
					}
					return r.CreatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "updated_at",
				Label:      "Updated At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.RunStep) string {
					if r.UpdatedAt.IsZero() {
						return ""
					}
					return r.UpdatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "project_id",
				Label:      "Project Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.RunStep) string {
					return r.ProjectID
				},
			},
			{
				Key:        "run_id",
				Label:      "Run Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.RunStep) string {
					return r.RunID
				},
			},
			{
				Key:        "seq",
				Label:      "Seq",
				Sortable:   false,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.RunStep) string {
					return fmt.Sprintf("%v", r.Seq)
				},
			},
			{
				Key:        "kind",
				Label:      "Kind",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.RunStep) string {
					return r.Kind
				},
			},
			{
				Key:        "status_str",
				Label:      "Status Str",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.RunStep) string {
					return r.StatusStr
				},
			},
			{
				Key:        "payload",
				Label:      "Payload",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.RunStep) string {
					if r.Payload == nil {
						return ""
					}
					return *r.Payload
				},
			},
		},

		Edges: []runtime.EdgeSpec[*ent.RunStep]{
			{
				Name: "run", Display: "→ Runs", Kind: runtime.EdgeUpward, Trigger: "u",
				// Count is emitted for BOTH upward and drill edges. For
				// upward edges it returns 0 or 1 (parent exists / doesn't).
				// For drill edges, the child row count.
				Count: func(ctx context.Context, r *ent.RunStep) (int, error) {
					return client.RunStep.QueryRun(r).Count(ctx)
				},
				ResolveUpward: func(ctx context.Context, r *ent.RunStep) (runtime.EntityRef, error) {
					tgt, err := client.RunStep.QueryRun(r).Only(ctx)
					if err != nil {
						return runtime.EntityRef{}, err
					}
					return runtime.EntityRef{Kind: "run", ID: fmt.Sprint(tgt.ID)}, nil
				},
			},
		},
	})
}
