// Code generated by enttui. DO NOT EDIT.

package tuigen

import (
	"context"
	"dbent/gen/ent"
	entHandoff "dbent/gen/ent/handoff"
	"encoding/json"

	"github.com/khanakia/entx/enttui/runtime"
)

// registerHandoff wires *ent.Handoff into the enttui runtime.
//
// Scope filtering: for every scope key configured in enttui.Config.ScopeFields
// that exists on this schema, the Fetch closure below reads opts.Scope[key]
// and applies a predicate when set. Caller drives this via app.SetScope(key, value).
func registerHandoff(app *runtime.App, client *ent.Client) {
	runtime.Register(app, runtime.EntitySpec[*ent.Handoff]{
		Kind:           "handoff",
		Display:        "Handoffs",
		Group:          "data",
		Icon:           "•",
		LabelKey:       "id",
		BodyKey:        "body",
		IDKey:          "id",
		PageSize:       200,
		MultiSort:      true,
		ShowEdgeCounts: true,
		AllowBulkCopy:  false,
		AllowExport:    false,
		Default: runtime.DefaultView{
			SortField: "created_at",
			SortDir:   runtime.Desc,
			Mode:      "",
		},

		Fetch: func(ctx context.Context, opts runtime.ListOpts) ([]*ent.Handoff, int, error) {
			q := client.Handoff.Query()
			// Scope predicate — keyed generically via ListOpts.Scope so the
			// runtime stays decoupled from any specific field name.
			if v := opts.Scope["project_id"]; v != "" {
				q = q.Where(entHandoff.ProjectID(v))
			}
			// Legacy substring filter — used by the list+preview browser's
			// global `/` prompt. Phase E (Filters slice) supersedes this
			// in the table view but both can coexist.
			if opts.Filter != "" {
				q = q.Where(entHandoff.Or(
					entHandoff.IDContainsFold(opts.Filter),
					entHandoff.ProjectIDContainsFold(opts.Filter),
					entHandoff.FromActorIDContainsFold(opts.Filter),
					entHandoff.ToActorIDContainsFold(opts.Filter),
					entHandoff.StatusStrContainsFold(opts.Filter),
				))
			}
			// Phase E — structured per-column filters. AND-composed.
			// Unsupported operators for a given field type fall through
			// silently rather than erroring — keeps the UI forgiving.
			for _, f := range opts.Filters {
				switch f.Field {
				case "id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entHandoff.IDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entHandoff.IDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entHandoff.IDContainsFold(f.Value))
					}
				case "project_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entHandoff.ProjectIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entHandoff.ProjectIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entHandoff.ProjectIDContainsFold(f.Value))
					}
				case "from_actor_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entHandoff.FromActorIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entHandoff.FromActorIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entHandoff.FromActorIDContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entHandoff.FromActorIDIsNil())
					case runtime.OpNotNull:
						q = q.Where(entHandoff.FromActorIDNotNil())
					}
				case "to_actor_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entHandoff.ToActorIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entHandoff.ToActorIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entHandoff.ToActorIDContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entHandoff.ToActorIDIsNil())
					case runtime.OpNotNull:
						q = q.Where(entHandoff.ToActorIDNotNil())
					}
				case "status_str":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entHandoff.StatusStrEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entHandoff.StatusStrNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entHandoff.StatusStrContainsFold(f.Value))
					}
				}
			}
			// Phase D — multi-column sort stack. Each Sort entry walks the
			// generated dispatch; unknown fields are silently skipped.
			if len(opts.Sort) > 0 {
				for _, k := range opts.Sort {
					switch k.Field {
					case "id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entHandoff.FieldID))
						} else {
							q = q.Order(ent.Desc(entHandoff.FieldID))
						}
					case "created_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entHandoff.FieldCreatedAt))
						} else {
							q = q.Order(ent.Desc(entHandoff.FieldCreatedAt))
						}
					case "updated_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entHandoff.FieldUpdatedAt))
						} else {
							q = q.Order(ent.Desc(entHandoff.FieldUpdatedAt))
						}
					case "project_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entHandoff.FieldProjectID))
						} else {
							q = q.Order(ent.Desc(entHandoff.FieldProjectID))
						}
					case "from_actor_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entHandoff.FieldFromActorID))
						} else {
							q = q.Order(ent.Desc(entHandoff.FieldFromActorID))
						}
					case "to_actor_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entHandoff.FieldToActorID))
						} else {
							q = q.Order(ent.Desc(entHandoff.FieldToActorID))
						}
					case "status_str":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entHandoff.FieldStatusStr))
						} else {
							q = q.Order(ent.Desc(entHandoff.FieldStatusStr))
						}
					}
				}
			}
			total, err := q.Clone().Count(ctx)
			if err != nil {
				return nil, 0, err
			}
			rows, err := q.Offset(opts.Offset).Limit(opts.Limit).All(ctx)
			return rows, total, err
		},

		// Ent-native JSON for the `J` clipboard shortcut. *ent.Handoff
		// implements MarshalJSON so eager-loaded edges (from With*())
		// land in the output under `edges` automatically.
		JSON: func(r *ent.Handoff) ([]byte, error) { return json.Marshal(r) },

		Columns: []runtime.Column[*ent.Handoff]{
			{
				Key:        "id",
				Label:      "Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Handoff) string {
					return r.ID
				},
			},
			{
				Key:        "created_at",
				Label:      "Created At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Handoff) string {
					if r.CreatedAt.IsZero() {
						return ""
					}
					return r.CreatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "updated_at",
				Label:      "Updated At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Handoff) string {
					if r.UpdatedAt.IsZero() {
						return ""
					}
					return r.UpdatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "project_id",
				Label:      "Project Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Handoff) string {
					return r.ProjectID
				},
			},
			{
				Key:        "from_actor_id",
				Label:      "From Actor Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Handoff) string {
					if r.FromActorID == nil {
						return ""
					}
					return *r.FromActorID
				},
			},
			{
				Key:        "to_actor_id",
				Label:      "To Actor Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Handoff) string {
					if r.ToActorID == nil {
						return ""
					}
					return *r.ToActorID
				},
			},
			{
				Key:        "body",
				Label:      "Body",
				Sortable:   false,
				Filterable: false,
				Hidden:     true,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Handoff) string {
					return r.Body
				},
			},
			{
				Key:        "status_str",
				Label:      "Status Str",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Handoff) string {
					return r.StatusStr
				},
			},
		},
	})
}
