// Code generated by enttui. DO NOT EDIT.

package tuigen

import (
	"context"
	"dbent/gen/ent"
	entPrompt "dbent/gen/ent/prompt"
	"encoding/json"

	"github.com/khanakia/entx/enttui/runtime"
)

// registerPrompt wires *ent.Prompt into the enttui runtime.
//
// Scope filtering: for every scope key configured in enttui.Config.ScopeFields
// that exists on this schema, the Fetch closure below reads opts.Scope[key]
// and applies a predicate when set. Caller drives this via app.SetScope(key, value).
func registerPrompt(app *runtime.App, client *ent.Client) {
	runtime.Register(app, runtime.EntitySpec[*ent.Prompt]{
		Kind:           "prompt",
		Display:        "Prompts",
		Group:          "data",
		Icon:           "•",
		LabelKey:       "name",
		BodyKey:        "body",
		IDKey:          "id",
		PageSize:       200,
		MultiSort:      true,
		ShowEdgeCounts: true,
		AllowBulkCopy:  false,
		AllowExport:    false,
		Default: runtime.DefaultView{
			SortField: "created_at",
			SortDir:   runtime.Desc,
			Mode:      "",
		},

		Fetch: func(ctx context.Context, opts runtime.ListOpts) ([]*ent.Prompt, int, error) {
			q := client.Prompt.Query()
			// Scope predicate — keyed generically via ListOpts.Scope so the
			// runtime stays decoupled from any specific field name.
			if v := opts.Scope["project_id"]; v != "" {
				q = q.Where(entPrompt.ProjectID(v))
			}
			// Legacy substring filter — used by the list+preview browser's
			// global `/` prompt. Phase E (Filters slice) supersedes this
			// in the table view but both can coexist.
			if opts.Filter != "" {
				q = q.Where(entPrompt.Or(
					entPrompt.IDContainsFold(opts.Filter),
					entPrompt.ProjectIDContainsFold(opts.Filter),
					entPrompt.NameContainsFold(opts.Filter),
					entPrompt.ArgsSchemaContainsFold(opts.Filter),
					entPrompt.CreatedByActorIDContainsFold(opts.Filter),
				))
			}
			// Phase E — structured per-column filters. AND-composed.
			// Unsupported operators for a given field type fall through
			// silently rather than erroring — keeps the UI forgiving.
			for _, f := range opts.Filters {
				switch f.Field {
				case "id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entPrompt.IDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entPrompt.IDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entPrompt.IDContainsFold(f.Value))
					}
				case "project_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entPrompt.ProjectIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entPrompt.ProjectIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entPrompt.ProjectIDContainsFold(f.Value))
					}
				case "name":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entPrompt.NameEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entPrompt.NameNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entPrompt.NameContainsFold(f.Value))
					}
				case "args_schema":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entPrompt.ArgsSchemaEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entPrompt.ArgsSchemaNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entPrompt.ArgsSchemaContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entPrompt.ArgsSchemaIsNil())
					case runtime.OpNotNull:
						q = q.Where(entPrompt.ArgsSchemaNotNil())
					}
				case "created_by_actor_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entPrompt.CreatedByActorIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entPrompt.CreatedByActorIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entPrompt.CreatedByActorIDContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entPrompt.CreatedByActorIDIsNil())
					case runtime.OpNotNull:
						q = q.Where(entPrompt.CreatedByActorIDNotNil())
					}
				}
			}
			// Phase D — multi-column sort stack. Each Sort entry walks the
			// generated dispatch; unknown fields are silently skipped.
			if len(opts.Sort) > 0 {
				for _, k := range opts.Sort {
					switch k.Field {
					case "id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entPrompt.FieldID))
						} else {
							q = q.Order(ent.Desc(entPrompt.FieldID))
						}
					case "created_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entPrompt.FieldCreatedAt))
						} else {
							q = q.Order(ent.Desc(entPrompt.FieldCreatedAt))
						}
					case "updated_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entPrompt.FieldUpdatedAt))
						} else {
							q = q.Order(ent.Desc(entPrompt.FieldUpdatedAt))
						}
					case "project_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entPrompt.FieldProjectID))
						} else {
							q = q.Order(ent.Desc(entPrompt.FieldProjectID))
						}
					case "name":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entPrompt.FieldName))
						} else {
							q = q.Order(ent.Desc(entPrompt.FieldName))
						}
					case "args_schema":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entPrompt.FieldArgsSchema))
						} else {
							q = q.Order(ent.Desc(entPrompt.FieldArgsSchema))
						}
					case "archived_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entPrompt.FieldArchivedAt))
						} else {
							q = q.Order(ent.Desc(entPrompt.FieldArchivedAt))
						}
					case "created_by_actor_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entPrompt.FieldCreatedByActorID))
						} else {
							q = q.Order(ent.Desc(entPrompt.FieldCreatedByActorID))
						}
					}
				}
			}
			total, err := q.Clone().Count(ctx)
			if err != nil {
				return nil, 0, err
			}
			rows, err := q.Offset(opts.Offset).Limit(opts.Limit).All(ctx)
			return rows, total, err
		},

		// Ent-native JSON for the `J` clipboard shortcut. *ent.Prompt
		// implements MarshalJSON so eager-loaded edges (from With*())
		// land in the output under `edges` automatically.
		JSON: func(r *ent.Prompt) ([]byte, error) { return json.Marshal(r) },

		Columns: []runtime.Column[*ent.Prompt]{
			{
				Key:        "id",
				Label:      "Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Prompt) string {
					return r.ID
				},
			},
			{
				Key:        "created_at",
				Label:      "Created At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Prompt) string {
					if r.CreatedAt.IsZero() {
						return ""
					}
					return r.CreatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "updated_at",
				Label:      "Updated At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Prompt) string {
					if r.UpdatedAt.IsZero() {
						return ""
					}
					return r.UpdatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "project_id",
				Label:      "Project Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Prompt) string {
					return r.ProjectID
				},
			},
			{
				Key:        "name",
				Label:      "Name",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Prompt) string {
					return r.Name
				},
			},
			{
				Key:        "description",
				Label:      "Description",
				Sortable:   false,
				Filterable: false,
				Hidden:     true,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Prompt) string {
					return r.Description
				},
			},
			{
				Key:        "args_schema",
				Label:      "Args Schema",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Prompt) string {
					if r.ArgsSchema == nil {
						return ""
					}
					return *r.ArgsSchema
				},
			},
			{
				Key:        "body",
				Label:      "Body",
				Sortable:   false,
				Filterable: false,
				Hidden:     true,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Prompt) string {
					return r.Body
				},
			},
			{
				Key:        "archived_at",
				Label:      "Archived At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Prompt) string {
					if r.ArchivedAt == nil || r.ArchivedAt.IsZero() {
						return ""
					}
					return r.ArchivedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "created_by_actor_id",
				Label:      "Created By Actor Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Prompt) string {
					if r.CreatedByActorID == nil {
						return ""
					}
					return *r.CreatedByActorID
				},
			},
		},
	})
}
