// Code generated by enttui. DO NOT EDIT.

package tuigen

import (
	"context"
	"dbent/gen/ent"
	entSession "dbent/gen/ent/session"
	"encoding/json"

	"github.com/khanakia/entx/enttui/runtime"
)

// registerSession wires *ent.Session into the enttui runtime.
//
// Scope filtering: for every scope key configured in enttui.Config.ScopeFields
// that exists on this schema, the Fetch closure below reads opts.Scope[key]
// and applies a predicate when set. Caller drives this via app.SetScope(key, value).
func registerSession(app *runtime.App, client *ent.Client) {
	runtime.Register(app, runtime.EntitySpec[*ent.Session]{
		Kind:           "session",
		Display:        "Sessions",
		Group:          "data",
		Icon:           "•",
		LabelKey:       "id",
		BodyKey:        "",
		IDKey:          "id",
		PageSize:       200,
		MultiSort:      true,
		ShowEdgeCounts: true,
		AllowBulkCopy:  false,
		AllowExport:    false,
		Default: runtime.DefaultView{
			SortField: "created_at",
			SortDir:   runtime.Desc,
			Mode:      "",
		},

		Fetch: func(ctx context.Context, opts runtime.ListOpts) ([]*ent.Session, int, error) {
			q := client.Session.Query()
			// Scope predicate — keyed generically via ListOpts.Scope so the
			// runtime stays decoupled from any specific field name.
			if v := opts.Scope["project_id"]; v != "" {
				q = q.Where(entSession.ProjectID(v))
			}
			// Legacy substring filter — used by the list+preview browser's
			// global `/` prompt. Phase E (Filters slice) supersedes this
			// in the table view but both can coexist.
			if opts.Filter != "" {
				q = q.Where(entSession.Or(
					entSession.IDContainsFold(opts.Filter),
					entSession.ProjectIDContainsFold(opts.Filter),
					entSession.ActorIDContainsFold(opts.Filter),
					entSession.AgentKindContainsFold(opts.Filter),
				))
			}
			// Phase E — structured per-column filters. AND-composed.
			// Unsupported operators for a given field type fall through
			// silently rather than erroring — keeps the UI forgiving.
			for _, f := range opts.Filters {
				switch f.Field {
				case "id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entSession.IDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entSession.IDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entSession.IDContainsFold(f.Value))
					}
				case "project_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entSession.ProjectIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entSession.ProjectIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entSession.ProjectIDContainsFold(f.Value))
					}
				case "actor_id":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entSession.ActorIDEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entSession.ActorIDNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entSession.ActorIDContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entSession.ActorIDIsNil())
					case runtime.OpNotNull:
						q = q.Where(entSession.ActorIDNotNil())
					}
				case "agent_kind":
					switch f.Op {
					case runtime.OpEq:
						q = q.Where(entSession.AgentKindEQ(f.Value))
					case runtime.OpNeq:
						q = q.Where(entSession.AgentKindNEQ(f.Value))
					case runtime.OpContains:
						q = q.Where(entSession.AgentKindContainsFold(f.Value))
					case runtime.OpIsNull:
						q = q.Where(entSession.AgentKindIsNil())
					case runtime.OpNotNull:
						q = q.Where(entSession.AgentKindNotNil())
					}
				}
			}
			// Phase D — multi-column sort stack. Each Sort entry walks the
			// generated dispatch; unknown fields are silently skipped.
			if len(opts.Sort) > 0 {
				for _, k := range opts.Sort {
					switch k.Field {
					case "id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entSession.FieldID))
						} else {
							q = q.Order(ent.Desc(entSession.FieldID))
						}
					case "created_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entSession.FieldCreatedAt))
						} else {
							q = q.Order(ent.Desc(entSession.FieldCreatedAt))
						}
					case "updated_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entSession.FieldUpdatedAt))
						} else {
							q = q.Order(ent.Desc(entSession.FieldUpdatedAt))
						}
					case "project_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entSession.FieldProjectID))
						} else {
							q = q.Order(ent.Desc(entSession.FieldProjectID))
						}
					case "started_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entSession.FieldStartedAt))
						} else {
							q = q.Order(ent.Desc(entSession.FieldStartedAt))
						}
					case "ended_at":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entSession.FieldEndedAt))
						} else {
							q = q.Order(ent.Desc(entSession.FieldEndedAt))
						}
					case "actor_id":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entSession.FieldActorID))
						} else {
							q = q.Order(ent.Desc(entSession.FieldActorID))
						}
					case "agent_kind":
						if k.Dir == runtime.Asc {
							q = q.Order(ent.Asc(entSession.FieldAgentKind))
						} else {
							q = q.Order(ent.Desc(entSession.FieldAgentKind))
						}
					}
				}
			}
			total, err := q.Clone().Count(ctx)
			if err != nil {
				return nil, 0, err
			}
			rows, err := q.Offset(opts.Offset).Limit(opts.Limit).All(ctx)
			return rows, total, err
		},

		// Ent-native JSON for the `J` clipboard shortcut. *ent.Session
		// implements MarshalJSON so eager-loaded edges (from With*())
		// land in the output under `edges` automatically.
		JSON: func(r *ent.Session) ([]byte, error) { return json.Marshal(r) },

		Columns: []runtime.Column[*ent.Session]{
			{
				Key:        "id",
				Label:      "Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Session) string {
					return r.ID
				},
			},
			{
				Key:        "created_at",
				Label:      "Created At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Session) string {
					if r.CreatedAt.IsZero() {
						return ""
					}
					return r.CreatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "updated_at",
				Label:      "Updated At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Session) string {
					if r.UpdatedAt.IsZero() {
						return ""
					}
					return r.UpdatedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "project_id",
				Label:      "Project Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Session) string {
					return r.ProjectID
				},
			},
			{
				Key:        "started_at",
				Label:      "Started At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Session) string {
					if r.StartedAt.IsZero() {
						return ""
					}
					return r.StartedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "ended_at",
				Label:      "Ended At",
				Sortable:   true,
				Filterable: false,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Session) string {
					if r.EndedAt == nil || r.EndedAt.IsZero() {
						return ""
					}
					return r.EndedAt.Format("2006-01-02 15:04:05")
				},
			},
			{
				Key:        "actor_id",
				Label:      "Actor Id",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Session) string {
					if r.ActorID == nil {
						return ""
					}
					return *r.ActorID
				},
			},
			{
				Key:        "agent_kind",
				Label:      "Agent Kind",
				Sortable:   true,
				Filterable: true,
				Hidden:     false,
				Width:      0,
				Align:      "",
				Get: func(r *ent.Session) string {
					if r.AgentKind == nil {
						return ""
					}
					return *r.AgentKind
				},
			},
		},
	})
}
